"""
Draft Agent — AI-first
======================
Generates contract clauses via Vertex AI using the playbook as guidance.

Each clause is generated by a separate AI call that receives:
  - Clause type & drafting-tier posture (preferred / acceptable / fallback).
  - Deal context (parties, jurisdiction, term, purpose).
  - Required defined terms the clause must use.
  - Jurisdiction-specific notes when present.
  - The playbook's template text as a *reference seed* (not a rigid output).

All clauses generate in parallel via ``asyncio.gather`` — a 15-clause NDA runs
in ~10–15 s instead of 2+ minutes sequential, eliminating Stage-2 timeouts.

Section numbering is assigned dynamically at render time, so the clause body
never contains hardcoded numbers. Cross-references use ``{{SECTION_REF:type}}``
placeholders that are resolved after all sections are generated.

Failure mode: if an individual clause AI call fails (timeout, rate-limit,
Vertex down), the agent falls back to the filled template text so the draft
always completes. The fallback paths are logged but never throw.
"""

from __future__ import annotations

import asyncio
import logging
import re
import time
from datetime import date
from typing import Any, Dict, List, Optional, Tuple

from app.core.config import settings
from app.services.prompt_sanitizer import sanitize_for_prompt

from app.services.drafting.models import (
    DraftMetadata,
    DraftRequest,
    DraftSection,
    RawDraft,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Title map
# ---------------------------------------------------------------------------

_TITLE_MAP: Dict[str, str] = {
    "nda_mutual": "MUTUAL NON-DISCLOSURE AGREEMENT",
    "nda_unilateral": "NON-DISCLOSURE AGREEMENT",
    "saas": "SAAS SUBSCRIPTION AGREEMENT",
    "msa": "MASTER SERVICE AGREEMENT",
    "employment": "EMPLOYMENT AGREEMENT",
}

# ---------------------------------------------------------------------------
# Tier selection matrix — mirrored for party_2 so protective keeps the
# customer/receiving side of the table, not the provider's template.
# ---------------------------------------------------------------------------

_TIER_MATRIX: Dict[tuple[str, str], str] = {
    # Party 1 (drafter / provider / disclosing / company): preferred = most aggressive
    ("party_1", "protective"): "preferred",
    ("party_1", "balanced"): "acceptable",
    ("party_1", "commercial"): "fallback",
    ("party_1", "aggressive"): "fallback",
    # Party 2 (counterparty / customer / receiving / employee): mirror —
    # "protective" for them means the *other* side's aggressive tier flipped,
    # which the playbook encodes as the fallback.
    ("party_2", "protective"): "fallback",
    ("party_2", "balanced"): "acceptable",
    ("party_2", "commercial"): "preferred",
    ("party_2", "aggressive"): "preferred",
}

# How long to give each parallel clause-generation call before timing out.
# Stage-2 (the orchestrator) enforces its own overall timeout; this is a
# per-call cap so a single hang doesn't block the gather.
_PER_CLAUSE_TIMEOUT_S = 90.0

# Cap concurrent Vertex AI calls to avoid hitting per-project rate limits.
_MAX_CONCURRENT_CLAUSES = 10


# ---------------------------------------------------------------------------
# Billing frequency normalisation (frontend sends "annually", backend wants
# "annual"; we tolerate both and any reasonable variant)
# ---------------------------------------------------------------------------

def _normalise_billing_frequency(value: str) -> str:
    v = (value or "").lower().strip()
    if v in {"month", "monthly", "per month"}:
        return "monthly"
    if v in {"quarter", "quarterly", "per quarter"}:
        return "quarterly"
    if v in {"annual", "annually", "yearly", "per year", "year"}:
        return "annual"
    return "monthly"  # safe default


_FREQ_MULTIPLIER: Dict[str, int] = {"monthly": 12, "quarterly": 4, "annual": 1}


class DraftAgent:
    """AI-first drafting agent — builds a RawDraft from a request and playbook."""

    # ------------------------------------------------------------------
    # Tier selection
    # ------------------------------------------------------------------

    @staticmethod
    def _select_tier(
        perspective: str,
        risk_appetite: str,
        clause_category: str | None = None,
        risk_profile: dict[str, str] | None = None,
    ) -> str:
        """Map (perspective, risk_appetite) to a playbook tier name.

        Per-clause override via ``risk_profile`` takes priority when the
        clause_category is present in the profile. Otherwise falls back to
        the global perspective/risk_appetite matrix (which mirrors tiers
        for party_2).
        """
        if risk_profile and clause_category and clause_category in risk_profile:
            override = risk_profile[clause_category].lower()
            return {
                "protective": "preferred",
                "balanced": "acceptable",
                "commercial": "fallback",
                "aggressive": "fallback",
            }.get(override, "acceptable")

        if perspective == "balanced":
            return "acceptable"
        return _TIER_MATRIX.get((perspective, risk_appetite), "acceptable")

    # ------------------------------------------------------------------
    # Context building (not "placeholders" any more — this is the AI's
    # prompt context, which is cleaner than regex substitution)
    # ------------------------------------------------------------------

    @staticmethod
    def _build_context(req: DraftRequest) -> Dict[str, Any]:
        """Build structured context passed into every clause-generation prompt."""
        eff_date = (
            req.effective_date.isoformat()
            if req.effective_date
            else date.today().isoformat()
        )

        ctx: Dict[str, Any] = {
            "contract_type": req.contract_type,
            "effective_date": eff_date,
            "term_months": req.term_months,
            "governing_law": req.governing_law,
            "dispute_resolution": req.dispute_resolution,
            "venue": req.venue or req.governing_law,
            "jurisdiction": req.jurisdiction,
            "perspective": req.drafting_perspective,
            "risk_appetite": req.risk_appetite,
            # Parties
            "party_1": {
                "name": req.party_1.name,
                "short_name": req.party_1.name.split()[0],
                "entity_type": req.party_1.entity_type,
                "jurisdiction": req.party_1.jurisdiction,
                "address": req.party_1.address or None,
            },
            "party_2": {
                "name": req.party_2.name,
                "short_name": req.party_2.name.split()[0],
                "entity_type": req.party_2.entity_type,
                "jurisdiction": req.party_2.jurisdiction,
                "address": req.party_2.address or None,
            },
        }

        # Role aliases (for prompt readability)
        if req.contract_type.startswith("nda"):
            if req.contract_type == "nda_unilateral":
                ctx["roles"] = {
                    "disclosing_party": ctx["party_1"]["name"],
                    "receiving_party": ctx["party_2"]["name"],
                }
        elif req.contract_type == "saas":
            ctx["roles"] = {
                "provider": ctx["party_1"]["name"],
                "customer": ctx["party_2"]["name"],
            }
        elif req.contract_type == "msa":
            ctx["roles"] = {
                "service_provider": ctx["party_1"]["name"],
                "client": ctx["party_2"]["name"],
            }
        elif req.contract_type == "employment":
            ctx["roles"] = {
                "company": ctx["party_1"]["name"],
                "employee": ctx["party_2"]["name"],
            }

        # NDA details
        if req.nda_details:
            ctx["nda"] = {
                "purpose": req.nda_details.purpose,
                "survival_years": req.nda_details.confidentiality_survival_years,
                "non_solicitation": req.nda_details.non_solicitation,
                "non_solicitation_months": req.nda_details.non_solicitation_months or 12,
                "marking_requirement": req.nda_details.marking_requirement,
                "ci_categories": (
                    req.nda_details.ci_categories
                    or [
                        "technical data",
                        "trade secrets",
                        "business plans",
                        "financial information",
                    ]
                ),
            }

        # SaaS details
        if req.saas_details:
            saas = req.saas_details
            bf = _normalise_billing_frequency(saas.billing_frequency)
            multiplier = _FREQ_MULTIPLIER[bf]
            ctx["saas"] = {
                "service_description": saas.service_description,
                "pricing_model": saas.pricing_model,
                "price_amount": saas.price_amount,
                "price_formatted": f"${saas.price_amount:,.2f}",
                "billing_frequency": bf,
                "auto_renewal": saas.auto_renewal,
                "uptime_commitment": saas.uptime_commitment or 99.9,
                "authorized_users": saas.authorized_users,
                "liability_cap_months": saas.liability_cap_months,
                "compliance_frameworks": saas.compliance_frameworks or [],
                "data_regions": saas.data_regions or [],
                "support_tiers": saas.support_tiers or {},
                "annual_value": saas.price_amount * multiplier,
                "annual_value_formatted": f"${saas.price_amount * multiplier:,.2f}",
            }

        # Employment details (fields are optional on DraftRequest)
        if req.contract_type == "employment":
            ctx["employment"] = {
                "title": getattr(req, "employee_title", None),
                "base_salary": getattr(req, "base_salary", None),
                "reporting_manager": getattr(req, "reporting_manager", None),
                "work_location": getattr(req, "work_location", None),
            }

        return ctx

    # ------------------------------------------------------------------
    # Backwards-compatible placeholder builder (used by fallback template
    # path when AI is unavailable)
    # ------------------------------------------------------------------

    @staticmethod
    def _build_placeholders(req: DraftRequest) -> Dict[str, str]:
        """Flat key-value dict used only by the fallback template filler."""
        eff_date = (
            req.effective_date.isoformat()
            if req.effective_date
            else date.today().isoformat()
        )

        p: Dict[str, str] = {
            "party_1_name": req.party_1.name,
            "party_1_short_name": req.party_1.name.split()[0],
            "party_1_entity_type": req.party_1.entity_type,
            "party_1_jurisdiction": req.party_1.jurisdiction,
            "party_1_address": req.party_1.address or "",
            "party_2_name": req.party_2.name,
            "party_2_short_name": req.party_2.name.split()[0],
            "party_2_entity_type": req.party_2.entity_type,
            "party_2_jurisdiction": req.party_2.jurisdiction,
            "party_2_address": req.party_2.address or "",
            "effective_date": eff_date,
            "term_months": str(req.term_months),
            "governing_law": req.governing_law,
            "dispute_resolution": req.dispute_resolution,
            "venue": req.venue or req.governing_law,
        }

        # Role aliases
        p["disclosing_party_name"] = p["party_1_name"]
        p["disclosing_party_short_name"] = p["party_1_short_name"]
        p["receiving_party_name"] = p["party_2_name"]
        p["receiving_party_short_name"] = p["party_2_short_name"]
        p["provider_name"] = p["party_1_name"]
        p["provider_short_name"] = p["party_1_short_name"]
        p["provider_entity_type"] = p["party_1_entity_type"]
        p["provider_jurisdiction"] = p["party_1_jurisdiction"]
        p["provider_address"] = p["party_1_address"]
        p["customer_name"] = p["party_2_name"]
        p["customer_short_name"] = p["party_2_short_name"]
        p["customer_entity_type"] = p["party_2_entity_type"]
        p["customer_jurisdiction"] = p["party_2_jurisdiction"]
        p["customer_address"] = p["party_2_address"]
        p["service_provider_name"] = p["party_1_name"]
        p["client_name"] = p["party_2_name"]
        p["company_name"] = p["party_1_name"]
        p["employee_name"] = p["party_2_name"]

        p["confidentiality_survival_years"] = "3"

        if req.contract_type == "employment":
            p["employee_title"] = getattr(req, "employee_title", None) or ""
            p["base_salary"] = getattr(req, "base_salary", None) or ""
            p["reporting_manager"] = getattr(req, "reporting_manager", None) or ""
            p["work_location"] = getattr(req, "work_location", None) or ""

        if req.nda_details:
            nda = req.nda_details
            p["purpose"] = nda.purpose
            p["confidentiality_survival_years"] = str(nda.confidentiality_survival_years)
            p["non_solicitation_months"] = str(nda.non_solicitation_months or 12)
            p["ci_categories_clause"] = (
                ", ".join(nda.ci_categories)
                if nda.ci_categories
                else "technical data, trade secrets, business plans, financial information"
            )

        if req.saas_details:
            saas = req.saas_details
            bf = _normalise_billing_frequency(saas.billing_frequency)
            multiplier = _FREQ_MULTIPLIER[bf]
            p["service_description"] = saas.service_description
            p["pricing_model"] = saas.pricing_model
            p["price_amount"] = f"{saas.price_amount:,.2f}"
            p["billing_frequency"] = bf
            p["uptime_commitment"] = (
                f"{saas.uptime_commitment}%" if saas.uptime_commitment else "99.9%"
            )
            p["authorized_users"] = str(saas.authorized_users or "unlimited")
            p["auto_renewal_text"] = (
                "automatically renew for successive periods of equal length"
                if saas.auto_renewal
                else "expire at the end of the Initial Term unless renewed in writing"
            )
            p["annual_value"] = f"{saas.price_amount * multiplier:,.2f}"

        return p

    # ------------------------------------------------------------------
    # Template rendering (fallback only)
    # ------------------------------------------------------------------

    @staticmethod
    def _fill_placeholders(template: str, placeholders: Dict[str, str]) -> str:
        """Replace ``{{key}}`` tokens with values from *placeholders*."""

        def _replacer(match: re.Match) -> str:
            key = match.group(1).strip()
            value = placeholders.get(key, "")
            return value if value else ""

        return re.sub(r"\{\{(\s*\w+\s*)\}\}", _replacer, template)

    # ------------------------------------------------------------------
    # Conditional inclusion
    # ------------------------------------------------------------------

    @staticmethod
    def _should_include(clause: Dict[str, Any], req: DraftRequest) -> bool:
        if clause.get("is_required", True):
            return True

        condition = clause.get("conditional_on")
        if not condition:
            return True

        match = re.match(r"([\w.]+)\s*==\s*(.+)", condition.strip())
        if not match:
            return True

        path_str, expected_raw = match.group(1), match.group(2).strip()

        obj: Any = req
        for part in path_str.split("."):
            obj = getattr(obj, part, None)
            if obj is None:
                return False

        if expected_raw.lower() == "true":
            return bool(obj) is True
        if expected_raw.lower() == "false":
            return bool(obj) is False

        return str(obj) == expected_raw

    # ------------------------------------------------------------------
    # Clause prompt construction
    # ------------------------------------------------------------------

    @staticmethod
    def _build_clause_prompt(
        clause: Dict[str, Any],
        tier_name: str,
        context: Dict[str, Any],
        seed_text: str,
        tier_guidance: str,
    ) -> str:
        """Build the per-clause prompt for Vertex AI."""
        clause_type = clause.get("clause_type", "clause")
        heading = clause.get("section_heading", "")
        drafting_notes = clause.get("drafting_notes", "")
        required_terms = clause.get("required_defined_terms", [])
        cross_refs = clause.get("cross_references", [])

        # Resolve jurisdiction variant (specific first, then country prefix)
        jur = context.get("jurisdiction", "")
        jur_key = jur.split("-")[0] if jur else ""
        jur_variants = clause.get("jurisdiction_variants", {})
        jur_variant = jur_variants.get(jur) or jur_variants.get(jur_key) or ""

        # Map tier → legal posture directive
        tier_directive = {
            "preferred": (
                "Draft this clause in its MOST PROTECTIVE form for the drafting "
                "party. Use firm, assertive language. Narrow exceptions. Short "
                "cure periods. Broad carve-outs. This is the 'open strong' tier."
            ),
            "acceptable": (
                "Draft this clause as a BALANCED, market-standard provision. "
                "Language should be fair to both sides and match what a "
                "reasonable senior associate would produce for an arm's-length "
                "deal. This is the settlement tier."
            ),
            "fallback": (
                "Draft this clause in its COMMERCIAL / COUNTERPARTY-FRIENDLY form. "
                "Softer language ('commercially reasonable efforts'), longer "
                "cure periods, broader exceptions, mutual obligations where "
                "possible. This is the floor — the minimum you'd accept."
            ),
        }.get(tier_name, "Balanced market-standard language.")

        # Perspective directive
        perspective = context.get("perspective", "balanced")
        if perspective == "party_1":
            perspective_note = "The drafting party is Party 1 (the primary party in the preamble)."
        elif perspective == "party_2":
            perspective_note = (
                "The drafting party is Party 2 — the counterparty. Tilt protections "
                "and obligations appropriately so Party 2 has the stronger position."
            )
        else:
            perspective_note = "Draft neutrally, with no party favored."

        # Compact context block
        parties_block = (
            f"- Party 1: {context['party_1']['name']} ({context['party_1']['entity_type']}, "
            f"{context['party_1']['jurisdiction']})\n"
            f"- Party 2: {context['party_2']['name']} ({context['party_2']['entity_type']}, "
            f"{context['party_2']['jurisdiction']})"
        )
        roles = context.get("roles", {})
        roles_block = (
            "\n".join(f"- {k.replace('_', ' ').title()}: {v}" for k, v in roles.items())
            if roles
            else ""
        )

        deal_block = (
            f"- Effective date: {context.get('effective_date', 'TBD')}\n"
            f"- Term: {context.get('term_months', 12)} months\n"
            f"- Governing law: {context.get('governing_law', '(unspecified)')}\n"
            f"- Dispute resolution: {context.get('dispute_resolution', 'arbitration')}\n"
            f"- Venue: {context.get('venue', '(unspecified)')}"
        )

        nda_block = ""
        if "nda" in context:
            n = context["nda"]
            ci_cat_line = ", ".join(n["ci_categories"])
            nda_block = (
                "\nNDA-specific context:\n"
                f"- Purpose of disclosure: {n['purpose']}\n"
                f"- Confidentiality survival: {n['survival_years']} years\n"
                f"- Non-solicitation included: {n['non_solicitation']} "
                f"({n['non_solicitation_months']} months)\n"
                f"- Marking requirement: {n['marking_requirement']}\n"
                f"- Categories of confidential information: {ci_cat_line}"
            )

        employment_block = ""
        employment_clause_directive = ""
        if "employment" in context:
            e = context["employment"]
            employment_block = (
                "\nEmployment-specific context:\n"
                f"- Position / Title: {e.get('title') or '(unspecified)'}\n"
                f"- Base salary: {e.get('base_salary') or '(unspecified)'}\n"
                f"- Reporting manager: {e.get('reporting_manager') or '(unspecified)'}\n"
                f"- Work location: {e.get('work_location') or 'Hybrid'}"
            )
            emp_directives: list[str] = []
            if clause_type in ("position_duties", "preamble") and e.get("title"):
                emp_directives.append(
                    f"MANDATORY: Employee's position / job title is exactly "
                    f"'{e['title']}' — use this verbatim, do not paraphrase."
                )
            if clause_type == "compensation" and e.get("base_salary"):
                emp_directives.append(
                    f"MANDATORY: Base salary must be exactly {e['base_salary']} — "
                    f"do not substitute a placeholder or different amount."
                )
            if clause_type in ("position_duties", "work_hours") and e.get("reporting_manager"):
                emp_directives.append(
                    f"MANDATORY: Employee reports to {e['reporting_manager']}."
                )
            if clause_type == "work_hours" and e.get("work_location"):
                emp_directives.append(
                    f"MANDATORY: Work location arrangement is "
                    f"'{e['work_location']}' — reflect this exactly."
                )
            if emp_directives:
                employment_clause_directive = (
                    "\n\nClause-specific mandates (override tier defaults):\n- "
                    + "\n- ".join(emp_directives)
                )

        saas_block = ""
        saas_clause_directive = ""
        if "saas" in context:
            s = context["saas"]
            frameworks_list = s["compliance_frameworks"]
            frameworks = ", ".join(frameworks_list) or "(none specified)"
            regions_list = s["data_regions"]
            regions = ", ".join(regions_list) or "(not specified)"
            cap_months = s["liability_cap_months"] or "(follow tier standard)"
            support_tiers = s.get("support_tiers") or {}
            support_line = (
                ", ".join(f"{k}: {v}" for k, v in support_tiers.items())
                if support_tiers
                else "(use tier defaults)"
            )
            saas_block = (
                "\nSaaS-specific context:\n"
                f"- Service: {s['service_description']}\n"
                f"- Pricing: {s['price_formatted']} per {s['billing_frequency']} billing period, "
                f"{s['pricing_model']} pricing\n"
                f"- Estimated annual value: {s['annual_value_formatted']}\n"
                f"- Auto-renewal: {s['auto_renewal']}\n"
                f"- Uptime commitment: {s['uptime_commitment']}%\n"
                f"- Authorized users: {s['authorized_users'] or '(unlimited)'}\n"
                f"- Requested liability cap: {cap_months} months of fees\n"
                f"- Compliance frameworks to reference: {frameworks}\n"
                f"- Data processing regions: {regions}\n"
                f"- Customer-specified support tiers: {support_line}"
            )

            # Per-clause directives that force the AI to HONOR the user's SaaS
            # knobs. Without these, generic prompts often ignore the specific
            # numbers/frameworks and fall back to playbook defaults.
            directives: list[str] = []
            if clause_type == "limitation_of_liability" and s.get("liability_cap_months"):
                directives.append(
                    f"MANDATORY: The aggregate liability cap for this clause MUST be "
                    f"exactly {s['liability_cap_months']} months of fees paid by Customer "
                    f"in the {('12 months' if s['liability_cap_months'] >= 12 else f'{s['liability_cap_months']} months')} "
                    f"preceding the claim. Do NOT substitute a different cap. If the tier "
                    f"would normally use a different cap, override it with "
                    f"{s['liability_cap_months']} months of fees."
                )
            if clause_type in ("data_security", "dpa") and frameworks_list:
                directives.append(
                    f"MANDATORY: This clause MUST reference the following compliance "
                    f"frameworks explicitly by name: {', '.join(frameworks_list)}. "
                    f"Provider's security / data-protection obligations must be "
                    f"framed as aligning with these specific frameworks."
                )
            if clause_type in ("data_security", "dpa", "data_ownership") and regions_list:
                directives.append(
                    f"MANDATORY: Reference the following data processing regions "
                    f"explicitly where relevant: {', '.join(regions_list)}. "
                    f"Data shall be processed and stored in these regions."
                )
            if clause_type == "grant_of_license" and s.get("authorized_users"):
                directives.append(
                    f"MANDATORY: The license grant must reference the specific "
                    f"authorized-user cap of {s['authorized_users']} users."
                )
            if clause_type == "sla" and support_tiers:
                tiers_text = "; ".join(f"{k} — {v}" for k, v in support_tiers.items())
                directives.append(
                    f"MANDATORY: The SLA support section must reflect the "
                    f"Customer-specified support tiers exactly: {tiers_text}. "
                    f"Structure the P1/P2/P3/P4 response matrix to match these tier "
                    f"commitments."
                )
            if directives:
                saas_clause_directive = (
                    "\n\nClause-specific mandates (override tier defaults with these):\n- "
                    + "\n- ".join(directives)
                )

        required_terms_block = (
            f"\nRequired defined terms this clause MUST use: {', '.join(required_terms)}"
            if required_terms
            else ""
        )

        jur_block = f"\nJurisdiction note ({jur}): {jur_variant}" if jur_variant else ""

        cross_ref_block = ""
        if cross_refs:
            cross_ref_text = ", ".join(cross_refs)
            cross_ref_block = (
                f"\nThis clause cross-references these other clause types: {cross_ref_text}. "
                "Use the token {{REF:clause_type}} where you would otherwise write "
                "'Section X'. These tokens will be replaced with the real section "
                "numbers after all clauses are generated. Example: "
                "'notwithstanding {{REF:liability}}' or 'as defined in {{REF:definitions}}'."
            )

        seed_block = ""
        if seed_text:
            seed_block = (
                "\n\nReference language from the firm's playbook (use as inspiration, "
                "NOT as a rigid template — you may restructure, tighten, or rewrite "
                "this freely):\n---\n"
                f"{sanitize_for_prompt(seed_text, max_length=3000)}\n---"
            )

        drafting_notes_block = (
            f"\nPlaybook drafting notes: {drafting_notes}" if drafting_notes else ""
        )

        prompt = (
            f"You are a senior contract attorney drafting a single clause of a "
            f"{context['contract_type'].replace('_', ' ').upper()}.\n\n"
            f"Clause to draft: **{heading}** (type: {clause_type})\n\n"
            f"Tier posture: {tier_name.upper()}\n"
            f"{tier_directive}\n\n"
            f"Perspective: {perspective_note}\n\n"
            "Deal context:\n"
            f"{parties_block}\n"
            f"{roles_block}\n"
            f"{deal_block}"
            f"{nda_block}"
            f"{saas_block}"
            f"{saas_clause_directive}"
            f"{employment_block}"
            f"{employment_clause_directive}"
            f"{required_terms_block}"
            f"{jur_block}"
            f"{cross_ref_block}"
            f"{drafting_notes_block}"
            f"{seed_block}\n\n"
            "OUTPUT INSTRUCTIONS (critical):\n"
            "1. Return ONLY the clause body text. No heading. No section "
            "number (those are added by the renderer).\n"
            "2. No markdown formatting. No code fences. No ``` anywhere.\n"
            "3. Do NOT include any preamble like 'Here is the clause' or "
            "'Certainly, below is...'. Start directly with the first word of the clause.\n"
            "4. Use proper legal prose. Defined terms capitalized. Numbered "
            "sub-paragraphs (a), (b), (c) where a clause has multiple parts.\n"
            "5. Length: 2–6 paragraphs, appropriate for this clause type. "
            "Boilerplate sections may be shorter (but at least one full sentence); "
            "substantive sections (liability, indemnification, IP) should be thorough.\n"
            "6. NEVER respond with just a cross-reference like 'Section 3' or a "
            "fragment — always produce the full operative clause text. "
            "Cross-references belong INSIDE the clause body, not as the whole body.\n"
            "7. All dates, names, amounts from the deal context above must be "
            "used verbatim — do not substitute placeholders like [Date] or XXX.\n"
            "8. For cross-references, use {{REF:clause_type}} tokens exactly as "
            "instructed above."
        )

        return prompt

    # ------------------------------------------------------------------
    # Per-clause AI generation
    # ------------------------------------------------------------------

    async def _ai_generate_clause(
        self,
        clause: Dict[str, Any],
        tier_name: str,
        context: Dict[str, Any],
        semaphore: asyncio.Semaphore,
    ) -> Tuple[str, int, bool]:
        """Generate a single clause via Vertex AI. Returns (text, tokens, ai_used)."""
        # Get tier-specific seed + guidance from the playbook (still useful as
        # a knowledge anchor for the AI)
        tier_data = clause.get(tier_name, clause.get("acceptable", {}))
        seed_text = tier_data.get("template_text", "")
        tier_guidance = tier_data.get("guidance", "")

        # Fallback immediately if no Vertex AI
        try:
            from app.core.vertex_client import get_generative_model, is_available
        except ImportError:
            logger.warning("Vertex client unavailable, falling back to seed text")
            return seed_text, 0, False

        if not is_available():
            logger.warning("Vertex AI not configured, falling back to seed text")
            return seed_text, 0, False

        prompt = self._build_clause_prompt(
            clause, tier_name, context, seed_text, tier_guidance
        )

        # Strip markdown fences from AI output
        try:
            from app.services.gemini_analyzer import _strip_markdown_fences
        except ImportError:
            def _strip_markdown_fences(t: str) -> str:
                return t.strip()

        async def _call_vertex(prompt_text: str, attempt: int) -> Tuple[str, int]:
            """Single AI call — returns (text, tokens). Raises on failure."""
            from google.genai.types import GenerateContentConfig
            model = get_generative_model(settings.GEMINI_MODEL)
            response = await asyncio.wait_for(
                model.generate_content_async(
                    [{"role": "user", "parts": [{"text": prompt_text}]}],
                    generation_config=GenerateContentConfig(
                        temperature=0.3 + (0.1 * attempt),  # nudge variety on retry
                        max_output_tokens=3500,
                    ),
                ),
                timeout=_PER_CLAUSE_TIMEOUT_S,
            )
            raw = getattr(response, "text", None) or ""
            cleaned = _strip_markdown_fences(raw).strip()
            tokens = 0
            usage = getattr(response, "usage_metadata", None)
            if usage is not None:
                tokens = getattr(usage, "total_token_count", 0) or 0
            return cleaned, tokens

        # Minimum meaningful clause length — short boilerplate sections like
        # signature blocks can be brief, but anything under this is almost
        # always a bad/truncated AI output.
        MIN_CLAUSE_CHARS = 80

        async with semaphore:
            total_tokens = 0
            for attempt in range(2):  # initial call + 1 retry
                try:
                    text, tokens = await _call_vertex(prompt, attempt)
                    total_tokens += tokens

                    if not text:
                        logger.warning(
                            "Attempt %d: AI returned empty text for clause %s",
                            attempt + 1,
                            clause.get("clause_type"),
                        )
                        continue

                    if len(text) < MIN_CLAUSE_CHARS:
                        logger.warning(
                            "Attempt %d: AI output too short (%d chars) for clause %s: %r",
                            attempt + 1,
                            len(text),
                            clause.get("clause_type"),
                            text[:100],
                        )
                        # Retry with adjusted prompt asking for more detail
                        prompt = prompt + (
                            "\n\nIMPORTANT: Your previous response was too brief. "
                            "Provide the complete clause body text (2-6 paragraphs). "
                            "Do not respond with just a cross-reference or fragment."
                        )
                        continue

                    return text, total_tokens, True

                except asyncio.TimeoutError:
                    logger.warning(
                        "Clause %s timed out on attempt %d after %.0fs",
                        clause.get("clause_type"),
                        attempt + 1,
                        _PER_CLAUSE_TIMEOUT_S,
                    )
                    # Don't retry on timeout — fall through to seed
                    break
                except Exception as e:
                    logger.warning(
                        "Clause %s AI call %d failed (%s)",
                        clause.get("clause_type"),
                        attempt + 1,
                        type(e).__name__,
                    )
                    # Only retry on transient errors, not validation/etc.
                    continue

            logger.warning(
                "Clause %s falling back to seed text after retries",
                clause.get("clause_type"),
            )
            return seed_text, total_tokens, False

    # ------------------------------------------------------------------
    # Cross-reference resolution (post-process)
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_cross_refs(sections: List[DraftSection]) -> List[DraftSection]:
        """Replace ``{{REF:clause_type}}`` tokens with real section numbers."""
        clause_type_to_number = {
            s.clause_type: s.number for s in sections
        }

        def _replacer(match: re.Match) -> str:
            key = match.group(1).strip()
            num = clause_type_to_number.get(key)
            if num:
                return f"Section {num}"
            # Unresolved reference — fall back to a human-readable form
            pretty = key.replace("_", " ").title()
            return f"Section ({pretty})"

        pattern = re.compile(r"\{\{\s*REF\s*:\s*([\w_]+)\s*\}\}")
        updated: List[DraftSection] = []
        for s in sections:
            new_content = pattern.sub(_replacer, s.content)
            if new_content != s.content:
                updated.append(DraftSection(
                    number=s.number,
                    heading=s.heading,
                    content=new_content,
                    clause_type=s.clause_type,
                    tier_used=s.tier_used,
                    notes=s.notes,
                ))
            else:
                updated.append(s)
        return updated

    # ------------------------------------------------------------------
    # Main generation
    # ------------------------------------------------------------------

    async def generate(
        self,
        req: DraftRequest,
        playbook: Dict[str, Any],
    ) -> RawDraft:
        """Build a full RawDraft from *req* using *playbook* as guidance.

        Each clause generates in parallel via Vertex AI. Section numbers
        are assigned dynamically; cross-references are resolved after
        all clauses complete.
        """
        start = time.monotonic()

        context = self._build_context(req)
        placeholders = self._build_placeholders(req)

        clause_list: List[Dict[str, Any]] = playbook.get("clauses", [])
        # Filter + sort
        clauses_to_generate: List[Tuple[Dict[str, Any], str]] = []
        for clause in sorted(
            clause_list, key=lambda c: c.get("position_in_order", 0)
        ):
            if not self._should_include(clause, req):
                continue
            clause_category = clause.get("category", clause.get("clause_type"))
            tier_name = self._select_tier(
                req.drafting_perspective,
                req.risk_appetite,
                clause_category=clause_category,
                risk_profile=getattr(req, "risk_profile", None) or None,
            )
            clauses_to_generate.append((clause, tier_name))

        logger.info(
            "Generating %d clauses in parallel (concurrency=%d, timeout=%ds/clause)",
            len(clauses_to_generate),
            _MAX_CONCURRENT_CLAUSES,
            int(_PER_CLAUSE_TIMEOUT_S),
        )

        # Parallel generation with concurrency cap
        semaphore = asyncio.Semaphore(_MAX_CONCURRENT_CLAUSES)
        tasks = [
            self._ai_generate_clause(clause, tier, context, semaphore)
            for clause, tier in clauses_to_generate
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        # Build sections
        sections: List[DraftSection] = []
        defined_terms: Dict[str, str] = {}
        tokens_used = 0
        ai_clauses = 0

        for i, ((clause, tier_name), result) in enumerate(
            zip(clauses_to_generate, results), 1
        ):
            # If gather caught an exception, log and fall back to seed
            if isinstance(result, BaseException):
                logger.error(
                    "Unexpected error in clause %s: %s",
                    clause.get("clause_type"),
                    result,
                )
                tier_data = clause.get(tier_name, clause.get("acceptable", {}))
                content = self._fill_placeholders(
                    tier_data.get("template_text", ""), placeholders
                )
                ai_used = False
            else:
                content, tokens, ai_used = result
                tokens_used += tokens
                if ai_used:
                    ai_clauses += 1
                else:
                    # Fill placeholders in the seed fallback
                    content = self._fill_placeholders(content, placeholders)

            sections.append(
                DraftSection(
                    number=str(i),
                    heading=clause.get("section_heading", ""),
                    content=content.strip(),
                    clause_type=clause.get("clause_type", "unknown"),
                    tier_used=tier_name,
                    notes=clause.get("drafting_notes"),
                )
            )

            for term in clause.get("required_defined_terms", []):
                defined_terms.setdefault(term, clause.get("section_heading", ""))

        # Resolve {{REF:clause_type}} tokens
        sections = self._resolve_cross_refs(sections)

        elapsed = time.monotonic() - start
        title = _TITLE_MAP.get(
            req.contract_type,
            req.contract_type.upper().replace("_", " ") + " AGREEMENT",
        )

        logger.info(
            "Draft complete: %d sections (%d AI-generated, %d fallback) in %.1fs, %d tokens",
            len(sections),
            ai_clauses,
            len(sections) - ai_clauses,
            elapsed,
            tokens_used,
        )

        return RawDraft(
            contract_type=req.contract_type,
            title=title,
            sections=sections,
            defined_terms=defined_terms,
            metadata=DraftMetadata(
                playbook_id=playbook.get("contract_type", req.contract_type),
                model=settings.GEMINI_MODEL,
                generation_seconds=round(elapsed, 3),
                tokens_used=tokens_used,
            ),
        )
