"""
Draft Agent — AI-first
======================
Generates contract clauses via Vertex AI using the playbook as guidance.

Each clause is generated by a separate AI call that receives:
  - Clause type & drafting-tier posture (preferred / acceptable / fallback).
  - Deal context (parties, jurisdiction, term, purpose).
  - Required defined terms the clause must use.
  - Jurisdiction-specific notes when present.
  - The playbook's template text as a *reference seed* (not a rigid output).

All clauses generate in parallel via ``asyncio.gather`` — a 15-clause NDA runs
in ~10–15 s instead of 2+ minutes sequential, eliminating Stage-2 timeouts.

Section numbering is assigned dynamically at render time, so the clause body
never contains hardcoded numbers. Cross-references use ``{{SECTION_REF:type}}``
placeholders that are resolved after all sections are generated.

Failure mode: if an individual clause AI call fails (timeout, rate-limit,
Vertex down), the agent falls back to the filled template text so the draft
always completes. The fallback paths are logged but never throw.
"""

from __future__ import annotations

import asyncio
import logging
import re
import time
from datetime import date
from typing import Any, Dict, List, Optional, Tuple

from app.core.config import settings
from app.services.prompt_sanitizer import sanitize_for_prompt

from app.services.drafting.models import (
    DraftMetadata,
    DraftRequest,
    DraftSection,
    RawDraft,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Title map
# ---------------------------------------------------------------------------

_TITLE_MAP: Dict[str, str] = {
    "nda_mutual": "MUTUAL NON-DISCLOSURE AGREEMENT",
    "nda_unilateral": "NON-DISCLOSURE AGREEMENT",
    "saas": "SAAS SUBSCRIPTION AGREEMENT",
    "msa": "MASTER SERVICE AGREEMENT",
    "employment": "EMPLOYMENT AGREEMENT",
}

# ---------------------------------------------------------------------------
# Tier selection matrix — mirrored for party_2 so protective keeps the
# customer/receiving side of the table, not the provider's template.
# ---------------------------------------------------------------------------

_TIER_MATRIX: Dict[tuple[str, str], str] = {
    # Party 1 (drafter / provider / disclosing / company): preferred = most aggressive
    ("party_1", "protective"): "preferred",
    ("party_1", "balanced"): "acceptable",
    ("party_1", "commercial"): "fallback",
    ("party_1", "aggressive"): "fallback",
    # Party 2 (counterparty / customer / receiving / employee): mirror —
    # "protective" for them means the *other* side's aggressive tier flipped,
    # which the playbook encodes as the fallback.
    ("party_2", "protective"): "fallback",
    ("party_2", "balanced"): "acceptable",
    ("party_2", "commercial"): "preferred",
    ("party_2", "aggressive"): "preferred",
}

# How long to give each parallel clause-generation call before timing out.
# Stage-2 (the orchestrator) enforces its own overall timeout; this is a
# per-call cap so a single hang doesn't block the gather.
_PER_CLAUSE_TIMEOUT_S = 90.0

# Cap concurrent Vertex AI calls to avoid hitting per-project rate limits.
_MAX_CONCURRENT_CLAUSES = 10


# ---------------------------------------------------------------------------
# Billing frequency normalisation (frontend sends "annually", backend wants
# "annual"; we tolerate both and any reasonable variant)
# ---------------------------------------------------------------------------

def _normalise_billing_frequency(value: str) -> str:
    v = (value or "").lower().strip()
    if v in {"month", "monthly", "per month"}:
        return "monthly"
    if v in {"quarter", "quarterly", "per quarter"}:
        return "quarterly"
    if v in {"annual", "annually", "yearly", "per year", "year"}:
        return "annual"
    return "monthly"  # safe default


_FREQ_MULTIPLIER: Dict[str, int] = {"monthly": 12, "quarterly": 4, "annual": 1}


def _strip_leading_heading(text: str, heading: str = "") -> str:
    """Strip any leading section-heading line the AI may have added.

    The renderer adds its own numbered heading. If the AI starts the body with
    something like "12. LIMITATION OF LIABILITY." or "LIMITATION OF LIABILITY.",
    remove that prefix so the document doesn't double-heading.
    """
    if not text:
        return text

    # Match patterns like:
    #   "12. LIMITATION OF LIABILITY."
    #   "12.1 Liability Cap."
    #   "LIMITATION OF LIABILITY."
    #   "Limitation of Liability."
    # followed by \n or \s+ (run-in heading).
    patterns = [
        # Numbered heading: "12.", "12.1 ", "I.", "A.", "(a)" etc. followed by UPPERCASE title
        r"^\s*(?:\d+(?:\.\d+)?|[IVX]+|[A-Z]|\([a-z]\))\.?\s+[A-Z][A-Z\s,&]+(?:\.\s+|\n)",
        # Just UPPERCASE run-in heading like "LIMITATION OF LIABILITY."
        r"^\s*[A-Z][A-Z\s,&]{5,}(?:\.\s+|\n)",
    ]
    for pat in patterns:
        m = re.match(pat, text)
        if m:
            remaining = text[m.end():].strip()
            # Sanity: only strip if what follows is a full clause body (not just another line)
            if len(remaining) > 40:
                text = remaining
                break

    # Additionally: if the heading string matches exactly as the first line, strip it.
    if heading:
        # Case-insensitive exact first-line match
        first_newline = text.find("\n")
        if first_newline > 0:
            first_line = text[:first_newline].strip(" .\t")
            if first_line.lower() == heading.lower():
                text = text[first_newline:].lstrip()

    return text


# ---------------------------------------------------------------------------
# Entity-type ↔ jurisdiction heuristics for D10
# ---------------------------------------------------------------------------

# Jurisdiction-EXCLUSIVE entity-type markers: tokens that are characteristic
# of one country and essentially never appear in legitimate entities from a
# different country. Ambiguous suffixes like "Ltd" or "Limited" (valid in
# IN/GB/SG/CA/HK alike) are intentionally omitted — we only want to flag
# obvious mismatches such as "Pvt. Ltd." paired with a New York address.
_JURISDICTION_EXCLUSIVE: Dict[str, List[str]] = {
    "IN": ["pvt. ltd", "pvt ltd", "private limited", "opc pvt"],
    "DE": ["gmbh", "ag aktiengesellschaft", "aktiengesellschaft"],
    "FR": ["sarl", "sasu", "eurl"],
    "AU": ["pty ltd", "pty. ltd", "pty limited", "pty. limited"],
    "BR": ["ltda"],
    "JP": ["k.k.", "godo kaisha", "kabushiki kaisha"],
    "SG": ["pte ltd", "pte. ltd"],
    "AE": ["pjsc", "fz llc", "fze"],
    "US": [],   # "Inc."/"LLC"/"Corp." are unique-ish but also appear globally
    "GB": [],   # "Plc" is UK-only but rare enough to skip
}


def _detect_entity_jurisdiction_mismatches(
    preamble_text: str,
    context: Dict[str, Any],
) -> List[str]:
    """Flag obvious entity-type ↔ jurisdiction mismatches.

    Strategy: for each party, check whether its entity_type string contains
    a marker EXCLUSIVE to a country other than its declared jurisdiction.
    We deliberately ignore ambiguous suffixes ("Ltd", "Limited") because
    they are valid in many jurisdictions.
    """
    issues: List[str] = []
    for party_key in ("party_1", "party_2"):
        party = context.get(party_key, {}) or {}
        entity = (party.get("entity_type") or "").strip().lower()
        jur = (party.get("jurisdiction") or "").strip().upper()
        if not entity or not jur:
            continue
        country = jur.split("-", 1)[0]
        for other_country, markers in _JURISDICTION_EXCLUSIVE.items():
            if other_country == country or not markers:
                continue
            hit = next((m for m in markers if m in entity), None)
            if hit:
                issues.append(
                    f"{party.get('name') or party_key} is marked "
                    f"'{party.get('entity_type')}' (the '{hit}' marker is "
                    f"characteristic of {other_country}) but the declared "
                    f"jurisdiction is {jur}"
                )
                break
    return issues


class DraftAgent:
    """AI-first drafting agent — builds a RawDraft from a request and playbook."""

    # ------------------------------------------------------------------
    # Tier selection
    # ------------------------------------------------------------------

    @staticmethod
    def _select_tier(
        perspective: str,
        risk_appetite: str,
        clause_category: str | None = None,
        risk_profile: dict[str, str] | None = None,
    ) -> str:
        """Map (perspective, risk_appetite) to a playbook tier name.

        Per-clause override via ``risk_profile`` takes priority when the
        clause_category is present in the profile. Otherwise falls back to
        the global perspective/risk_appetite matrix (which mirrors tiers
        for party_2).
        """
        if risk_profile and clause_category and clause_category in risk_profile:
            override = risk_profile[clause_category].lower()
            return {
                "protective": "preferred",
                "balanced": "acceptable",
                "commercial": "fallback",
                "aggressive": "fallback",
            }.get(override, "acceptable")

        if perspective == "balanced":
            return "acceptable"
        return _TIER_MATRIX.get((perspective, risk_appetite), "acceptable")

    # ------------------------------------------------------------------
    # Context building (not "placeholders" any more — this is the AI's
    # prompt context, which is cleaner than regex substitution)
    # ------------------------------------------------------------------

    @staticmethod
    def _build_context(
        req: DraftRequest,
        playbook: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Build structured context passed into every clause-generation prompt.

        When *playbook* supplies declarative metadata (``roles``,
        ``forbidden_terms``, ``mandatory_directives``, ``clause_mandatory_directives``,
        ``detectors``) those values override the hardcoded defaults below.
        This keeps doc-type-specific rules (e.g. NDA must not use
        "Provider/Customer") inside each playbook instead of leaking into
        the shared prompt template.
        """
        eff_date = (
            req.effective_date.isoformat()
            if req.effective_date
            else date.today().isoformat()
        )

        ctx: Dict[str, Any] = {
            "contract_type": req.contract_type,
            "effective_date": eff_date,
            "term_months": req.term_months,
            "governing_law": req.governing_law,
            "dispute_resolution": req.dispute_resolution,
            "venue": req.venue or req.governing_law,
            "jurisdiction": req.jurisdiction,
            "perspective": req.drafting_perspective,
            "risk_appetite": req.risk_appetite,
            # Parties
            "party_1": {
                "name": req.party_1.name,
                "short_name": req.party_1.name.split()[0],
                "entity_type": req.party_1.entity_type,
                "jurisdiction": req.party_1.jurisdiction,
                "address": req.party_1.address or None,
            },
            "party_2": {
                "name": req.party_2.name,
                "short_name": req.party_2.name.split()[0],
                "entity_type": req.party_2.entity_type,
                "jurisdiction": req.party_2.jurisdiction,
                "address": req.party_2.address or None,
            },
        }

        # Role aliases (for prompt readability)
        if req.contract_type.startswith("nda"):
            if req.contract_type == "nda_unilateral":
                ctx["roles"] = {
                    "disclosing_party": ctx["party_1"]["name"],
                    "receiving_party": ctx["party_2"]["name"],
                }
        elif req.contract_type == "saas":
            ctx["roles"] = {
                "provider": ctx["party_1"]["name"],
                "customer": ctx["party_2"]["name"],
            }
        elif req.contract_type == "msa":
            ctx["roles"] = {
                "service_provider": ctx["party_1"]["name"],
                "client": ctx["party_2"]["name"],
            }
        elif req.contract_type == "employment":
            ctx["roles"] = {
                "company": ctx["party_1"]["name"],
                "employee": ctx["party_2"]["name"],
            }

        # NDA details
        if req.nda_details:
            ctx["nda"] = {
                "purpose": req.nda_details.purpose,
                "survival_years": req.nda_details.confidentiality_survival_years,
                "non_solicitation": req.nda_details.non_solicitation,
                "non_solicitation_months": req.nda_details.non_solicitation_months or 12,
                "marking_requirement": req.nda_details.marking_requirement,
                "ci_categories": (
                    req.nda_details.ci_categories
                    or [
                        "technical data",
                        "trade secrets",
                        "business plans",
                        "financial information",
                    ]
                ),
            }

        # SaaS details
        if req.saas_details:
            saas = req.saas_details
            bf = _normalise_billing_frequency(saas.billing_frequency)
            multiplier = _FREQ_MULTIPLIER[bf]
            ctx["saas"] = {
                "service_description": saas.service_description,
                "pricing_model": saas.pricing_model,
                "price_amount": saas.price_amount,
                "price_formatted": f"${saas.price_amount:,.2f}",
                "billing_frequency": bf,
                "auto_renewal": saas.auto_renewal,
                "uptime_commitment": saas.uptime_commitment or 99.9,
                "authorized_users": saas.authorized_users,
                "liability_cap_months": saas.liability_cap_months,
                "compliance_frameworks": saas.compliance_frameworks or [],
                "data_regions": saas.data_regions or [],
                "support_tiers": saas.support_tiers or {},
                "annual_value": saas.price_amount * multiplier,
                "annual_value_formatted": f"${saas.price_amount * multiplier:,.2f}",
            }

        # Employment details (fields are optional on DraftRequest)
        if req.contract_type == "employment":
            ctx["employment"] = {
                "title": getattr(req, "employee_title", None),
                "base_salary": getattr(req, "base_salary", None),
                "reporting_manager": getattr(req, "reporting_manager", None),
                "work_location": getattr(req, "work_location", None),
            }

        # ------------------------------------------------------------------
        # Playbook-driven metadata (doc-type-specific rules).
        # When the playbook declares any of these keys, they override the
        # hardcoded defaults above. Absence = current behavior unchanged
        # (backward-compatible for SaaS / MSA / Employment playbooks that
        # have not yet been migrated).
        # ------------------------------------------------------------------
        # Track provenance of ``ctx["roles"]``. The legacy hardcoded switch
        # above stores PARTY NAMES as the values (e.g. saas → {"provider":
        # "Acme Corp."}), whereas the new playbook convention stores ROLE
        # LABELS (e.g. nda_mutual → {"disclosing_party": "Disclosing
        # Party"}). Downstream code needs to know which is which so the
        # "Use X and Y" instruction uses role labels, not party names.
        ctx["_roles_from_playbook"] = False
        if playbook:
            pb_roles = playbook.get("roles")
            if pb_roles:
                # Playbook roles WIN over the hardcoded switch above. Keys
                # are snake_case labels (e.g. "disclosing_party"), values
                # are the human-readable role term shown to the AI.
                ctx["roles"] = dict(pb_roles)
                ctx["_roles_from_playbook"] = True
            ctx["forbidden_terms"] = list(playbook.get("forbidden_terms", []))
            ctx["mandatory_directives"] = list(
                playbook.get("mandatory_directives", [])
            )
            ctx["clause_mandatory_directives"] = dict(
                playbook.get("clause_mandatory_directives", {})
            )
            ctx["detectors"] = list(playbook.get("detectors", []))
        else:
            ctx.setdefault("forbidden_terms", [])
            ctx.setdefault("mandatory_directives", [])
            ctx.setdefault("clause_mandatory_directives", {})
            ctx.setdefault("detectors", [])

        return ctx

    # ------------------------------------------------------------------
    # Backwards-compatible placeholder builder (used by fallback template
    # path when AI is unavailable)
    # ------------------------------------------------------------------

    @staticmethod
    def _build_placeholders(req: DraftRequest) -> Dict[str, str]:
        """Flat key-value dict used only by the fallback template filler."""
        eff_date = (
            req.effective_date.isoformat()
            if req.effective_date
            else date.today().isoformat()
        )

        p: Dict[str, str] = {
            "party_1_name": req.party_1.name,
            "party_1_short_name": req.party_1.name.split()[0],
            "party_1_entity_type": req.party_1.entity_type,
            "party_1_jurisdiction": req.party_1.jurisdiction,
            "party_1_address": req.party_1.address or "",
            "party_2_name": req.party_2.name,
            "party_2_short_name": req.party_2.name.split()[0],
            "party_2_entity_type": req.party_2.entity_type,
            "party_2_jurisdiction": req.party_2.jurisdiction,
            "party_2_address": req.party_2.address or "",
            "effective_date": eff_date,
            "term_months": str(req.term_months),
            "governing_law": req.governing_law,
            "dispute_resolution": req.dispute_resolution,
            "venue": req.venue or req.governing_law,
        }

        # Role aliases
        p["disclosing_party_name"] = p["party_1_name"]
        p["disclosing_party_short_name"] = p["party_1_short_name"]
        p["receiving_party_name"] = p["party_2_name"]
        p["receiving_party_short_name"] = p["party_2_short_name"]
        p["provider_name"] = p["party_1_name"]
        p["provider_short_name"] = p["party_1_short_name"]
        p["provider_entity_type"] = p["party_1_entity_type"]
        p["provider_jurisdiction"] = p["party_1_jurisdiction"]
        p["provider_address"] = p["party_1_address"]
        p["customer_name"] = p["party_2_name"]
        p["customer_short_name"] = p["party_2_short_name"]
        p["customer_entity_type"] = p["party_2_entity_type"]
        p["customer_jurisdiction"] = p["party_2_jurisdiction"]
        p["customer_address"] = p["party_2_address"]
        p["service_provider_name"] = p["party_1_name"]
        p["client_name"] = p["party_2_name"]
        p["company_name"] = p["party_1_name"]
        p["employee_name"] = p["party_2_name"]

        p["confidentiality_survival_years"] = "3"

        if req.contract_type == "employment":
            p["employee_title"] = getattr(req, "employee_title", None) or ""
            p["base_salary"] = getattr(req, "base_salary", None) or ""
            p["reporting_manager"] = getattr(req, "reporting_manager", None) or ""
            p["work_location"] = getattr(req, "work_location", None) or ""

        if req.nda_details:
            nda = req.nda_details
            p["purpose"] = nda.purpose
            p["confidentiality_survival_years"] = str(nda.confidentiality_survival_years)
            p["non_solicitation_months"] = str(nda.non_solicitation_months or 12)
            p["ci_categories_clause"] = (
                ", ".join(nda.ci_categories)
                if nda.ci_categories
                else "technical data, trade secrets, business plans, financial information"
            )

        if req.saas_details:
            saas = req.saas_details
            bf = _normalise_billing_frequency(saas.billing_frequency)
            multiplier = _FREQ_MULTIPLIER[bf]
            p["service_description"] = saas.service_description
            p["pricing_model"] = saas.pricing_model
            p["price_amount"] = f"{saas.price_amount:,.2f}"
            p["billing_frequency"] = bf
            p["uptime_commitment"] = (
                f"{saas.uptime_commitment}%" if saas.uptime_commitment else "99.9%"
            )
            p["authorized_users"] = str(saas.authorized_users or "unlimited")
            p["auto_renewal_text"] = (
                "automatically renew for successive periods of equal length"
                if saas.auto_renewal
                else "expire at the end of the Initial Term unless renewed in writing"
            )
            p["annual_value"] = f"{saas.price_amount * multiplier:,.2f}"

        return p

    # ------------------------------------------------------------------
    # Template rendering (fallback only)
    # ------------------------------------------------------------------

    @staticmethod
    def _fill_placeholders(template: str, placeholders: Dict[str, str]) -> str:
        """Replace ``{{key}}`` tokens with values from *placeholders*."""

        def _replacer(match: re.Match) -> str:
            key = match.group(1).strip()
            value = placeholders.get(key, "")
            return value if value else ""

        return re.sub(r"\{\{(\s*\w+\s*)\}\}", _replacer, template)

    # ------------------------------------------------------------------
    # Conditional inclusion
    # ------------------------------------------------------------------

    @staticmethod
    def _should_include(clause: Dict[str, Any], req: DraftRequest) -> bool:
        if clause.get("is_required", True):
            return True

        condition = clause.get("conditional_on")
        if not condition:
            return True

        match = re.match(r"([\w.]+)\s*==\s*(.+)", condition.strip())
        if not match:
            return True

        path_str, expected_raw = match.group(1), match.group(2).strip()

        obj: Any = req
        for part in path_str.split("."):
            obj = getattr(obj, part, None)
            if obj is None:
                return False

        if expected_raw.lower() == "true":
            return bool(obj) is True
        if expected_raw.lower() == "false":
            return bool(obj) is False

        return str(obj) == expected_raw

    # ------------------------------------------------------------------
    # Clause prompt construction
    # ------------------------------------------------------------------

    @staticmethod
    def _build_clause_prompt(
        clause: Dict[str, Any],
        tier_name: str,
        context: Dict[str, Any],
        seed_text: str,
        tier_guidance: str,
    ) -> str:
        """Build the per-clause prompt for Vertex AI."""
        clause_type = clause.get("clause_type", "clause")
        heading = clause.get("section_heading", "")
        drafting_notes = clause.get("drafting_notes", "")
        required_terms = clause.get("required_defined_terms", [])
        cross_refs = clause.get("cross_references", [])

        # Resolve jurisdiction variant (specific first, then country prefix)
        jur = context.get("jurisdiction", "")
        jur_key = jur.split("-")[0] if jur else ""
        jur_variants = clause.get("jurisdiction_variants", {})
        jur_variant = jur_variants.get(jur) or jur_variants.get(jur_key) or ""

        # Map tier → legal posture directive
        tier_directive = {
            "preferred": (
                "Draft this clause in its MOST PROTECTIVE form for the drafting "
                "party. Use firm, assertive language. Narrow exceptions. Short "
                "cure periods. Broad carve-outs. This is the 'open strong' tier."
            ),
            "acceptable": (
                "Draft this clause as a BALANCED, market-standard provision. "
                "Language should be fair to both sides and match what a "
                "reasonable senior associate would produce for an arm's-length "
                "deal. This is the settlement tier."
            ),
            "fallback": (
                "Draft this clause in its COMMERCIAL / COUNTERPARTY-FRIENDLY form. "
                "Softer language ('commercially reasonable efforts'), longer "
                "cure periods, broader exceptions, mutual obligations where "
                "possible. This is the floor — the minimum you'd accept."
            ),
        }.get(tier_name, "Balanced market-standard language.")

        # Perspective directive
        perspective = context.get("perspective", "balanced")
        if perspective == "party_1":
            perspective_note = "The drafting party is Party 1 (the primary party in the preamble)."
        elif perspective == "party_2":
            perspective_note = (
                "The drafting party is Party 2 — the counterparty. Tilt protections "
                "and obligations appropriately so Party 2 has the stronger position."
            )
        else:
            perspective_note = "Draft neutrally, with no party favored."

        # Compact context block
        parties_block = (
            f"- Party 1: {context['party_1']['name']} ({context['party_1']['entity_type']}, "
            f"{context['party_1']['jurisdiction']})\n"
            f"- Party 2: {context['party_2']['name']} ({context['party_2']['entity_type']}, "
            f"{context['party_2']['jurisdiction']})"
        )
        roles = context.get("roles", {})
        roles_block = (
            "\n".join(f"- {k.replace('_', ' ').title()}: {v}" for k, v in roles.items())
            if roles
            else ""
        )

        deal_block = (
            f"- Effective date: {context.get('effective_date', 'TBD')}\n"
            f"- Term: {context.get('term_months', 12)} months\n"
            f"- Governing law: {context.get('governing_law', '(unspecified)')}\n"
            f"- Dispute resolution: {context.get('dispute_resolution', 'arbitration')}\n"
            f"- Venue: {context.get('venue', '(unspecified)')}"
        )

        nda_block = ""
        if "nda" in context:
            n = context["nda"]
            ci_cat_line = ", ".join(n["ci_categories"])
            nda_block = (
                "\nNDA-specific context:\n"
                f"- Purpose of disclosure: {n['purpose']}\n"
                f"- Confidentiality survival: {n['survival_years']} years\n"
                f"- Non-solicitation included: {n['non_solicitation']} "
                f"({n['non_solicitation_months']} months)\n"
                f"- Marking requirement: {n['marking_requirement']}\n"
                f"- Categories of confidential information: {ci_cat_line}"
            )

        employment_block = ""
        employment_clause_directive = ""
        if "employment" in context:
            e = context["employment"]
            employment_block = (
                "\nEmployment-specific context:\n"
                f"- Position / Title: {e.get('title') or '(unspecified)'}\n"
                f"- Base salary: {e.get('base_salary') or '(unspecified)'}\n"
                f"- Reporting manager: {e.get('reporting_manager') or '(unspecified)'}\n"
                f"- Work location: {e.get('work_location') or 'Hybrid'}"
            )
            emp_directives: list[str] = []
            if clause_type in ("position_duties", "preamble") and e.get("title"):
                emp_directives.append(
                    f"MANDATORY: Employee's position / job title is exactly "
                    f"'{e['title']}' — use this verbatim, do not paraphrase."
                )
            if clause_type == "compensation" and e.get("base_salary"):
                emp_directives.append(
                    f"MANDATORY: Base salary must be exactly {e['base_salary']} — "
                    f"do not substitute a placeholder or different amount."
                )
            if clause_type in ("position_duties", "work_hours") and e.get("reporting_manager"):
                emp_directives.append(
                    f"MANDATORY: Employee reports to {e['reporting_manager']}."
                )
            if clause_type == "work_hours" and e.get("work_location"):
                emp_directives.append(
                    f"MANDATORY: Work location arrangement is "
                    f"'{e['work_location']}' — reflect this exactly."
                )
            if emp_directives:
                employment_clause_directive = (
                    "\n\nClause-specific mandates (override tier defaults):\n- "
                    + "\n- ".join(emp_directives)
                )

        # Universal MANDATORY directives — apply to ALL contract types.
        # These force the AI to honor user-selected jurisdiction, governing
        # law, dispute-resolution method, and venue in the clauses where
        # they appear. Without these, the AI echoes Delaware/litigation
        # defaults baked into SaaS seed templates regardless of user input.
        universal_clause_directive = ""
        universal_directives: List[str] = []
        gl_value = context.get("governing_law", "") or ""
        dr_value = context.get("dispute_resolution", "") or ""
        venue_value = context.get("venue", "") or ""
        jurisdiction_value = context.get("jurisdiction", "") or ""

        if clause_type in ("dispute_resolution", "governing_law"):
            if gl_value:
                universal_directives.append(
                    f"MANDATORY: The governing law of this Agreement is "
                    f"exactly '{gl_value}'. Use this phrase verbatim. Do NOT "
                    f"substitute Delaware, California, New York, or any other "
                    f"jurisdiction. The clause must read that the Agreement is "
                    f"governed by the laws of {gl_value}."
                )
            if dr_value:
                # Normalise so the directive reads cleanly
                method = dr_value.lower().strip()
                method_sentence = {
                    "arbitration": (
                        "Disputes MUST be resolved by binding arbitration. "
                        "Do NOT use litigation or court proceedings as the "
                        "primary mechanism. Equitable / injunctive relief may "
                        "still be sought in a court but the substantive "
                        "dispute goes to arbitration."
                    ),
                    "litigation": (
                        "Disputes MUST be resolved by litigation in a court "
                        "of competent jurisdiction. Do NOT default to "
                        "arbitration."
                    ),
                    "mediation": (
                        "Disputes MUST first be escalated to mediation, "
                        "followed by the agreed formal mechanism if unresolved."
                    ),
                }.get(method, (
                    f"Disputes MUST be resolved by {method}. Do NOT substitute "
                    "a different mechanism."
                ))
                universal_directives.append(f"MANDATORY: {method_sentence}")
            if venue_value:
                universal_directives.append(
                    f"MANDATORY: The venue / seat MUST be '{venue_value}'. "
                    f"Do NOT substitute Wilmington, Delaware or any other "
                    f"default."
                )

        # DPA-specific jurisdictional directive (belt-and-suspenders alongside
        # the coherence pass D5).
        if clause_type == "dpa":
            j = jurisdiction_value.upper()
            j_prefix = j.split("-", 1)[0]
            if j_prefix == "IN":
                universal_directives.append(
                    "MANDATORY: This is an India-to-India data processing "
                    "relationship. Write this DPA under the Digital Personal "
                    "Data Protection Act 2023 (DPDP Act). Use DPDP "
                    "terminology: 'Data Fiduciary' = Customer, 'Data "
                    "Processor' = Provider, 'Data Principal' = individual. "
                    "Do NOT reference GDPR, Regulation (EU) 2016/679, the "
                    "EEA, EU Standard Contractual Clauses, or any other "
                    "European instrument — those are the wrong framework for "
                    "this deal."
                )
            elif j_prefix == "EU" or j_prefix in {"DE", "FR", "NL", "IE", "ES", "IT"}:
                universal_directives.append(
                    "MANDATORY: Write this DPA under the EU GDPR (Regulation "
                    "(EU) 2016/679). Use GDPR roles: 'Controller' = "
                    "Customer, 'Processor' = Provider. Reference Article 28 "
                    "requirements. International transfers outside the EEA "
                    "must use the 2021 EU Standard Contractual Clauses."
                )
            elif j == "US-CA":
                universal_directives.append(
                    "MANDATORY: This DPA is for a California deal. Write it "
                    "under the CCPA / CPRA. Use CCPA roles: Customer is the "
                    "'Business', Provider is the 'Service Provider'. Do NOT "
                    "reference GDPR, EEA, or EU-specific instruments."
                )
            elif j_prefix == "GB":
                universal_directives.append(
                    "MANDATORY: Write this DPA under the UK GDPR and Data "
                    "Protection Act 2018. International transfers must use the "
                    "UK International Data Transfer Agreement (IDTA) or the "
                    "UK Addendum to the 2021 EU SCCs."
                )
            elif j_prefix == "SG":
                universal_directives.append(
                    "MANDATORY: Write this DPA under the Singapore Personal "
                    "Data Protection Act (PDPA)."
                )
            elif j_prefix == "AU":
                universal_directives.append(
                    "MANDATORY: Write this DPA under the Australian Privacy "
                    "Act 1988 and the Australian Privacy Principles."
                )
            elif j == "BR":
                universal_directives.append(
                    "MANDATORY: Write this DPA under the Brazilian LGPD "
                    "(Lei Geral de Proteção de Dados)."
                )

        # Playbook-level directives (doc-type-specific: e.g. "This is an NDA,
        # never use 'Provider/Customer'"). Always injected before the output
        # instructions so they compete on equal footing with seed text.
        playbook_mandates: List[str] = list(context.get("mandatory_directives", []))

        # Per-clause mandates from the playbook, keyed by clause_type.
        clause_mandates_map = context.get("clause_mandatory_directives", {}) or {}
        per_clause_mandates: List[str] = list(
            clause_mandates_map.get(clause_type, [])
        )

        if universal_directives or playbook_mandates or per_clause_mandates:
            all_mandates = [
                *playbook_mandates,       # doc-type scope (e.g. NDA-wide)
                *per_clause_mandates,     # clause-scope override
                *universal_directives,    # user-picked knobs (GL, dispute, DPA)
            ]
            universal_clause_directive = (
                "\n\nMandatory directives (override any conflicting seed "
                "language):\n- "
                + "\n- ".join(all_mandates)
            )

        saas_block = ""
        saas_clause_directive = ""
        if "saas" in context:
            s = context["saas"]
            frameworks_list = s["compliance_frameworks"]
            frameworks = ", ".join(frameworks_list) or "(none specified)"
            regions_list = s["data_regions"]
            regions = ", ".join(regions_list) or "(not specified)"
            cap_months = s["liability_cap_months"] or "(follow tier standard)"
            support_tiers = s.get("support_tiers") or {}
            support_line = (
                ", ".join(f"{k}: {v}" for k, v in support_tiers.items())
                if support_tiers
                else "(use tier defaults)"
            )
            saas_block = (
                "\nSaaS-specific context:\n"
                f"- Service: {s['service_description']}\n"
                f"- Pricing: {s['price_formatted']} per {s['billing_frequency']} billing period, "
                f"{s['pricing_model']} pricing\n"
                f"- Estimated annual value: {s['annual_value_formatted']}\n"
                f"- Auto-renewal: {s['auto_renewal']}\n"
                f"- Uptime commitment: {s['uptime_commitment']}%\n"
                f"- Authorized users: {s['authorized_users'] or '(unlimited)'}\n"
                f"- Requested liability cap: {cap_months} months of fees\n"
                f"- Compliance frameworks to reference: {frameworks}\n"
                f"- Data processing regions: {regions}\n"
                f"- Customer-specified support tiers: {support_line}"
            )

            # Per-clause directives that force the AI to HONOR the user's SaaS
            # knobs. Without these, generic prompts often ignore the specific
            # numbers/frameworks and fall back to playbook defaults.
            directives: list[str] = []
            if clause_type == "limitation_of_liability" and s.get("liability_cap_months"):
                cap_m = s["liability_cap_months"]
                window = "12 months" if cap_m >= 12 else f"{cap_m} months"
                directives.append(
                    f"MANDATORY: The aggregate liability cap for this clause MUST be "
                    f"exactly {cap_m} months of fees paid by Customer "
                    f"in the {window} "
                    f"preceding the claim. Do NOT substitute a different cap. If the tier "
                    f"would normally use a different cap, override it with "
                    f"{cap_m} months of fees."
                )
            if clause_type in ("data_security", "dpa") and frameworks_list:
                directives.append(
                    f"MANDATORY: This clause MUST reference the following compliance "
                    f"frameworks explicitly by name: {', '.join(frameworks_list)}. "
                    f"Provider's security / data-protection obligations must be "
                    f"framed as aligning with these specific frameworks."
                )
            if clause_type in ("data_security", "dpa", "data_ownership") and regions_list:
                directives.append(
                    f"MANDATORY: Reference the following data processing regions "
                    f"explicitly where relevant: {', '.join(regions_list)}. "
                    f"Data shall be processed and stored in these regions."
                )
            if clause_type == "grant_of_license" and s.get("authorized_users"):
                directives.append(
                    f"MANDATORY: The license grant must reference the specific "
                    f"authorized-user cap of {s['authorized_users']} users."
                )
            if clause_type == "sla" and support_tiers:
                tiers_text = "; ".join(f"{k} — {v}" for k, v in support_tiers.items())
                directives.append(
                    f"MANDATORY: The SLA support section must reflect the "
                    f"Customer-specified support tiers exactly: {tiers_text}. "
                    f"Structure the P1/P2/P3/P4 response matrix to match these tier "
                    f"commitments."
                )
            if directives:
                saas_clause_directive = (
                    "\n\nClause-specific mandates (override tier defaults with these):\n- "
                    + "\n- ".join(directives)
                )

        required_terms_block = (
            f"\nRequired defined terms this clause MUST use: {', '.join(required_terms)}"
            if required_terms
            else ""
        )

        jur_block = f"\nJurisdiction note ({jur}): {jur_variant}" if jur_variant else ""

        # Cross-references are handled by NAME, not by section number. This
        # avoids a class of bugs where the AI writes a bare cross-ref token at
        # the start of a clause body ("{{REF:fees}} and is expressly limited...")
        # which then resolves into "Section 6 and is expressly limited..." —
        # a syntactically-valid but content-less orphan opening.
        cross_ref_block = ""
        if cross_refs:
            cross_ref_text = ", ".join(cross_refs)
            cross_ref_block = (
                f"\nThis clause may reference these related clauses when needed: "
                f"{cross_ref_text}. Refer to them by NAME, not by number. Write e.g. "
                f"'the Confidentiality section', 'Exhibit A (Service Level Agreement)', "
                f"'the Indemnification Section', 'this Agreement'. Do NOT write "
                f"'Section 5' or 'Section X'. Do NOT use any curly-brace tokens. "
                f"Cross-references should appear INSIDE the clause body as part of "
                f"a full sentence, never as the opening."
            )

        seed_block = ""
        if seed_text:
            seed_block = (
                "\n\nReference language from the firm's playbook (use as inspiration, "
                "NOT as a rigid template — you may restructure, tighten, or rewrite "
                "this freely):\n---\n"
                f"{sanitize_for_prompt(seed_text, max_length=3000)}\n---"
            )

        drafting_notes_block = (
            f"\nPlaybook drafting notes: {drafting_notes}" if drafting_notes else ""
        )

        # Collect MANDATORY overrides (playbook + user-selected knobs) and
        # put them right before the output instructions where the model pays
        # the most attention.
        # Order: playbook doc-type mandates → user-selected knobs (GL,
        # dispute, DPA) → SaaS/Employment knobs. Playbook comes first because
        # doc-type identity is the most fundamental constraint — if an NDA
        # accidentally inherits SaaS seed text, the anti-leak mandate must
        # win.
        mandatory_overrides = ""
        for block in (
            universal_clause_directive,
            saas_clause_directive,
            employment_clause_directive,
        ):
            if block and ("MANDATORY" in block or "Mandatory directives" in block):
                mandatory_overrides += block
        mandatory_overrides_section = (
            f"\n\n=== CRITICAL OVERRIDES (HIGHEST PRIORITY) ==="
            f"{mandatory_overrides}\n"
            f"These overrides take ABSOLUTE priority over any conflicting guidance in the "
            f"reference seed, tier posture, or playbook notes above. If the seed text "
            f"uses a different value (e.g. a different cap, framework list, or role "
            f"label), you MUST override it to honor these directives.\n"
            f"==============================================================\n"
        ) if mandatory_overrides else ""

        # Role labels used in the output instructions. Only safe to iterate
        # ``roles.values()`` when the playbook itself supplied them — the
        # legacy hardcoded switch in ``_build_context`` stored party NAMES
        # as values (e.g. {"provider": "Acme Corp."}). For those cases we
        # keep the historical Provider/Customer wording to preserve SaaS/MSA/
        # Employment behavior until those playbooks are migrated.
        if roles and context.get("_roles_from_playbook"):
            role_labels_for_prompt = " and ".join(
                f"'{v}'" for v in roles.values()
            )
        else:
            role_labels_for_prompt = "'Provider' and 'Customer'"

        # Forbidden-term instruction (playbook-driven). Only emitted when
        # the playbook declares forbidden terms, so SaaS/MSA/Employment are
        # untouched.
        forbidden_terms_list = context.get("forbidden_terms", []) or []
        forbidden_block = ""
        if forbidden_terms_list:
            forbidden_block = (
                "\n"
                "F. FORBIDDEN TERMS (this contract type does not define them):\n"
                f"   - Do NOT use any of the following terms anywhere in the "
                f"clause body: {', '.join(repr(t) for t in forbidden_terms_list)}.\n"
                "   - If the reference seed uses one of these terms, REPLACE it "
                "with the correct role label from the roles block above, or "
                "REMOVE the sentence if no correct substitution exists.\n"
            )

        prompt = (
            f"You are a senior contract attorney drafting a single clause of a "
            f"{context['contract_type'].replace('_', ' ').upper()}.\n\n"
            f"Clause to draft: **{heading}** (type: {clause_type})\n\n"
            f"Tier posture: {tier_name.upper()}\n"
            f"{tier_directive}\n\n"
            f"Perspective: {perspective_note}\n\n"
            "Deal context:\n"
            f"{parties_block}\n"
            f"{roles_block}\n"
            f"{deal_block}"
            f"{nda_block}"
            f"{saas_block}"
            f"{employment_block}"
            f"{required_terms_block}"
            f"{jur_block}"
            f"{cross_ref_block}"
            f"{drafting_notes_block}"
            f"{seed_block}"
            f"{mandatory_overrides_section}"
            "\nOUTPUT INSTRUCTIONS (critical — read carefully):\n"
            "\n"
            "A. WHAT TO RETURN:\n"
            "   - Return ONLY the clause body text. Start directly with the first "
            "word of the operative text. No meta-commentary.\n"
            "   - Do NOT repeat the heading or add a section number. The renderer "
            f"adds '{heading}' as the heading automatically.\n"
            "   - Do NOT start with a numbered or uppercase run-in heading like "
            f"'{heading.upper()}.' or '12. LIMITATION OF LIABILITY.'.\n"
            "   - Do NOT start with 'Section N' or 'Section (X)' — orphan "
            "cross-references as openings are invalid.\n"
            "   - No markdown. No ``` fences. No preamble like 'Here is...'.\n"
            "\n"
            "B. DEFINED-TERM DISCIPLINE (strict):\n"
            f"   - Use {role_labels_for_prompt} (the role labels shown in the "
            "roles block above) throughout the clause body. These are the "
            "ONLY defined role terms for this contract — use no others.\n"
            "   - Do NOT use the parties' literal company names in the body of "
            "ordinary clauses. The party names belong ONLY in the Preamble "
            "and Signature Blocks.\n"
            "   - Wrap first-use defined terms in double quotes (e.g. "
            '"Confidential Information"), then use them unquoted afterwards. '
            "Do NOT nest quotes inside already-quoted defined terms (never "
            'write `"Receiving "Party""` — write `"Receiving Party"`).\n'
            "\n"
            "C. SUB-NUMBERING DISCIPLINE:\n"
            "   - Do NOT prefix sub-paragraphs with numeric labels like '12.1', "
            "'12.2', '14.1'. Those numbers belong to the parent section and the "
            "renderer handles them.\n"
            "   - Use '(a)', '(b)', '(c)' for enumerated sub-parts within a clause. "
            "For deeper nesting use '(i)', '(ii)', '(iii)'.\n"
            "\n"
            "D. CROSS-REFERENCES:\n"
            "   - When referring to another clause in this Agreement, use its "
            "NAME, not a number. Examples of correct references: "
            "'the Confidentiality Section', 'the Data Security obligations', "
            "'Exhibit A (Service Level Agreement)', 'this Agreement', "
            "'the Order Form attached as Exhibit C'.\n"
            "   - Cross-references must appear INSIDE a full sentence, never as "
            "the clause opening.\n"
            "\n"
            "E. SUBSTANCE:\n"
            "   - Length: 2–6 paragraphs as appropriate. Substantive sections "
            "(liability, indemnification, IP, data security) should be thorough "
            "and complete — no stubs. Boilerplate may be shorter but at least one "
            "full operative sentence.\n"
            "   - All dates, names, amounts from the deal context must be used "
            "verbatim — never substitute '[Date]', 'XXX', '[Amount]', etc.\n"
            "   - Every sentence must be grammatically complete. Close every "
            "opened parenthesis and quotation mark. Never end a clause "
            "mid-phrase.\n"
            "   - If a CRITICAL OVERRIDES block appears above, "
            "those values are non-negotiable — use them verbatim.\n"
            f"{forbidden_block}"
        )

        return prompt

    # ------------------------------------------------------------------
    # Per-clause AI generation
    # ------------------------------------------------------------------

    async def _ai_generate_clause(
        self,
        clause: Dict[str, Any],
        tier_name: str,
        context: Dict[str, Any],
        semaphore: asyncio.Semaphore,
    ) -> Tuple[str, int, bool]:
        """Generate a single clause via Vertex AI. Returns (text, tokens, ai_used)."""
        # Get tier-specific seed + guidance from the playbook (still useful as
        # a knowledge anchor for the AI)
        tier_data = clause.get(tier_name, clause.get("acceptable", {}))
        seed_text = tier_data.get("template_text", "")
        tier_guidance = tier_data.get("guidance", "")

        # Fallback immediately if no Vertex AI
        try:
            from app.core.vertex_client import get_generative_model, is_available
        except ImportError:
            logger.warning("Vertex client unavailable, falling back to seed text")
            return seed_text, 0, False

        if not is_available():
            logger.warning("Vertex AI not configured, falling back to seed text")
            return seed_text, 0, False

        prompt = self._build_clause_prompt(
            clause, tier_name, context, seed_text, tier_guidance
        )

        # Strip markdown fences from AI output
        try:
            from app.services.gemini_analyzer import _strip_markdown_fences
        except ImportError:
            def _strip_markdown_fences(t: str) -> str:
                return t.strip()

        async def _call_vertex(prompt_text: str, attempt: int) -> Tuple[str, int]:
            """Single AI call — returns (text, tokens). Raises on failure."""
            from google.genai.types import GenerateContentConfig
            model = get_generative_model(settings.GEMINI_MODEL)
            response = await asyncio.wait_for(
                model.generate_content_async(
                    [{"role": "user", "parts": [{"text": prompt_text}]}],
                    generation_config=GenerateContentConfig(
                        temperature=0.3 + (0.1 * attempt),  # nudge variety on retry
                        max_output_tokens=3500,
                    ),
                ),
                timeout=_PER_CLAUSE_TIMEOUT_S,
            )
            raw = getattr(response, "text", None) or ""
            cleaned = _strip_markdown_fences(raw).strip()
            cleaned = _strip_leading_heading(cleaned, clause.get("section_heading", ""))
            tokens = 0
            usage = getattr(response, "usage_metadata", None)
            if usage is not None:
                tokens = getattr(usage, "total_token_count", 0) or 0
            return cleaned, tokens

        # Minimum meaningful clause length — short boilerplate sections like
        # signature blocks can be brief, but anything under this is almost
        # always a bad/truncated AI output.
        MIN_CLAUSE_CHARS = 80

        async with semaphore:
            total_tokens = 0
            for attempt in range(2):  # initial call + 1 retry
                try:
                    text, tokens = await _call_vertex(prompt, attempt)
                    total_tokens += tokens

                    if not text:
                        logger.warning(
                            "Attempt %d: AI returned empty text for clause %s",
                            attempt + 1,
                            clause.get("clause_type"),
                        )
                        continue

                    if len(text) < MIN_CLAUSE_CHARS:
                        logger.warning(
                            "Attempt %d: AI output too short (%d chars) for clause %s: %r",
                            attempt + 1,
                            len(text),
                            clause.get("clause_type"),
                            text[:100],
                        )
                        # Retry with adjusted prompt asking for more detail
                        prompt = prompt + (
                            "\n\nIMPORTANT: Your previous response was too brief. "
                            "Provide the complete clause body text (2-6 paragraphs). "
                            "Do not respond with just a cross-reference or fragment."
                        )
                        continue

                    return text, total_tokens, True

                except asyncio.TimeoutError:
                    logger.warning(
                        "Clause %s timed out on attempt %d after %.0fs",
                        clause.get("clause_type"),
                        attempt + 1,
                        _PER_CLAUSE_TIMEOUT_S,
                    )
                    # Don't retry on timeout — fall through to seed
                    break
                except Exception as e:
                    logger.warning(
                        "Clause %s AI call %d failed (%s)",
                        clause.get("clause_type"),
                        attempt + 1,
                        type(e).__name__,
                    )
                    # Only retry on transient errors, not validation/etc.
                    continue

            logger.warning(
                "Clause %s falling back to seed text after retries",
                clause.get("clause_type"),
            )
            return seed_text, total_tokens, False

    # ------------------------------------------------------------------
    # Cross-reference resolution (post-process)
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_cross_refs(sections: List[DraftSection]) -> List[DraftSection]:
        """Replace legacy ``{{REF:clause_type}}`` tokens with named references.

        We no longer instruct the AI to produce these tokens — clauses now
        use named references ('the Confidentiality Section') directly. This
        resolver remains as a safety net in case a playbook seed or an older
        cached output still contains tokens. Resolves to the clause's
        section_heading rather than a bare section number, which reads more
        naturally if a stray token leaks through.
        """
        clause_type_to_heading = {
            s.clause_type: s.heading for s in sections
        }

        def _replacer(match: re.Match) -> str:
            key = match.group(1).strip()
            heading = clause_type_to_heading.get(key)
            if heading:
                return f"the {heading} section"
            pretty = key.replace("_", " ").title()
            return f"the {pretty} section"

        pattern = re.compile(r"\{\{\s*REF\s*:\s*([\w_]+)\s*\}\}")
        updated: List[DraftSection] = []
        for s in sections:
            new_content = pattern.sub(_replacer, s.content)
            if new_content != s.content:
                updated.append(DraftSection(
                    number=s.number,
                    heading=s.heading,
                    content=new_content,
                    clause_type=s.clause_type,
                    tier_used=s.tier_used,
                    notes=s.notes,
                ))
            else:
                updated.append(s)
        return updated

    # ------------------------------------------------------------------
    # Coherence pass (post-generation defect detection + AI repair)
    # ------------------------------------------------------------------

    @staticmethod
    def _detect_defects(
        section: DraftSection,
        context: Dict[str, Any],
    ) -> List[str]:
        """Return a list of human-readable defects in this clause body.

        Empty list means the section is clean. Each string describes a
        specific issue the repair prompt should address.
        """
        text = section.content or ""
        defects: List[str] = []

        # D1: Orphan "Section N" opening (the {{REF:}} resolution artifact).
        # E.g., "Section 22 and is expressly limited..."
        orphan_opener = re.match(
            r"^\s*Section\s*(?:\d+(?:\.\d+)?|\([^)]+\)|[IVX]+)[\s,.]",
            text,
        )
        if orphan_opener:
            defects.append(
                "Clause opens with a bare section reference "
                f"('{text[:60].strip()}...'). Rewrite to start with a full "
                "operative sentence. If the clause needs to refer to another "
                "section, do it by NAME inside a proper sentence."
            )

        # D2: Literal party names instead of role terms.
        # Only flag when MORE than 2 occurrences — a couple in Preamble / SIG
        # are legitimate.
        p1_name = context.get("party_1", {}).get("name", "")
        p2_name = context.get("party_2", {}).get("name", "")
        p1_short = context.get("party_1", {}).get("short_name", "")
        p2_short = context.get("party_2", {}).get("short_name", "")

        # Skip the preamble and signature blocks — names are correct there.
        if section.clause_type not in {"preamble", "signature_blocks", "recitals"}:
            literal_hits = 0
            for name in (p1_name, p2_name, p1_short, p2_short):
                if name and len(name) > 2:
                    literal_hits += len(re.findall(rf"\b{re.escape(name)}\b", text))
            if literal_hits >= 2:
                defects.append(
                    f"Clause uses the parties' literal names "
                    f"('{p1_short}', '{p2_short}') {literal_hits} times in the "
                    "body. Replace with the defined role terms (Provider / "
                    "Customer, or Disclosing Party / Receiving Party, as "
                    "appropriate). Literal names belong only in the Preamble "
                    "and Signature Blocks."
                )

        # D3: Numeric sub-labels that don't match the clause's own section
        # number. E.g., body says "11.1" but clause is actually §12.
        section_num = section.number
        sub_label_match = re.search(r"(?<!\d)(\d{1,2})\.\d+\s+[A-Z]", text)
        if sub_label_match:
            embedded_num = sub_label_match.group(1)
            if embedded_num != section_num:
                defects.append(
                    f"Clause body uses numeric sub-labels ('{embedded_num}.1', "
                    f"'{embedded_num}.2', ...) but this is actually section "
                    f"{section_num}. Replace the numeric sub-labels with "
                    "'(a)', '(b)', '(c)' sub-paragraphs, OR simply drop the "
                    "sub-numbers and let the sub-paragraphs flow as prose."
                )

        # D4: Stub clause. Some sections are expected to be substantive (liability,
        # indemnification, IP, data security, data ownership, SLA) and should
        # be at least 400 chars. Signature/boilerplate OK smaller.
        SUBSTANTIVE_TYPES = {
            "limitation_of_liability",
            "indemnification",
            "intellectual_property",
            "data_security",
            "data_ownership",
            "confidentiality",
            "sla",
            "dpa",
            "representations_warranties",
            "fees_and_payment",
            "term_and_termination",
            "grant_of_license",
            "scope_of_services",
        }
        if section.clause_type in SUBSTANTIVE_TYPES and len(text) < 400:
            defects.append(
                f"Clause is too short for a substantive '{section.clause_type}' "
                f"section ({len(text)} chars). Produce a thorough clause with "
                "2-5 paragraphs of operative language including all the "
                "substantive obligations, carve-outs, and procedures expected "
                "for this clause type."
            )

        # D5: Jurisdiction mismatch in the DPA. If the contract's jurisdiction
        # is India, the DPA must reference DPDP (not GDPR).
        if section.clause_type == "dpa":
            jur = context.get("jurisdiction", "")
            if jur.upper() == "IN" or jur.upper().startswith("IN-"):
                mentions_dpdp = bool(re.search(r"DPDP|Digital Personal Data Protection", text))
                mentions_gdpr = bool(re.search(r"\bGDPR\b|Regulation\s*\(EU\)\s*2016/679|EEA|EU\s*Standard\s*Contractual", text))
                if not mentions_dpdp or mentions_gdpr:
                    defects.append(
                        "Contract jurisdiction is India (IN) so the DPA must be "
                        "written under the Digital Personal Data Protection Act 2023 "
                        "(DPDP Act). Rewrite the DPA to use DPDP terminology "
                        "(Data Fiduciary = Customer, Data Processor = Provider, "
                        "Data Principal = individual). Do NOT reference GDPR, EEA, "
                        "EU SCCs, or EU 2016/679 — these are the wrong framework "
                        "for an India-to-India processing relationship."
                    )

        # D6: Governing law mismatch.
        # The user's requested governing_law must appear in this clause —
        # otherwise the AI has silently substituted Delaware / California
        # defaults from the seed, or truncated the phrase (e.g. producing
        # "governed by ... the Ney York" instead of "the laws of New York").
        # Fires on both combined "governing_law" clauses (common in NDAs)
        # and standalone "dispute_resolution" clauses (common in SaaS/MSA).
        if section.clause_type in {"dispute_resolution", "governing_law"}:
            expected_gl = (context.get("governing_law") or "").strip()
            if expected_gl:
                # Escape regex-unsafe characters in the expected value.
                pattern = re.escape(expected_gl)
                mentions_expected = bool(re.search(pattern, text, re.IGNORECASE))
                # Common wrong defaults the AI might slip into
                WRONG_LAW_DEFAULTS = [
                    r"\bState of Delaware\b",
                    r"\bDelaware\b",
                    r"\bState of California\b",
                    r"\bCalifornia\b",
                    r"\bState of New York\b",
                    r"\bNew York\b",
                ]
                wrong_hits = []
                for wrong_pat in WRONG_LAW_DEFAULTS:
                    # Only flag the wrong default if it ISN'T the expected value
                    # (so "Delaware" is only wrong when expected != Delaware)
                    bare = re.sub(r"\\b|\\s", "", wrong_pat).lower()
                    bare = re.sub(r"state of ", "", bare)
                    if bare not in expected_gl.lower():
                        if re.search(wrong_pat, text):
                            wrong_hits.append(bare)
                if not mentions_expected or wrong_hits:
                    defects.append(
                        f"The user specified '{expected_gl}' as the governing "
                        f"law. The clause must be governed by {expected_gl} "
                        f"and the venue / seat should be a city in "
                        f"{expected_gl}. Do NOT substitute "
                        f"{', '.join(set(wrong_hits)) or 'Delaware or another default US state'}."
                    )
                # "Laws of" completeness check. The AI occasionally truncates
                # the canonical phrase (e.g. produces "governed by and
                # construed in accordance with the Ney York." instead of
                # "the laws of New York"). If the phrase "governed by"
                # appears anywhere in the clause, the words "laws of" must
                # appear within a reasonable window afterward — otherwise
                # the clause is malformed.
                if re.search(r"\bgoverned\s+by\b", text, re.IGNORECASE):
                    # Look for "laws of" within 80 chars after "governed by".
                    after_gb = re.split(
                        r"\bgoverned\s+by\b", text, maxsplit=1, flags=re.IGNORECASE
                    )
                    if len(after_gb) == 2 and not re.search(
                        r"\blaws?\s+of\b", after_gb[1][:120], re.IGNORECASE
                    ):
                        defects.append(
                            "Governing-law clause is malformed: the phrase "
                            "'governed by' is not followed by 'laws of "
                            f"{expected_gl}' within a reasonable window. "
                            "The canonical form is 'This Agreement shall be "
                            f"governed by and construed in accordance with "
                            f"the laws of {expected_gl}, without regard to "
                            "its conflict-of-laws principles.' Rewrite the "
                            "clause to include the full 'laws of "
                            f"{expected_gl}' phrase and verify the "
                            "jurisdiction name is spelled correctly."
                        )

        # D7: Dispute-resolution method mismatch. If user selected
        # "arbitration" but the clause describes "litigation" as the primary
        # mechanism (or vice versa), flag for repair. Also fires on combined
        # "governing_law" clauses (common in NDAs) since they usually
        # bundle the dispute-resolution mechanism.
        if section.clause_type in {"dispute_resolution", "governing_law"}:
            expected_method = (context.get("dispute_resolution") or "").lower().strip()
            if expected_method:
                # Detect the dominant mechanism actually described in the clause.
                # Look for structural cues — "shall be determined by binding
                # arbitration" vs. "either Party may initiate litigation".
                arb_hits = len(re.findall(r"\b(binding\s+)?arbitration\b", text, re.IGNORECASE))
                lit_hits = len(re.findall(r"\b(?:litigation|initiate\s+(?:an?\s+)?action\s+in\s+(?:the\s+)?courts?|file\s+a\s+lawsuit)\b", text, re.IGNORECASE))
                # "Courts of … jurisdiction" language is ambiguous (could be
                # for equitable relief only), so we look for an emphatic
                # litigation-as-primary signal.
                if expected_method == "arbitration" and lit_hits > arb_hits and arb_hits == 0:
                    defects.append(
                        "User selected ARBITRATION as the dispute-resolution "
                        "mechanism, but the clause describes litigation as the "
                        "primary mechanism. Rewrite so disputes are resolved by "
                        "binding arbitration (the user's choice). Courts may "
                        "still be mentioned for injunctive / equitable relief "
                        "only."
                    )
                elif expected_method == "litigation" and arb_hits > 0 and lit_hits == 0:
                    defects.append(
                        "User selected LITIGATION as the dispute-resolution "
                        "mechanism, but the clause describes binding arbitration. "
                        "Rewrite so disputes are resolved in court."
                    )
                elif expected_method == "mediation" and arb_hits + lit_hits > 0 and not re.search(r"\bmediation\b", text, re.IGNORECASE):
                    defects.append(
                        "User selected MEDIATION as the primary dispute-"
                        "resolution mechanism but the clause does not "
                        "reference mediation. Rewrite to include a mediation "
                        "escalation stage."
                    )

        # ------------------------------------------------------------------
        # Playbook-driven detectors. These only fire when the playbook
        # declares the corresponding detector entry, so SaaS/MSA/Employment
        # playbooks that haven't been migrated keep their current behavior.
        # ------------------------------------------------------------------
        playbook_detectors = context.get("detectors", []) or []
        declared_types = {d.get("type") for d in playbook_detectors if isinstance(d, dict)}

        # D9: Forbidden-terms leak (e.g., "Provider/Customer" inside an NDA).
        # The preamble and signature blocks can legitimately name parties, so
        # we skip them; recitals can too (party narrative). Only the operative
        # body is strictly policed.
        forbidden_terms = context.get("forbidden_terms", []) or []
        if "forbidden_terms" in declared_types and forbidden_terms:
            if section.clause_type not in {"preamble", "signature_blocks"}:
                leaked: List[str] = []
                for term in forbidden_terms:
                    if not term:
                        continue
                    # Word-boundary match, case-sensitive (SaaS role labels
                    # are capitalized defined terms; matching "Customer" but
                    # not "customer-facing" as an adjective).
                    if re.search(rf"\b{re.escape(term)}\b", text):
                        leaked.append(term)
                if leaked:
                    defects.append(
                        f"This clause contains role/concept terms that are NOT "
                        f"defined in this contract type: {', '.join(repr(t) for t in leaked)}. "
                        "These appear to have leaked from a different contract "
                        "template (SaaS, Employment, or MSA). Replace them with "
                        "the role labels declared in the roles block "
                        "(Disclosing Party / Receiving Party for NDAs), or "
                        "remove the affected sentences if no correct "
                        "substitution exists."
                    )

        # D10: Entity-type ↔ jurisdiction mismatch. An Indian 'Pvt. Ltd.' is
        # not a US entity; a 'New York'-based party should not be labeled
        # 'Pvt. Ltd.' in the preamble. Only fires on the preamble (where
        # entity types appear) to avoid noise.
        if (
            "entity_jurisdiction_mismatch" in declared_types
            and section.clause_type == "preamble"
        ):
            mismatches = _detect_entity_jurisdiction_mismatches(text, context)
            if mismatches:
                defects.append(
                    "Entity-type / jurisdiction mismatch in the preamble: "
                    + "; ".join(mismatches)
                    + ". Rewrite so each Party's entity-type suffix matches its "
                    "jurisdiction (e.g. an Indian entity is 'Pvt. Ltd.' or "
                    "'Private Limited'; a New York entity is 'Inc.', 'LLC', "
                    "'Corp.', etc. — not 'Pvt. Ltd.')."
                )

        # D11: Truncated / incomplete clause. Open parenthesis with no close,
        # open double-quote with no close, or body ending mid-sentence without
        # terminal punctuation. Indicates the AI was cut off or the seed was
        # copied partially.
        if "truncated_clause" in declared_types and text:
            trunc_issues: List[str] = []
            # Unbalanced parens
            if text.count("(") != text.count(")"):
                trunc_issues.append(
                    f"unbalanced parentheses ({text.count('(')} open vs "
                    f"{text.count(')')} close)"
                )
            # Unbalanced straight quotes
            if text.count('"') % 2 != 0:
                trunc_issues.append("unbalanced double quotes")
            # Ends mid-sentence (no terminal punctuation within last 3 chars,
            # ignoring trailing whitespace)
            stripped_tail = text.rstrip()
            if stripped_tail and stripped_tail[-1] not in ".!?\"')]}\u201d":
                # Allow closing bracket/brace/quote as legitimate enders
                trunc_issues.append("body ends without terminal punctuation")
            if trunc_issues:
                defects.append(
                    "Clause appears truncated or incomplete: "
                    + ", ".join(trunc_issues)
                    + ". Rewrite the clause so every sentence is complete, "
                    "every parenthetical is closed, and every quotation mark "
                    "is balanced."
                )

        # D12: Nested / duplicated quotes around defined terms.
        # Common AI defect: `"Receiving "Party""` (a defined term that was
        # already quoted got quoted again when nested inside another phrase).
        # Matches both straight (") and Unicode smart (\u201c \u201d) quotes
        # because Word/rendering pipelines frequently convert one to the
        # other, and the AI itself mixes them within a single clause.
        if "nested_quote_duplication" in declared_types and text:
            # Any "double-quote-ish" character: straight, smart-left, smart-right.
            _QUOTE_CLASS = r'[\"\u201c\u201d]'
            # Pattern: Qword Qword Q  — three quote characters with two
            # capitalised tokens in between (e.g. "Receiving "Party"").
            nested_pattern = (
                _QUOTE_CLASS
                + r"[A-Z][a-z]+\s+"
                + _QUOTE_CLASS
                + r"[A-Z][a-z]+"
                + _QUOTE_CLASS
                + r"{1,2}"
            )
            nested_quote_hits = re.findall(nested_pattern, text)
            if nested_quote_hits:
                defects.append(
                    "Clause contains nested / duplicated defined-term quotes "
                    f"(example: {nested_quote_hits[0]!r}). Rewrite so each "
                    "defined term is wrapped in a single pair of double quotes "
                    "on first use (e.g. `\"Receiving Party\"`) and unquoted "
                    "thereafter. Use the same quote style (either all straight "
                    "or all curly) consistently throughout the clause."
                )

        # D8: Survival list in Effects of Termination must include the key
        # post-termination provisions: Confidentiality (9), Limitation of
        # Liability (13), Dispute Resolution (17). Missing these creates
        # material legal exposure.
        if section.clause_type == "effects_of_termination":
            # Look for an explicit "sections ... shall survive" style list
            survival_match = re.search(
                r"survival|shall\s+survive|survive\s+(?:the\s+)?(?:expiration|termination)",
                text,
                re.IGNORECASE,
            )
            if survival_match:
                # Check that critical clause types are mentioned by name or number
                # (we can't know the exact numbers, so check by keyword).
                confidentiality_ref = bool(re.search(r"confidentialit", text, re.IGNORECASE))
                liability_ref = bool(re.search(r"(limitation\s+of\s+liability|liability\s+cap|limit)", text, re.IGNORECASE))
                dispute_ref = bool(re.search(r"dispute|arbitration|governing\s+law", text, re.IGNORECASE))
                missing = []
                if not confidentiality_ref:
                    missing.append("Confidentiality")
                if not liability_ref:
                    missing.append("Limitation of Liability")
                if not dispute_ref:
                    missing.append("Dispute Resolution / Governing Law")
                if missing:
                    defects.append(
                        "The survival list in this Effects of Termination "
                        f"clause does not reference {', '.join(missing)}. "
                        "Without surviving these sections post-termination, "
                        "the liability cap, confidentiality obligations, and "
                        "dispute mechanism no longer apply — a material legal "
                        "defect. Rewrite to include these sections by name in "
                        "the survival list."
                    )

        return defects

    async def _repair_clause(
        self,
        section: DraftSection,
        defects: List[str],
        context: Dict[str, Any],
    ) -> Optional[str]:
        """Ask Vertex AI to repair a defective clause. Returns new text or None."""
        try:
            from app.core.vertex_client import get_generative_model, is_available
            if not is_available():
                return None
        except ImportError:
            return None

        defect_list = "\n".join(f"- {d}" for d in defects)

        p1 = context.get("party_1", {})
        p2 = context.get("party_2", {})
        roles = context.get("roles", {})
        if roles:
            roles_line = ", ".join(
                f"{k.replace('_',' ').title()} = {v}" for k, v in roles.items()
            )
        else:
            roles_line = (
                f"Provider = {p1.get('name')}, Customer = {p2.get('name')}"
            )
        # Same provenance gate as _build_clause_prompt: only treat
        # roles.values() as role LABELS when the playbook supplied them.
        if roles and context.get("_roles_from_playbook"):
            role_labels_only = ", ".join(f"'{v}'" for v in roles.values())
        else:
            role_labels_only = "'Provider' and 'Customer'"

        # Playbook doc-type directives (e.g., "This is an NDA, never use
        # Provider/Customer"). Injected into the repair prompt so fixes do
        # not re-introduce the same leak.
        playbook_mandates = context.get("mandatory_directives", []) or []
        forbidden_terms = context.get("forbidden_terms", []) or []
        pb_block = ""
        if playbook_mandates:
            pb_block += (
                "\nDoc-type mandates (must be respected):\n- "
                + "\n- ".join(playbook_mandates)
                + "\n"
            )
        if forbidden_terms:
            pb_block += (
                "\nForbidden terms (never use these in the rewritten clause): "
                + ", ".join(repr(t) for t in forbidden_terms)
                + ".\n"
            )

        prompt = (
            f"You are repairing a defective clause in a {context.get('contract_type','').replace('_',' ').upper()}.\n\n"
            f"Clause heading: **{section.heading}** (type: {section.clause_type})\n"
            f"Jurisdiction: {context.get('jurisdiction', '(unspecified)')}\n"
            f"Defined roles: {roles_line}\n"
            f"{pb_block}\n"
            f"The current clause body has these defects that MUST be fixed:\n"
            f"{defect_list}\n\n"
            f"Current (defective) clause body:\n---\n{section.content}\n---\n\n"
            "Return ONLY the corrected clause body as prose. No heading, no section "
            "number, no markdown fences, no preamble. Start directly with the first "
            "word of the operative text.\n\n"
            "Rules:\n"
            f"- Use ONLY the defined role terms ({role_labels_only}) — NOT the "
            "parties' literal company names — throughout the body. Names belong "
            "only in the Preamble / Signature Block.\n"
            "- Use (a), (b), (c) for sub-parts, not '12.1', '12.2'.\n"
            "- Refer to other clauses by NAME ('the Confidentiality Section', "
            "'Exhibit A') never by number ('Section 5').\n"
            "- Never start the body with an orphan 'Section N' reference.\n"
            "- Every sentence must be complete: close every parenthesis, "
            "balance every quotation mark, end with terminal punctuation.\n"
            "- Preserve the substantive legal positions — do not soften or remove "
            "protections, caps, or carve-outs that the current text has.\n"
        )

        try:
            from google.genai.types import GenerateContentConfig
            model = get_generative_model(settings.GEMINI_MODEL)
            response = await asyncio.wait_for(
                model.generate_content_async(
                    [{"role": "user", "parts": [{"text": prompt}]}],
                    generation_config=GenerateContentConfig(
                        temperature=0.2,
                        max_output_tokens=3500,
                    ),
                ),
                timeout=_PER_CLAUSE_TIMEOUT_S,
            )
            raw = getattr(response, "text", None) or ""
            try:
                from app.services.gemini_analyzer import _strip_markdown_fences
            except ImportError:
                def _strip_markdown_fences(t: str) -> str:
                    return t.strip()
            cleaned = _strip_markdown_fences(raw).strip()
            cleaned = _strip_leading_heading(cleaned, section.heading)
            # Reject trivially-short repairs
            if not cleaned or len(cleaned) < 80:
                return None
            return cleaned
        except Exception as e:
            logger.warning(
                "Repair of clause %s failed (%s)",
                section.clause_type,
                type(e).__name__,
            )
            return None

    async def _coherence_pass(
        self,
        sections: List[DraftSection],
        req: DraftRequest,
        context: Dict[str, Any],
    ) -> List[DraftSection]:
        """Detect and repair defects across all sections (in parallel)."""
        # Build list of (index, section, defects) for only defective sections
        flagged: List[Tuple[int, DraftSection, List[str]]] = []
        for i, section in enumerate(sections):
            defects = self._detect_defects(section, context)
            if defects:
                flagged.append((i, section, defects))

        if not flagged:
            logger.info("Coherence pass: 0/%d sections needed repair", len(sections))
            return sections

        logger.info(
            "Coherence pass: %d/%d sections flagged — running repair in parallel",
            len(flagged),
            len(sections),
        )

        # Repair all flagged sections in parallel (bounded by same semaphore)
        semaphore = asyncio.Semaphore(_MAX_CONCURRENT_CLAUSES)

        async def _repair_one(section: DraftSection, defects: List[str]) -> Optional[str]:
            async with semaphore:
                return await self._repair_clause(section, defects, context)

        repair_tasks = [_repair_one(s, d) for (_, s, d) in flagged]
        repairs = await asyncio.gather(*repair_tasks, return_exceptions=True)

        # Apply successful repairs
        repaired_count = 0
        result = list(sections)  # shallow copy
        for (idx, section, defects), repair in zip(flagged, repairs):
            if isinstance(repair, BaseException):
                logger.warning(
                    "Repair exception for %s: %s",
                    section.clause_type,
                    repair,
                )
                continue
            if repair is None:
                logger.info(
                    "Coherence repair for %s unavailable; keeping original",
                    section.clause_type,
                )
                continue
            result[idx] = DraftSection(
                number=section.number,
                heading=section.heading,
                content=repair,
                clause_type=section.clause_type,
                tier_used=section.tier_used,
                notes=section.notes,
            )
            repaired_count += 1
            logger.info(
                "Coherence repaired %s (%d defects)",
                section.clause_type,
                len(defects),
            )

        logger.info(
            "Coherence pass complete: %d/%d sections repaired",
            repaired_count,
            len(flagged),
        )
        return result

    # ------------------------------------------------------------------
    # Main generation
    # ------------------------------------------------------------------

    async def generate(
        self,
        req: DraftRequest,
        playbook: Dict[str, Any],
    ) -> RawDraft:
        """Build a full RawDraft from *req* using *playbook* as guidance.

        Each clause generates in parallel via Vertex AI. Section numbers
        are assigned dynamically; cross-references are resolved after
        all clauses complete.
        """
        start = time.monotonic()

        context = self._build_context(req, playbook)
        placeholders = self._build_placeholders(req)

        clause_list: List[Dict[str, Any]] = playbook.get("clauses", [])
        # Filter + sort
        clauses_to_generate: List[Tuple[Dict[str, Any], str]] = []
        for clause in sorted(
            clause_list, key=lambda c: c.get("position_in_order", 0)
        ):
            if not self._should_include(clause, req):
                continue
            clause_category = clause.get("category", clause.get("clause_type"))
            tier_name = self._select_tier(
                req.drafting_perspective,
                req.risk_appetite,
                clause_category=clause_category,
                risk_profile=getattr(req, "risk_profile", None) or None,
            )
            clauses_to_generate.append((clause, tier_name))

        logger.info(
            "Generating %d clauses in parallel (concurrency=%d, timeout=%ds/clause)",
            len(clauses_to_generate),
            _MAX_CONCURRENT_CLAUSES,
            int(_PER_CLAUSE_TIMEOUT_S),
        )

        # Parallel generation with concurrency cap
        semaphore = asyncio.Semaphore(_MAX_CONCURRENT_CLAUSES)
        tasks = [
            self._ai_generate_clause(clause, tier, context, semaphore)
            for clause, tier in clauses_to_generate
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        # Build sections
        sections: List[DraftSection] = []
        defined_terms: Dict[str, str] = {}
        tokens_used = 0
        ai_clauses = 0

        for i, ((clause, tier_name), result) in enumerate(
            zip(clauses_to_generate, results), 1
        ):
            # If gather caught an exception, log and fall back to seed
            if isinstance(result, BaseException):
                logger.error(
                    "Unexpected error in clause %s: %s",
                    clause.get("clause_type"),
                    result,
                )
                tier_data = clause.get(tier_name, clause.get("acceptable", {}))
                content = self._fill_placeholders(
                    tier_data.get("template_text", ""), placeholders
                )
                ai_used = False
            else:
                content, tokens, ai_used = result
                tokens_used += tokens
                if ai_used:
                    ai_clauses += 1
                else:
                    # Fill placeholders in the seed fallback
                    content = self._fill_placeholders(content, placeholders)

            # Belt-and-suspenders: strip any leading heading the AI may have
            # embedded, in case the in-_call_vertex pass missed it for any reason.
            heading = clause.get("section_heading", "")
            content = _strip_leading_heading(content.strip(), heading)

            sections.append(
                DraftSection(
                    number=str(i),
                    heading=heading,
                    content=content.strip(),
                    clause_type=clause.get("clause_type", "unknown"),
                    tier_used=tier_name,
                    notes=clause.get("drafting_notes"),
                )
            )

            for term in clause.get("required_defined_terms", []):
                defined_terms.setdefault(term, clause.get("section_heading", ""))

        # Resolve any legacy {{REF:clause_type}} tokens (belt-and-suspenders;
        # the AI is now instructed not to produce them).
        sections = self._resolve_cross_refs(sections)

        # Coherence pass: detect common AI-generated defects (orphan openings,
        # literal-name drift, numeric sub-labels, stub content) and repair
        # each broken section with a targeted AI call. Always AI-first —
        # never a deterministic rewrite.
        sections = await self._coherence_pass(sections, req, context)

        elapsed = time.monotonic() - start
        title = _TITLE_MAP.get(
            req.contract_type,
            req.contract_type.upper().replace("_", " ") + " AGREEMENT",
        )

        logger.info(
            "Draft complete: %d sections (%d AI-generated, %d fallback) in %.1fs, %d tokens",
            len(sections),
            ai_clauses,
            len(sections) - ai_clauses,
            elapsed,
            tokens_used,
        )

        return RawDraft(
            contract_type=req.contract_type,
            title=title,
            sections=sections,
            defined_terms=defined_terms,
            metadata=DraftMetadata(
                playbook_id=playbook.get("contract_type", req.contract_type),
                model=settings.GEMINI_MODEL,
                generation_seconds=round(elapsed, 3),
                tokens_used=tokens_used,
            ),
        )
