"""Consulting / Professional Services Agreement — Default playbook."""
import uuid

def _r(clause_type, primary, risk, patterns, fallback=None, deal_breaker=False, ai_verify=True, prompt=None, order=0):
    sl = {"preferred": primary}
    if fallback:
        sl["fallback"] = fallback
    return {
        "id": str(uuid.uuid4()), "clause_type": clause_type, "primary_position": primary,
        "fallback_position": fallback, "risk_level": risk, "is_deal_breaker": deal_breaker,
        "detection_patterns": {"match_type": "regex", "patterns": patterns},
        "suggested_language": sl, "requires_ai_verification": ai_verify,
        "verification_prompt": prompt, "order_index": order,
    }

CONSULTING = {
    "name": "Consulting / Professional Services Agreement",
    "description": "Default playbook for hiring consultants, freelancers, and advisors in India. Covers scope, milestones, IP ownership, liability, independent contractor status, and non-compete enforceability.",
    "category": "CUSTOM",
    "rules": [
        _r("scope_of_work",
           "Scope of work must be clearly defined with deliverables and acceptance criteria.",
           "yellow",
           [r"(?i)\b(scope\s+of\s+work)\b", r"(?i)\b(deliverable(s)?)\b",
            r"(?i)\b(statement\s+of\s+work|SOW)\b", r"(?i)\b(services?\s+to\s+be\s+(provided|performed))\b"],
           "The Consultant shall provide the services described in the Statement of Work (SOW) attached hereto. Each SOW shall specify deliverables, milestones, timelines, and acceptance criteria.",
           prompt="Check if scope is clearly defined. Flag vague or open-ended scope.", order=0),
        _r("payment_milestones",
           "Payment should be milestone-based, not lump-sum upfront. Protect both parties.",
           "yellow",
           [r"(?i)\b(payment\s+(terms?|schedule|milestones?))\b", r"(?i)\b(milestone[\s-]?based\s+payment)\b",
            r"(?i)\b(advance\s+payment)\b", r"(?i)\b(fee(s)?\s+(and|schedule))\b"],
           "Fees shall be paid on a milestone basis as set forth in the SOW. Payment shall be due within thirty (30) days of acceptance of each milestone deliverable. No advance payment shall exceed 20% of the total SOW value.",
           prompt="Check payment structure. Flag if no milestones or if advance >30% of total.", order=1),
        _r("ip_ownership",
           "Work product IP should be assigned to client upon full payment. Consultant retains pre-existing IP.",
           "red",
           [r"(?i)\b(intellectual\s+property\s+(ownership|rights|assign))\b",
            r"(?i)\b(work\s+product)\b", r"(?i)\b(work(s)?\s+for\s+hire)\b",
            r"(?i)\b(all\s+IP\s+(shall\s+)?(belong|vest|remain))\b"],
           "All work product created by Consultant specifically for Client under this Agreement shall be assigned to Client upon full payment (Work Product IP). Consultant retains all rights in its pre-existing intellectual property, tools, and methodologies (Consultant IP), and grants Client a non-exclusive, perpetual license to use Consultant IP as embedded in the deliverables.",
           deal_breaker=True,
           prompt="Check IP allocation. Flag if consultant retains all IP including work product, or if client claims consultant's pre-existing IP.", order=2),
        _r("limitation_of_liability",
           "Liability should be capped at fees paid under the relevant SOW.",
           "red",
           [r"(?i)\b(limitation\s+of\s+liability)\b", r"(?i)\b(aggregate\s+liability)\b",
            r"(?i)\b(unlimited\s+liability)\b"],
           "Consultant's aggregate liability shall not exceed the total fees paid or payable under the relevant SOW. Neither Party shall be liable for indirect, consequential, or punitive damages.",
           deal_breaker=True,
           prompt="Check liability cap. Flag unlimited liability.", order=3),
        _r("indemnification",
           "Mutual indemnification, capped at fees paid.",
           "yellow",
           [r"(?i)\b(indemnif(y|ication|ies))\b", r"(?i)\b(hold\s+harmless)\b"],
           "Each Party shall indemnify the other against third-party claims arising from breach of this Agreement or negligence, subject to the limitation of liability cap.",
           prompt="Check if indemnification is mutual and capped.", order=4),
        _r("confidentiality",
           "Mutual confidentiality with reasonable term (3 years).",
           "yellow",
           [r"(?i)\b(confidential(ity)?)\b", r"(?i)\b(non[\s-]?disclosure)\b",
            r"(?i)\b(proprietary\s+information)\b"],
           "Both Parties shall maintain confidentiality of each other's proprietary information for three (3) years following termination of this Agreement.",
           prompt="Check if confidentiality is mutual. Flag perpetual term.", order=5),
        _r("termination",
           "Both parties should have reasonable termination rights with notice.",
           "yellow",
           [r"(?i)\b(terminat(e|ion))\b", r"(?i)\b(early\s+termination)\b"],
           "Either Party may terminate this Agreement upon thirty (30) days' written notice. Upon termination, Client shall pay for all work completed and accepted through the termination date. Consultant shall deliver all work-in-progress.",
           prompt="Check if both parties have termination rights. Flag if only client can terminate.", order=6),
        _r("independent_contractor",
           "Must clearly state independent contractor status — not an employment relationship.",
           "yellow",
           [r"(?i)\b(independent\s+contractor)\b", r"(?i)\b(not\s+(an?\s+)?employ(ee|ment))\b",
            r"(?i)\b(contractor\s+status)\b"],
           "The Consultant is an independent contractor and not an employee, agent, or partner of the Client. The Consultant shall be responsible for its own taxes, insurance, and compliance with applicable laws. Nothing in this Agreement creates an employer-employee relationship.",
           prompt="Check if independent contractor status is clearly stated. Flag ambiguity that could imply employment.", order=7),
        _r("non_compete",
           "Non-compete for consultants is generally unenforceable in India under Section 27 ICA.",
           "red",
           [r"(?i)\b(non[\s-]?compete)\b", r"(?i)\bshall\s+not\s+compete\b",
            r"(?i)\b(restriction\s+on\s+competition)\b"],
           "Remove non-compete clause. Post-engagement non-compete restrictions are void under Section 27 of the Indian Contract Act, 1872. During the engagement, Consultant agrees not to perform conflicting services for Client's direct competitors.",
           deal_breaker=True,
           prompt="Check if post-engagement non-compete exists. Unenforceable in India. During-engagement restrictions are acceptable.", order=8),
        _r("governing_law",
           "Indian law.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b"],
           "This Agreement shall be governed by the laws of India.",
           prompt="Flag foreign jurisdiction.", order=9),
    ],
}
