"""Consulting / Professional Services Agreement — Default playbook."""
from scripts.playbooks._helpers import _r  # noqa: F401

CONSULTING = {
    "name": "Consulting / Professional Services Agreement",
    "description": "Default playbook for hiring consultants, freelancers, and advisors in India. Covers scope, milestones, IP ownership, liability, independent contractor status, and non-compete enforceability.",
    "category": "custom",
    "party_side": "buyer",
    "rules": [
        _r("scope_of_work",
           "Scope of work must be clearly defined with deliverables and acceptance criteria.",
           "yellow",
           [r"(?i)\b(scope\s+of\s+work)\b", r"(?i)\b(deliverable(s)?)\b",
            r"(?i)\b(statement\s+of\s+work|SOW)\b", r"(?i)\b(services?\s+to\s+be\s+(provided|performed))\b"],
           "The Consultant shall provide the services described in the Statement of Work (SOW) attached hereto. Each SOW shall specify deliverables, milestones, timelines, and acceptance criteria.",
           prompt="Check if scope is clearly defined. Flag vague or open-ended scope.", order=0,
           detection_mode="ai_with_keywords",
           risk_description="Scope is vague, open-ended, or lacks clear deliverables",
           unacceptable_signals=["as directed by client", "all services reasonably requested", "scope to be determined"],
           acceptable_signals=["specific deliverables listed", "defined milestones", "change order process"],
           acceptable_position="Defined deliverables with milestones, acceptance criteria, and change order process"),
        _r("payment_milestones",
           "Payment should be milestone-based, not lump-sum upfront. Protect both parties.",
           "yellow",
           [r"(?i)\b(payment\s+(terms?|schedule|milestones?))\b", r"(?i)\b(milestone[\s-]?based\s+payment)\b",
            r"(?i)\b(advance\s+payment)\b", r"(?i)\b(fee(s)?\s+(and|schedule))\b"],
           "Fees shall be paid on a milestone basis as set forth in the SOW. Payment shall be due within thirty (30) days of acceptance of each milestone deliverable. No advance payment shall exceed 20% of the total SOW value.",
           prompt="Check payment structure. Flag if no milestones or if advance >30% of total.", order=1,
           detection_mode="ai_with_keywords",
           risk_description="Payment structure is lump-sum or advance exceeds 30% of total",
           unacceptable_signals=["100% advance", "payment upfront before delivery", "no milestone payments"],
           acceptable_signals=["milestone-based", "payment upon acceptance", "advance not exceeding 20%"],
           acceptable_position="Milestone-based payments with advance capped at 20% of total"),
        _r("ip_ownership",
           "Work product IP should be assigned to client upon full payment. Consultant retains pre-existing IP.",
           "red",
           [r"(?i)\b(intellectual\s+property\s+(ownership|rights|assign))\b",
            r"(?i)\b(work\s+product)\b", r"(?i)\b(work(s)?\s+for\s+hire)\b",
            r"(?i)\b(all\s+IP\s+(shall\s+)?(belong|vest|remain))\b"],
           "All work product created by Consultant specifically for Client under this Agreement shall be assigned to Client upon full payment (Work Product IP). Consultant retains all rights in its pre-existing intellectual property, tools, and methodologies (Consultant IP), and grants Client a non-exclusive, perpetual license to use Consultant IP as embedded in the deliverables.",
           deal_breaker=True,
           prompt="Check IP allocation. Flag if consultant retains all IP including work product, or if client claims consultant's pre-existing IP.", order=2,
           detection_mode="ai_with_keywords",
           risk_description="Consultant retains all IP including work product paid for by client",
           unacceptable_signals=["consultant retains all IP", "client receives limited license only", "no assignment of work product"],
           acceptable_signals=["work product assigned to client", "consultant retains pre-existing IP"],
           acceptable_position="Work product IP assigned to client; consultant retains pre-existing IP"),
        _r("limitation_of_liability",
           "Liability should be capped at fees paid under the relevant SOW.",
           "red",
           [r"(?i)\b(limitation\s+of\s+liability)\b", r"(?i)\b(aggregate\s+liability)\b",
            r"(?i)\b(unlimited\s+liability)\b"],
           "Consultant's aggregate liability shall not exceed the total fees paid or payable under the relevant SOW. Neither Party shall be liable for indirect, consequential, or punitive damages.",
           deal_breaker=True,
           prompt="Check liability cap. Flag unlimited liability.", order=3,
           detection_mode="ai_with_keywords",
           risk_description="Liability cap missing or unlimited for consulting engagement",
           unacceptable_signals=["unlimited liability", "no cap", "all damages without limitation"],
           acceptable_signals=["capped at fees paid", "limited to total contract value"],
           acceptable_position="Mutual liability capped at total fees paid"),
        _r("indemnification",
           "Mutual indemnification, capped at fees paid.",
           "yellow",
           [r"(?i)\b(indemnif(y|ication|ies))\b", r"(?i)\b(hold\s+harmless)\b"],
           "Each Party shall indemnify the other against third-party claims arising from breach of this Agreement or negligence, subject to the limitation of liability cap.",
           prompt="Check if indemnification is mutual and capped.", order=4,
           detection_mode="ai_with_keywords",
           risk_description="Indemnification not mutual or exceeds total fees paid",
           unacceptable_signals=["consultant shall indemnify without limitation", "one-sided indemnification"],
           acceptable_signals=["mutual indemnification", "capped at fees paid", "limited to direct damages"],
           acceptable_position="Mutual indemnification capped at total fees paid, limited to direct damages"),
        _r("confidentiality",
           "Mutual confidentiality with reasonable term (3 years).",
           "yellow",
           [r"(?i)\b(confidential(ity)?)\b", r"(?i)\b(non[\s-]?disclosure)\b",
            r"(?i)\b(proprietary\s+information)\b"],
           "Both Parties shall maintain confidentiality of each other's proprietary information for three (3) years following termination of this Agreement.",
           prompt="Check if confidentiality is mutual. Flag perpetual term.", order=5,
           detection_mode="ai_with_keywords",
           risk_description="Confidentiality is one-sided or perpetual",
           unacceptable_signals=["perpetual confidentiality", "only consultant bound"],
           acceptable_signals=["mutual confidentiality", "3 years post-termination"],
           acceptable_position="Mutual, 3 years post-termination"),
        _r("termination",
           "Both parties should have reasonable termination rights with notice.",
           "yellow",
           [r"(?i)\b(terminat(e|ion))\b", r"(?i)\b(early\s+termination)\b"],
           "Either Party may terminate this Agreement upon thirty (30) days' written notice. Upon termination, Client shall pay for all work completed and accepted through the termination date. Consultant shall deliver all work-in-progress.",
           prompt="Check if both parties have termination rights. Flag if only client can terminate.", order=6,
           detection_mode="ai_with_keywords",
           risk_description="Termination rights are one-sided or no notice period",
           unacceptable_signals=["only client may terminate", "immediate termination without notice"],
           acceptable_signals=["either party may terminate", "30 days written notice"],
           acceptable_position="Either party with 30-day notice; payment for completed work on termination"),
        _r("independent_contractor",
           "Must clearly state independent contractor status — not an employment relationship.",
           "yellow",
           [r"(?i)\b(independent\s+contractor)\b", r"(?i)\b(not\s+(an?\s+)?employ(ee|ment))\b",
            r"(?i)\b(contractor\s+status)\b"],
           "The Consultant is an independent contractor and not an employee, agent, or partner of the Client. The Consultant shall be responsible for its own taxes, insurance, and compliance with applicable laws. Nothing in this Agreement creates an employer-employee relationship.",
           prompt="Check if independent contractor status is clearly stated. Flag ambiguity that could imply employment.", order=7,
           detection_mode="ai_with_keywords",
           risk_description="Independent contractor status is ambiguous or implies employment relationship",
           unacceptable_signals=["employee", "employment relationship", "employer obligations"],
           acceptable_signals=["independent contractor", "not an employee", "responsible for own taxes"],
           acceptable_position="Clearly stated independent contractor with no employment relationship"),
        _r("non_compete",
           "Non-compete for consultants is generally unenforceable in India under Section 27 ICA.",
           "red",
           [r"(?i)\b(non[\s-]?compete)\b", r"(?i)\bshall\s+not\s+compete\b",
            r"(?i)\b(restriction\s+on\s+competition)\b"],
           "Remove non-compete clause. Post-engagement non-compete restrictions are void under Section 27 of the Indian Contract Act, 1872. During the engagement, Consultant agrees not to perform conflicting services for Client's direct competitors.",
           deal_breaker=True,
           prompt="Check if post-engagement non-compete exists. Unenforceable in India. During-engagement restrictions are acceptable.", order=8,
           detection_mode="ai_with_keywords",
           risk_description="Non-compete for consultant, generally unenforceable in India under Section 27",
           unacceptable_signals=["consultant shall not compete", "non-compete", "restrained from providing services to competitors"],
           acceptable_signals=["non-solicitation only", "no non-compete clause"],
           clause_context="Section 27 Indian Contract Act makes post-engagement non-competes void for consultants",
           acceptable_position="Remove non-compete; replace with 12-month non-solicitation"),
        _r("governing_law",
           "Indian law.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b"],
           "This Agreement shall be governed by the laws of India.",
           prompt="Flag foreign jurisdiction.", order=9,
           detection_mode="ai_with_keywords",
           risk_description="Governing law is not Indian law",
           unacceptable_signals=["foreign jurisdiction"],
           acceptable_signals=["laws of India"],
           acceptable_position="Indian law"),
    ],
}
