"""Data Processing Agreement — Default playbook (DPDP Act 2023 compliant)."""
from scripts.playbooks._helpers import _r  # noqa: F401

DPA = {
    "name": "Data Processing Agreement (DPA)",
    "description": (
        "Data-fiduciary-side contract playbook for allocating processor duties "
        "under the DPDP Act 2023 and DPDP Rules 2025. Contractual controls are "
        "identified as negotiated safeguards, not misstated as automatic "
        "statutory wording. Main substantive commencement is 13 May 2027."
    ),
    "category": "dpa",
    "party_side": "buyer",
    "version": 2,
    "rules": [
        _r("purpose_limitation",
           "Limit the processor to the documented service purposes and instructions; flag independent use that may change its role or exceed the fiduciary's lawful purpose.",
           "yellow",
           [r"(?i)\b(purpose\s+(limitation|of\s+processing))\b",
            r"(?i)\b(process(ing)?\s+(only|solely)\s+for)\b",
            r"(?i)\b(processor\s+may\s+use\s+(the\s+)?data\s+for)\b"],
           "The Data Processor shall process Personal Data only for the specific purposes set forth in this Agreement and strictly in accordance with the documented instructions of the Data Fiduciary. The Processor shall not process Personal Data for any other purpose.",
           prompt="Determine the parties' roles and check whether the processor is limited to documented purposes and instructions. Flag independent marketing, profiling, or analytics use unless separately authorised on a valid legal basis.", order=0,
           detection_mode="ai_with_keywords",
           risk_description="Processor can use personal data beyond specified purposes",
           unacceptable_signals=["processor may use data for its own purposes", "data for marketing", "analytics on personal data"],
           acceptable_signals=["solely for specified purposes", "documented instructions only"],
           clause_context="This is a contractual allocation that helps the Data Fiduciary discharge its DPDP obligations; do not call the exact wording an automatic statutory DPA requirement.",
           acceptable_position="Processing is limited to documented service purposes and lawful instructions, with separately authorised uses expressly identified."),
        _r("data_subject_rights",
           "Require practical processor assistance so the Data Fiduciary can answer applicable Data Principal requests for information, correction, completion, updating, and erasure.",
           "yellow",
           [r"(?i)\b(data\s+subject\s+rights)\b", r"(?i)\b(data\s+principal\s+rights)\b",
            r"(?i)\b(right\s+to\s+(access|correct|eras|delet))\b",
            r"(?i)\b(DPDP.{0,20}rights)\b"],
           "The Processor shall provide reasonable and timely assistance requested by the Data Fiduciary to enable it to respond to applicable Data Principal requests under sections 11 and 12 of the DPDP Act, including information, correction, completion, updating, and erasure requests, subject to applicable retention law.",
           prompt="Check whether the processor must give timely operational assistance for applicable Data Principal requests. Do not describe section 11 as a general right to obtain a copy of all data.", order=1,
           detection_mode="ai_with_keywords",
           risk_description="Data principal rights (access, correction, erasure) not addressed",
           unacceptable_signals=["no obligation to assist with data subject requests", "rights handled at discretion"],
           acceptable_signals=["assist with data principal requests", "access, correction, erasure"],
           clause_context="Sections 11 and 12 state the relevant rights. Processor assistance is a negotiated control because the Data Fiduciary remains responsible for compliance.",
           acceptable_position="Processor provides timely assistance for applicable information, correction, completion, updating, and erasure workflows."),
        _r("sub_processor_controls",
           "Use notice, objection, flow-down, and continuing-liability controls for sub-processors; treat prior approval as the client's preferred contractual position, not a universal DPDP statutory formality.",
           "yellow",
           [r"(?i)\b(sub[\s-]?processor)\b", r"(?i)\b(sub[\s-]?contract(or|ing)?)\b",
            r"(?i)\b(third[\s-]?party\s+process(or|ing))\b"],
           "The Processor shall not engage any sub-processor without prior written consent of the Data Fiduciary. The Processor shall maintain a list of approved sub-processors and notify the Data Fiduciary of any changes at least thirty (30) days in advance.",
           prompt="Check notice, objection or consent, equivalent obligation flow-down, and the primary processor's continuing responsibility for sub-processors. Separate the negotiated control from statutory minimums.", order=2,
           detection_mode="ai_with_keywords",
           risk_description="No notification or approval when processor adds sub-processors",
           unacceptable_signals=["processor may engage any sub-processor", "no notification required", "blanket authorization"],
           acceptable_signals=["prior written consent", "30 days notice", "right to object", "list of current sub-processors"],
           clause_context="The DPDP Act permits processing through a Data Processor under a valid contract and keeps the Data Fiduciary responsible. It does not itself prescribe a GDPR-style sub-processor approval mechanism.",
           acceptable_position="Advance notice with a meaningful objection right, equivalent flow-down duties, and continuing processor responsibility."),
        _r("data_breach_notification",
           "Set an internal processor-to-fiduciary notice clock short enough for the fiduciary to meet Rule 7: notices to affected Data Principals and an initial Board report without delay, followed by Board details within 72 hours unless extended.",
           "red",
           [r"(?i)\b(data\s+breach\s+notif(y|ication))\b", r"(?i)\b(security\s+(breach|incident)\s+notif)\b",
            r"(?i)\b(breach.{0,30}(notify|inform|report))\b",
            r"(?i)\b(personal\s+data\s+breach)\b"],
           "The Processor shall notify the Data Fiduciary immediately, and in any event within twenty-four (24) hours, after becoming aware of a Personal Data Breach and shall promptly provide all information and cooperation reasonably required for notices, mitigation, investigation, and the detailed report to the Data Protection Board of India.",
           deal_breaker=True,
           prompt="Check whether the processor must notify the fiduciary quickly enough to support Rule 7. Do not treat 72 hours as the processor's statutory deadline or as the deadline for the initial Board or affected-principal notice.", order=3,
           detection_mode="ai_with_keywords",
           risk_description="Breach notification exceeds 72 hours or lacks specificity",
           unacceptable_signals=["notify within 7 days", "reasonable time", "at processor's discretion"],
           acceptable_signals=["immediately", "within 24 hours", "ongoing updates", "cooperate with notifications"],
           clause_context="Rule 7 applies notice duties to the Data Fiduciary. Initial Board notice and affected-principal notice are without delay; specified Board details follow within 72 hours unless the Board allows more time. The processor clock is contractual.",
           acceptable_position="Immediate notice, no later than 24 hours, followed by rolling details and notification cooperation."),
        _r("data_deletion_return",
           "Require return or secure deletion when services end or data is no longer needed, while preserving only data that applicable law requires to be retained.",
           "red",
           [r"(?i)\b(data\s+(deletion|destruction|return))\b",
            r"(?i)\b(upon\s+termination.{0,60}(delete|destroy|return)\s+(all\s+)?(personal\s+)?data)\b",
            r"(?i)\b(post[\s-]?termination\s+data)\b"],
           "Upon termination of this Agreement, the Processor shall, at the Data Fiduciary's election, return or permanently delete all Personal Data within thirty (30) days and provide written certification of deletion. The Processor shall not retain any copies except as required by applicable law.",
           deal_breaker=True,
           prompt="Check for return/deletion, backups, certification, timing, and a narrow legal-retention exception. Distinguish contract termination from the DPDP section 8(7) erasure trigger.", order=4,
           detection_mode="ai_with_keywords",
           risk_description="No data deletion or return clause on contract termination",
           unacceptable_signals=["no deletion obligation", "data retained after termination", "deletion at processor discretion"],
           acceptable_signals=["delete within 30 days", "return or delete at fiduciary's choice", "certification of deletion"],
           clause_context="Section 8(7) addresses erasure when consent is withdrawn or the specified purpose is no longer served, subject to necessary legal retention. A termination workflow and certificate are negotiated operational controls.",
           acceptable_position="Return or deletion within 30 days, including backup lifecycle treatment and certification, subject only to identified legal retention."),
        _r("cross_border_transfer",
           "Identify all foreign processing locations and prohibit transfers that breach a Central Government restriction, Rule 15 requirements, or stricter sectoral/localisation law.",
           "red",
           [r"(?i)\b(cross[\s-]?border\s+(transfer|data))\b",
            r"(?i)\b(transfer\s+(of\s+)?(personal\s+)?data\s+(outside|out\s+of)\s+india)\b",
            r"(?i)\b(international\s+data\s+transfer)\b",
            r"(?i)\b(data\s+transfer\s+to\s+(a\s+)?third\s+country)\b"],
           "The Processor shall disclose each country in which Personal Data will be processed and shall not transfer or make such data available outside India in breach of section 16 of the DPDP Act, Rule 15 of the DPDP Rules, any applicable Central Government requirement, or stricter sectoral localisation law. The Processor shall provide reasonable transfer-risk information and comply with agreed safeguards.",
           deal_breaker=True,
           prompt="Identify transfer locations and restrictions. Flag positive-allowlist wording, unrestricted location changes, or failure to account for Rule 15 and stricter sectoral law.", order=5,
           detection_mode="ai_with_keywords",
           risk_description="Personal data transferred outside India without adequate safeguards",
           unacceptable_signals=["data may be processed anywhere", "no restriction on transfer", "stored outside India at discretion"],
           acceptable_signals=["locations disclosed", "government restrictions", "Rule 15", "sectoral localisation", "transfer safeguards"],
           clause_context="Section 16 is a negative-restriction mechanism, not a positive country allowlist. Rule 15 and any stricter Indian law remain relevant; consent does not override them.",
           acceptable_position="Locations are disclosed; transfers comply with section 16, Rule 15, notified requirements, and stricter sectoral law."),
        _r("security_measures",
           "Must specify concrete technical and organizational security measures, not vague promises.",
           "yellow",
           [r"(?i)\b(security\s+measures)\b", r"(?i)\b(technical\s+and\s+organi[sz]ational\s+measures)\b",
            r"(?i)\b(appropriate\s+security)\b", r"(?i)\b(encrypt(ion|ed))\b"],
           "The Processor shall implement and maintain appropriate technical and organizational measures including: (a) encryption of Personal Data at rest and in transit; (b) access controls and authentication; (c) regular security testing; (d) employee training on data protection; (e) incident response procedures.",
           prompt="Check whether the schedule describes deployment-specific safeguards, incident handling, access control, resilience, testing, and evidence. Do not infer that generic boilerplate proves implementation.", order=6,
           detection_mode="ai_with_keywords",
           risk_description="Security measures are vague with no specific technical controls listed",
           unacceptable_signals=["appropriate security measures", "reasonable measures", "at processor's discretion"],
           acceptable_signals=["encryption at rest and in transit", "access controls", "regular security testing"],
           clause_context="Section 8(4) requires appropriate technical and organisational measures; section 8(5) and Rule 6 concern reasonable security safeguards. The contract must not claim controls that are not actually deployed.",
           acceptable_position="A factually accurate security schedule covers encryption where appropriate, access control, monitoring, resilience, testing, training, and incident response."),
        _r("audit_rights",
           "Negotiate proportionate evidence and audit rights so the fiduciary can oversee processor performance and investigate material incidents.",
           "yellow",
           [r"(?i)\b(audit\s+right)\b", r"(?i)\b(right\s+to\s+audit)\b",
            r"(?i)\b(inspection\s+right)\b", r"(?i)\b(compliance\s+audit)\b"],
           "The Data Fiduciary shall have the right to audit the Processor's compliance with this Agreement and applicable data protection laws. Such audits may be conducted annually or upon reasonable notice following a data breach or complaint. The Processor shall cooperate fully with any audit.",
           prompt="Check the evidence package, certification access, audit triggers, scope, frequency, costs, confidentiality, remediation, and regulator cooperation. Treat this as a contractual oversight control.", order=7,
           detection_mode="ai_with_keywords",
           risk_description="No audit rights for data fiduciary over processor's data handling",
           unacceptable_signals=["no audit rights", "processor self-certifies", "audit at processor's sole discretion"],
           acceptable_signals=["right to audit", "annual audit", "third-party audit", "cooperate with audits"],
           clause_context="A general annual customer audit right is not stated verbatim in the DPDP Act. It is a negotiated mechanism supporting the Data Fiduciary's continuing responsibility.",
           acceptable_position="Current independent assurance plus proportionate audit rights after material incidents, control failures, or regulator requests."),
        _r("liability_indemnification",
           "Allocate losses caused by the processor's contract breach, while separately negotiating caps, carve-outs, causation, defense control, and whether regulatory amounts may lawfully be shifted.",
           "red",
           [r"(?i)\b(indemnif(y|ication)).{0,60}(data|breach|processing)\b",
            r"(?i)\b(liab(le|ility)).{0,60}(data\s+breach|processing)\b"],
           "Subject to the agreed liability structure and applicable law, the Processor shall indemnify the Data Fiduciary against third-party claims and reasonable response costs to the extent caused by the Processor's breach of this Agreement, unauthorised processing, or failure to implement agreed safeguards. Regulatory amounts are included only to the extent lawfully recoverable.",
           prompt="Check causation, recoverable loss, defense mechanics, caps and carve-outs. Do not present an indemnity, uncapped exposure, or recovery of a Board penalty as automatically required by the DPDP Act.", order=8,
           detection_mode="ai_with_keywords",
           risk_description="Processor has no indemnification obligation for its breaches",
           unacceptable_signals=["processor not liable for breaches", "fiduciary bears all liability"],
           acceptable_signals=["processor indemnifies for its breach", "processor liable for non-compliance"],
           clause_context="The DPDP Act allocates public-law duties and penalties; it does not automatically create the proposed private indemnity or make regulatory penalties recoverable between parties.",
           acceptable_position="Processor covers third-party claims and reasonable response costs caused by its breach, with express and lawful treatment under the negotiated cap."),
        _r("governing_law",
           "State governing law and forum clearly, while preserving mandatory DPDP and other data-protection obligations that apply regardless of the contractual choice.",
           "yellow",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b"],
           "This Agreement shall be governed by the laws of [agreed jurisdiction]. Nothing in this Agreement limits either Party's obligation to comply with mandatory data-protection law applicable to its processing, including the DPDP Act where its territorial scope is met.",
           prompt="Identify governing law and forum, conflicts with the main agreement, and preservation of mandatory applicable data law. Do not say Indian governing law is required for DPDP applicability.", order=9,
           detection_mode="ai_with_keywords",
           risk_description="Governing law/forum is missing, conflicts with the main agreement, or purports to disapply mandatory data-protection duties",
           unacceptable_signals=["no governing law", "data protection law does not apply", "waiver of mandatory privacy law"],
           acceptable_signals=["governing law stated", "mandatory applicable data protection law preserved", "forum aligned with main agreement"],
           clause_context="DPDP territorial scope and mandatory application do not depend solely on the contract choosing Indian governing law.",
           acceptable_position="Clear governing law and forum aligned with the main agreement, with mandatory applicable data law preserved."),
    ],
}
