"""Data Processing Agreement — Default playbook (DPDP Act 2023 compliant)."""
import uuid

def _r(clause_type, primary, risk, patterns, fallback=None, deal_breaker=False, ai_verify=True, prompt=None, order=0):
    sl = {"preferred": primary}
    if fallback:
        sl["fallback"] = fallback
    return {
        "id": str(uuid.uuid4()), "clause_type": clause_type, "primary_position": primary,
        "fallback_position": fallback, "risk_level": risk, "is_deal_breaker": deal_breaker,
        "detection_patterns": {"match_type": "regex", "patterns": patterns},
        "suggested_language": sl, "requires_ai_verification": ai_verify,
        "verification_prompt": prompt, "order_index": order,
    }

DPA = {
    "name": "Data Processing Agreement (DPA)",
    "description": "Default playbook for data processing agreements under DPDP Act 2023. Covers purpose limitation, data subject rights, sub-processor controls, breach notification, deletion, cross-border transfers, and audit rights.",
    "category": "DPA",
    "rules": [
        _r("purpose_limitation",
           "Processor must only process data for specified purposes. Flag if processor can use data for own purposes.",
           "yellow",
           [r"(?i)\b(purpose\s+(limitation|of\s+processing))\b",
            r"(?i)\b(process(ing)?\s+(only|solely)\s+for)\b",
            r"(?i)\b(processor\s+may\s+use\s+(the\s+)?data\s+for)\b"],
           "The Data Processor shall process Personal Data only for the specific purposes set forth in this Agreement and strictly in accordance with the documented instructions of the Data Fiduciary. The Processor shall not process Personal Data for any other purpose.",
           prompt="Check if purpose limitation exists. Flag if processor can use data for own marketing or analytics purposes.", order=0),
        _r("data_subject_rights",
           "Must support DPDP Act obligations including right to access, correction, and erasure.",
           "yellow",
           [r"(?i)\b(data\s+subject\s+rights)\b", r"(?i)\b(data\s+principal\s+rights)\b",
            r"(?i)\b(right\s+to\s+(access|correct|eras|delet))\b",
            r"(?i)\b(DPDP.{0,20}rights)\b"],
           "The Processor shall assist the Data Fiduciary in fulfilling its obligations to respond to Data Principal rights requests under the DPDP Act, 2023, including rights of access, correction, and erasure, within the timelines prescribed by law.",
           prompt="Check if data subject/principal rights are addressed. Flag if missing.", order=1),
        _r("sub_processor_controls",
           "Must require notification and approval before engaging sub-processors.",
           "yellow",
           [r"(?i)\b(sub[\s-]?processor)\b", r"(?i)\b(sub[\s-]?contract(or|ing)?)\b",
            r"(?i)\b(third[\s-]?party\s+process(or|ing))\b"],
           "The Processor shall not engage any sub-processor without prior written consent of the Data Fiduciary. The Processor shall maintain a list of approved sub-processors and notify the Data Fiduciary of any changes at least thirty (30) days in advance.",
           prompt="Check sub-processor controls. Flag if processor can freely engage sub-processors without notification.", order=2),
        _r("data_breach_notification",
           "Breach notification must be 'without undue delay' per DPDP Act. Flag if >72 hours.",
           "red",
           [r"(?i)\b(data\s+breach\s+notif(y|ication))\b", r"(?i)\b(security\s+(breach|incident)\s+notif)\b",
            r"(?i)\b(breach.{0,30}(notify|inform|report))\b",
            r"(?i)\b(personal\s+data\s+breach)\b"],
           "The Processor shall notify the Data Fiduciary of any Personal Data Breach without undue delay and in any event within seventy-two (72) hours of becoming aware of such breach. The notification shall include: (a) nature of the breach; (b) categories and approximate number of affected data principals; (c) likely consequences; (d) measures taken or proposed.",
           deal_breaker=True,
           prompt="Check breach notification timeline. Flag if >72 hours. DPDP Act requires 'without undue delay'.", order=3),
        _r("data_deletion_return",
           "Must include data deletion/return clause upon termination. No deletion clause = deal-breaker.",
           "red",
           [r"(?i)\b(data\s+(deletion|destruction|return))\b",
            r"(?i)\b(upon\s+termination.{0,60}(delete|destroy|return)\s+(all\s+)?(personal\s+)?data)\b",
            r"(?i)\b(post[\s-]?termination\s+data)\b"],
           "Upon termination of this Agreement, the Processor shall, at the Data Fiduciary's election, return or permanently delete all Personal Data within thirty (30) days and provide written certification of deletion. The Processor shall not retain any copies except as required by applicable law.",
           deal_breaker=True,
           prompt="Check if data deletion/return clause exists for termination. Flag if missing.", order=4),
        _r("cross_border_transfer",
           "Cross-border data transfer outside India must have adequate safeguards per DPDP Act 2023.",
           "red",
           [r"(?i)\b(cross[\s-]?border\s+(transfer|data))\b",
            r"(?i)\b(transfer\s+(of\s+)?(personal\s+)?data\s+(outside|out\s+of)\s+india)\b",
            r"(?i)\b(international\s+data\s+transfer)\b",
            r"(?i)\b(data\s+transfer\s+to\s+(a\s+)?third\s+country)\b"],
           "The Processor shall not transfer Personal Data outside India except to countries or territories notified by the Central Government under the DPDP Act, 2023. Any permitted cross-border transfer shall be subject to appropriate contractual safeguards ensuring equivalent data protection standards.",
           deal_breaker=True,
           prompt="Check if data goes outside India. Flag cross-border transfers without safeguards per DPDP Act.", order=5),
        _r("security_measures",
           "Must specify concrete technical and organizational security measures, not vague promises.",
           "yellow",
           [r"(?i)\b(security\s+measures)\b", r"(?i)\b(technical\s+and\s+organi[sz]ational\s+measures)\b",
            r"(?i)\b(appropriate\s+security)\b", r"(?i)\b(encrypt(ion|ed))\b"],
           "The Processor shall implement and maintain appropriate technical and organizational measures including: (a) encryption of Personal Data at rest and in transit; (b) access controls and authentication; (c) regular security testing; (d) employee training on data protection; (e) incident response procedures.",
           prompt="Check if specific security measures are listed. Flag if only vague 'appropriate security' without specifics.", order=6),
        _r("audit_rights",
           "Data fiduciary must have the right to audit the processor's data handling practices.",
           "yellow",
           [r"(?i)\b(audit\s+right)\b", r"(?i)\b(right\s+to\s+audit)\b",
            r"(?i)\b(inspection\s+right)\b", r"(?i)\b(compliance\s+audit)\b"],
           "The Data Fiduciary shall have the right to audit the Processor's compliance with this Agreement and applicable data protection laws. Such audits may be conducted annually or upon reasonable notice following a data breach or complaint. The Processor shall cooperate fully with any audit.",
           prompt="Check if audit rights exist for the data fiduciary. Flag if no audit mechanism.", order=7),
        _r("liability_indemnification",
           "Processor must indemnify for data breaches caused by its failure to comply with the DPA.",
           "red",
           [r"(?i)\b(indemnif(y|ication)).{0,60}(data|breach|processing)\b",
            r"(?i)\b(liab(le|ility)).{0,60}(data\s+breach|processing)\b"],
           "The Processor shall indemnify and hold harmless the Data Fiduciary against any losses, claims, damages, or penalties arising from the Processor's breach of this Agreement or applicable data protection laws, including fines imposed by the Data Protection Board of India.",
           prompt="Check if processor liability for breaches is addressed. Flag if no indemnification for data breaches.", order=8),
        _r("governing_law",
           "Must be Indian law for DPDP Act compliance.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b"],
           "This Agreement shall be governed by the laws of India, including the Digital Personal Data Protection Act, 2023 and the Information Technology Act, 2000.",
           prompt="Must be Indian law for DPDP compliance.", order=9),
    ],
}
