"""Employment Agreement — Default playbook (India-specific)."""
import uuid

def _r(clause_type, primary, risk, patterns, fallback=None, deal_breaker=False, ai_verify=True, prompt=None, order=0):
    sl = {"preferred": primary}
    if fallback:
        sl["fallback"] = fallback
    return {
        "id": str(uuid.uuid4()), "clause_type": clause_type, "primary_position": primary,
        "fallback_position": fallback, "risk_level": risk, "is_deal_breaker": deal_breaker,
        "detection_patterns": {"match_type": "regex", "patterns": patterns},
        "suggested_language": sl, "requires_ai_verification": ai_verify,
        "verification_prompt": prompt, "order_index": order,
    }

EMPLOYMENT = {
    "name": "Employment Agreement (India)",
    "description": "Default playbook for Indian employment agreements. Covers probation, notice period, non-compete (Section 27), non-solicitation, IP assignment, confidentiality, garden leave, and restrictive covenants.",
    "category": "EMPLOYMENT",
    "rules": [
        _r("probation_period",
           "Probation period should be 3-6 months. Flag if exceeding 6 months.",
           "yellow",
           [r"(?i)\b(probation(ary)?\s+(period|term))\b", r"(?i)\b(probation\s+of\s+\d+\s+months)\b",
            r"(?i)\b(initial\s+probation)\b"],
           "The Employee shall be on probation for a period of six (6) months from the date of joining. During probation, either Party may terminate employment with fifteen (15) days' written notice.",
           prompt="Check probation duration. Flag if >6 months. Standard: 3-6 months.", order=0),
        _r("notice_period",
           "Either Party may terminate this employment by providing ninety (90) days' written notice or payment of salary in lieu of notice.",
           "yellow",
           [r"(?i)\b(notice\s+period)\b", r"(?i)\b(\d+\s+(month|day|week)s?\s+notice)\b",
            r"(?i)\b(prior\s+(written\s+)?notice\s+of\s+\d+)\b"],
           fallback="Either Party may terminate with sixty (60) days' written notice or salary in lieu thereof.",
           prompt="Check notice period length. Flag if >3 months for non-CXO roles.", order=1),
        _r("non_compete",
           "Non-compete clauses are largely UNENFORCEABLE in India under Section 27 of the Indian Contract Act, 1872. Flag presence as RED risk.",
           "red",
           [r"(?i)\b(non[\s-]?compete)\b", r"(?i)\bshall\s+not\s+compete\b",
            r"(?i)\b(restriction\s+on\s+competition)\b", r"(?i)\b(competitive\s+activit(y|ies))\b",
            r"(?i)\b(refrain\s+from\s+(engag|compet))\b"],
           "Remove post-employment non-compete clause. Non-compete restrictions post-termination are void under Section 27 of the Indian Contract Act, 1872 as held by the Supreme Court of India in Superintendence Company of India (P) Ltd v. Krishan Murgai (1981).",
           deal_breaker=True,
           prompt="Check if post-employment non-compete exists. This is unenforceable in India under Section 27 ICA. Flag as deal-breaker.", order=2),
        _r("non_solicitation",
           "Non-solicitation is enforceable if reasonable. Limit to 12 months post-termination.",
           "yellow",
           [r"(?i)\b(non[\s-]?solicit(ation)?)\b", r"(?i)\bshall\s+not\s+(solicit|hire|recruit)\b",
            r"(?i)\b(solicit|entice).{0,60}(employee|client|customer)\b"],
           "For a period of twelve (12) months following termination, the Employee shall not directly solicit any employee or customer of the Company with whom the Employee had material contact during the last twelve (12) months of employment.",
           prompt="Check non-solicitation scope and duration. Flag if >12 months or unreasonably broad.", order=3),
        _r("ip_assignment_work_for_hire",
           "Work-for-hire IP assignment is standard for employees. Flag if it extends to personal projects created outside work hours.",
           "yellow",
           [r"(?i)\b(work(s)?\s+for\s+hire)\b", r"(?i)\b(intellectual\s+property\s+assign(ment)?)\b",
            r"(?i)\b(invention(s)?\s+assign(ment)?)\b", r"(?i)\b(all\s+work\s+product)\b",
            r"(?i)\b(company\s+(owns?|property)\s+(all\s+)?IP)\b"],
           "All intellectual property created by the Employee in the course of employment and using Company resources shall be the exclusive property of the Company. This does not apply to inventions or works created entirely on the Employee's own time without use of Company resources and unrelated to Company business.",
           prompt="Check if IP assignment covers personal projects outside work hours. Flag if it extends beyond work scope.", order=4),
        _r("confidentiality",
           "Post-termination confidentiality should be limited to 2 years.",
           "yellow",
           [r"(?i)\b(confidential(ity)?\s+(obligation|clause))\b",
            r"(?i)\b(perpetual\s+confidentiality)\b",
            r"(?i)\b(non[\s-]?disclosure)\b"],
           "The Employee shall maintain confidentiality of Company's proprietary information during employment and for a period of two (2) years following termination.",
           prompt="Check confidentiality term. Flag if perpetual. Acceptable: 2 years post-termination.", order=5),
        _r("termination_for_cause",
           "Must list specific grounds for termination for cause.",
           "yellow",
           [r"(?i)\b(terminat(e|ion)\s+for\s+cause)\b", r"(?i)\b(summary\s+(termination|dismissal))\b",
            r"(?i)\b(grounds\s+for\s+(termination|dismissal))\b"],
           "The Company may terminate employment for cause including: (a) material breach of this Agreement; (b) gross misconduct or negligence; (c) conviction of a criminal offence; (d) fraud or dishonesty; (e) persistent failure to perform duties after written warning.",
           prompt="Check if termination for cause lists specific grounds. Flag if vague or entirely discretionary.", order=6),
        _r("termination_by_employee",
           "Employee should have the right to resign with reasonable notice.",
           "green",
           [r"(?i)\b(resign(ation)?)\b", r"(?i)\b(employee\s+may\s+terminate)\b",
            r"(?i)\b(voluntary\s+termination)\b"],
           "The Employee may resign from employment by providing the notice period specified herein or payment of salary in lieu of notice.",
           prompt="Check if employee has reasonable resignation rights. Flag if overly restrictive.", order=7),
        _r("garden_leave",
           "Garden leave should not exceed 3 months.",
           "yellow",
           [r"(?i)\b(garden\s+leave)\b", r"(?i)\b(paid\s+leave\s+during\s+notice)\b"],
           "During the notice period, the Company may place the Employee on garden leave for up to three (3) months, during which the Employee shall receive full salary and benefits but shall not be required to attend the workplace.",
           prompt="Check garden leave duration. Flag if >3 months.", order=8),
        _r("restrictive_covenants_scope",
           "Geographic and temporal scope of restrictive covenants must be reasonable.",
           "red",
           [r"(?i)\b(restrictive\s+covenant)\b", r"(?i)\b(worldwide|global)\s+(restriction|prohibition)\b",
            r"(?i)\b(anywhere\s+in\s+the\s+world)\b",
            r"(?i)\b(any\s+(geographic|territor))\b"],
           "Any restrictive covenants shall be limited to the specific geographic territory where the Employee operated and for a maximum period of twelve (12) months. Worldwide or unreasonable geographic restrictions are unenforceable.",
           deal_breaker=True,
           prompt="Check geographic and temporal scope of restrictive covenants. Flag worldwide restrictions or duration >12 months.", order=9),
        _r("bonus_variable_pay",
           "Bonus/variable pay criteria should be clearly defined, not entirely discretionary.",
           "yellow",
           [r"(?i)\b(bonus|variable\s+pay|incentive)\b", r"(?i)\b(discretionary\s+bonus)\b",
            r"(?i)\b(performance\s+(bonus|incentive))\b"],
           "The Employee shall be eligible for an annual performance bonus based on achievement of key performance indicators (KPIs) as communicated at the beginning of each performance cycle. Target bonus: [X]% of annual CTC.",
           prompt="Check if bonus criteria are defined. Flag if entirely discretionary with no criteria.", order=10),
        _r("governing_law",
           "Must be Indian law for Indian employees.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b"],
           "This Agreement shall be governed by the laws of India and the applicable state-specific Shops and Establishments Act.",
           prompt="Must be Indian law for Indian employment.", order=11),
    ],
}
