"""Fintech Industry — MSA + RBI/DPDP compliance playbook."""
from scripts.playbooks._helpers import _r

FINTECH = {
    "name": "Fintech Services Agreement (India)",
    "description": "Industry playbook for fintech companies in India. Covers RBI data localization, PPI guidelines, DPDP Act compliance, and financial services-specific risks.",
    "category": "MSA",
    "party_side": "buyer",
    "version": 2,
    "rules": [
        _r("rbi_data_localization",
           "For an entity and system within the RBI payment-data storage circular, keep the complete end-to-end transaction data in India and assess the circular's treatment of any foreign transaction leg; do not extend the rule to every fintech dataset.",
           "red",
           [r"(?i)\b(data\s+local[iz]ation)\b", r"(?i)\b(payment\s+(system\s+)?data)\b",
            r"(?i)\b(store[d]?\s+(in|within)\s+india)\b", r"(?i)\b(RBI\s+circular)\b"],
           "To the extent RBI Circular DPSS.CO.OD.No.2785/06.08.005/2017-18 applies to the services, the Provider shall store the complete end-to-end payment-system transaction data in India and comply with the circular and current RBI clarifications concerning any foreign transaction leg.",
           deal_breaker=True, order=0,
           risk_description="Applicable payment-system data is stored or mirrored contrary to the RBI circular, or the clause fails to identify covered systems and foreign transaction legs",
           unacceptable_signals=["stored internationally", "global data center", "cross-border storage"],
           acceptable_signals=["stored in India", "Indian data center", "RBI compliant"]),
        _r("ppi_guidelines",
           "Where the service involves a regulated prepaid payment instrument, allocate the current RBI PPI Master Direction duties applicable to that PPI type, including KYC and interoperability where triggered.",
           "yellow",
           [r"(?i)\b(pre-?paid\s+instrument|PPI)\b", r"(?i)\b(wallet|stored\s+value)\b",
            r"(?i)\b(KYC|know\s+your\s+customer)\b"],
           order=1,
           risk_description="PPI operations without adequate KYC or interoperability compliance"),
        _r("data_protection_dpdp",
           "Where the DPDP Act applies and the relevant provisions have commenced, allocate lawful-purpose, notice/consent or legitimate-use, rights, security, processor, retention, and breach support obligations.",
           "red",
           [r"(?i)\b(personal\s+data|data\s+protection)\b", r"(?i)\b(DPDP|Digital\s+Personal\s+Data)\b",
            r"(?i)\b(consent|data\s+fiduciary)\b"],
           deal_breaker=True, order=2,
           risk_description="Personal-data terms omit applicable DPDP duties or assume every provision is already in force regardless of phased commencement"),
        _r("outsourcing_guidelines",
           "Identify the regulated entity and apply the current RBI outsourcing direction or guideline that governs that entity and service; do not rely on a generic or superseded label.",
           "yellow",
           [r"(?i)\b(outsourc[eing]+)\b", r"(?i)\b(third.party\s+service)\b",
            r"(?i)\b(vendor\s+management)\b"],
           order=3,
           risk_description="Technology outsourcing without RBI outsourcing risk framework"),
        _r("grievance_redressal",
           "Where the regulated entity and product fall within the RBI complaint and Ombudsman framework, preserve the entity's grievance process, escalation, records, and regulatory cooperation.",
           "yellow",
           [r"(?i)\b(grievance|complaint|ombudsman)\b", r"(?i)\b(redress[al]*)\b"],
           order=4,
           risk_description="Missing customer grievance mechanism per RBI guidelines"),
        _r("cyber_security",
           "Apply the current cyber and incident requirements for the specific RBI-regulated entity, and separately support CERT-In reporting within six hours for incidents covered by the 2022 Directions.",
           "red",
           [r"(?i)\b(cyber\s*security)\b", r"(?i)\b(VAPT|penetration\s+test)\b",
            r"(?i)\b(incident\s+report)\b", r"(?i)\b(CSITE|CERT-?In)\b"],
           order=5,
           risk_description="Cyber controls or incident escalation do not match the regulated entity, covered incident, or applicable reporting clock"),
        _r("limitation_of_liability",
           "Negotiate an appropriate base cap and targeted super-cap or carve-outs for IP, confidentiality, security, fraud, and lawfully allocable regulatory exposure; twelve months of fees is a commercial benchmark, not a legal ceiling.",
           "yellow",
           [r"(?i)\b(limit[ation]*\s+of\s+liability)\b", r"(?i)\b(aggregate\s+liability)\b",
            r"(?i)\b(liability\s+cap)\b"],
           order=6,
           risk_description="Liability allocation is commercially disproportionate or fails to address material fintech, security, IP, and regulatory risks"),
        _r("audit_rights",
           "Preserve customer, auditor, and regulator access to the extent required by the applicable RBI outsourcing regime, with workable evidence, remediation, confidentiality, and business-continuity terms.",
           "yellow",
           [r"(?i)\b(audit\s+right)\b", r"(?i)\b(regulator[y]?\s+audit)\b",
            r"(?i)\b(inspection\s+right)\b"],
           order=7,
           risk_description="Missing audit rights for client or regulatory inspection"),
    ],
}
