"""Fintech Industry — MSA + RBI/DPDP compliance playbook."""
from scripts.playbooks._helpers import _r

FINTECH = {
    "name": "Fintech Services Agreement (India)",
    "description": "Industry playbook for fintech companies in India. Covers RBI data localization, PPI guidelines, DPDP Act compliance, and financial services-specific risks.",
    "category": "MSA",
    "party_side": "buyer",
    "rules": [
        _r("rbi_data_localization",
           "All payment system data must be stored exclusively in India per RBI circular on Storage of Payment System Data (April 2018).",
           "red",
           [r"(?i)\b(data\s+local[iz]ation)\b", r"(?i)\b(payment\s+(system\s+)?data)\b",
            r"(?i)\b(store[d]?\s+(in|within)\s+india)\b", r"(?i)\b(RBI\s+circular)\b"],
           "All payment system data, including full end-to-end transaction details, shall be stored exclusively within the territory of India in compliance with RBI Circular DPSS.CO.OD.No.2785/06.08.005/2017-18.",
           deal_breaker=True, order=0,
           risk_description="Payment data storage outside India violates RBI mandate",
           unacceptable_signals=["stored internationally", "global data center", "cross-border storage"],
           acceptable_signals=["stored in India", "Indian data center", "RBI compliant"]),
        _r("ppi_guidelines",
           "Pre-paid instruments must comply with RBI PPI Master Directions including KYC and interoperability requirements.",
           "yellow",
           [r"(?i)\b(pre-?paid\s+instrument|PPI)\b", r"(?i)\b(wallet|stored\s+value)\b",
            r"(?i)\b(KYC|know\s+your\s+customer)\b"],
           order=1,
           risk_description="PPI operations without adequate KYC or interoperability compliance"),
        _r("data_protection_dpdp",
           "Processing of personal data must comply with DPDP Act 2023: consent, purpose limitation, data fiduciary obligations.",
           "red",
           [r"(?i)\b(personal\s+data|data\s+protection)\b", r"(?i)\b(DPDP|Digital\s+Personal\s+Data)\b",
            r"(?i)\b(consent|data\s+fiduciary)\b"],
           deal_breaker=True, order=2,
           risk_description="Non-compliance with DPDP Act 2023 data fiduciary obligations"),
        _r("outsourcing_guidelines",
           "Technology outsourcing must comply with RBI Guidelines on Managing Risks and Code of Conduct in Outsourcing of Financial Services.",
           "yellow",
           [r"(?i)\b(outsourc[eing]+)\b", r"(?i)\b(third.party\s+service)\b",
            r"(?i)\b(vendor\s+management)\b"],
           order=3,
           risk_description="Technology outsourcing without RBI outsourcing risk framework"),
        _r("grievance_redressal",
           "Customer grievance redressal mechanism must be established per RBI Integrated Ombudsman Scheme 2021.",
           "yellow",
           [r"(?i)\b(grievance|complaint|ombudsman)\b", r"(?i)\b(redress[al]*)\b"],
           order=4,
           risk_description="Missing customer grievance mechanism per RBI guidelines"),
        _r("cyber_security",
           "Cyber security framework per RBI CSITE guidelines. Annual VAPT, incident reporting within 6 hours.",
           "red",
           [r"(?i)\b(cyber\s*security)\b", r"(?i)\b(VAPT|penetration\s+test)\b",
            r"(?i)\b(incident\s+report)\b", r"(?i)\b(CSITE|CERT-?In)\b"],
           order=5,
           risk_description="Missing cybersecurity framework or incident reporting obligations"),
        _r("limitation_of_liability",
           "Liability cap should not exceed 12 months of fees. Carve-outs for data breach, IP infringement, regulatory fines.",
           "yellow",
           [r"(?i)\b(limit[ation]*\s+of\s+liability)\b", r"(?i)\b(aggregate\s+liability)\b",
            r"(?i)\b(liability\s+cap)\b"],
           order=6,
           risk_description="Unlimited liability or missing carve-outs for regulatory fines"),
        _r("audit_rights",
           "Client and RBI/regulators must have audit rights over service provider's systems and processes.",
           "yellow",
           [r"(?i)\b(audit\s+right)\b", r"(?i)\b(regulator[y]?\s+audit)\b",
            r"(?i)\b(inspection\s+right)\b"],
           order=7,
           risk_description="Missing audit rights for client or regulatory inspection"),
    ],
}
