"""Healthcare Industry — Vendor agreement + sensitive personal data playbook."""
from scripts.playbooks._helpers import _r

HEALTHCARE = {
    "name": "Healthcare Vendor Agreement (India)",
    "description": "Industry playbook for healthcare vendor agreements in India. Covers sensitive personal data under IT Act, DPDP Act compliance, CDSCO/regulatory requirements, and patient data handling.",
    "category": "VENDOR",
    "party_side": "buyer",
    "rules": [
        _r("sensitive_personal_data",
           "Processing of sensitive personal data (health records, biometric data) requires explicit written consent per IT Act 2000 SPDI Rules and DPDP Act 2023.",
           "red",
           [r"(?i)\b(sensitive\s+personal\s+data|health\s+record|patient\s+data)\b",
            r"(?i)\b(medical\s+record|clinical\s+data)\b", r"(?i)\b(biometric)\b"],
           deal_breaker=True, order=0,
           risk_description="Processing health/sensitive data without explicit consent or SPDI compliance"),
        _r("data_breach_notification",
           "Data breach involving patient data must be notified within 72 hours per DPDP Act 2023 and CERT-In Directions 2022 (6 hours for cyber incidents).",
           "red",
           [r"(?i)\b(data\s+breach|security\s+incident)\b", r"(?i)\b(breach\s+notif)\b",
            r"(?i)\b(CERT-?In)\b"],
           deal_breaker=True, order=1,
           risk_description="Missing mandatory breach notification timelines"),
        _r("cdsco_compliance",
           "Medical device/pharma vendors must comply with CDSCO regulations, Medical Devices Rules 2017.",
           "yellow",
           [r"(?i)\b(CDSCO|Central\s+Drugs)\b", r"(?i)\b(medical\s+device)\b",
            r"(?i)\b(Drug.*Controller)\b", r"(?i)\b(pharmaceutical)\b"],
           order=2,
           risk_description="Vendor not acknowledging CDSCO regulatory requirements"),
        _r("clinical_trial_data",
           "Clinical trial data handling must comply with ICMR National Ethical Guidelines and New Drugs and Clinical Trials Rules 2019.",
           "yellow",
           [r"(?i)\b(clinical\s+trial)\b", r"(?i)\b(ICMR|Indian\s+Council\s+of\s+Medical)\b",
            r"(?i)\b(trial\s+data)\b"],
           order=3,
           risk_description="Clinical trial data handling without ICMR/ethics committee oversight"),
        _r("data_retention_healthcare",
           "Patient records must be retained per Clinical Establishments Act 2010 and state-specific rules. Minimum 3-5 years.",
           "yellow",
           [r"(?i)\b(data\s+retention|record\s+retention)\b", r"(?i)\b(retention\s+period)\b",
            r"(?i)\b(destroy|delete|purge).*\b(record|data)\b"],
           order=4,
           risk_description="Data retention period shorter than regulatory minimum for healthcare records"),
        _r("hipaa_interop",
           "For cross-border health data (esp. US clients), ensure HIPAA BAA provisions are included if applicable.",
           "yellow",
           [r"(?i)\b(HIPAA)\b", r"(?i)\b(Business\s+Associate\s+Agreement|BAA)\b",
            r"(?i)\b(protected\s+health\s+information|PHI)\b"],
           order=5,
           risk_description="Cross-border health data without HIPAA Business Associate Agreement"),
        _r("indemnification_healthcare",
           "Indemnification should include carve-outs for patient harm, regulatory fines, and data breaches. S.74 ICA ceiling applies.",
           "yellow",
           [r"(?i)\b(indemnif[ication]*)\b", r"(?i)\b(hold\s+harmless)\b"],
           order=6,
           risk_description="Missing indemnification carve-outs for patient harm or regulatory penalties"),
        _r("insurance_requirements",
           "Vendor must maintain professional liability / medical malpractice insurance with adequate coverage.",
           "yellow",
           [r"(?i)\b(insurance|professional\s+liability)\b", r"(?i)\b(malpractice)\b",
            r"(?i)\b(errors?\s+and\s+omissions|E&O)\b"],
           order=7,
           risk_description="Missing professional liability insurance requirement"),
    ],
}
