"""Healthcare Industry — Vendor agreement + sensitive personal data playbook."""
from scripts.playbooks._helpers import _r

HEALTHCARE = {
    "name": "Healthcare Vendor Agreement (India)",
    "description": "India healthcare vendor playbook. Every health, clinical-trial, device, retention, CERT-In, and overseas-health rule is applicability-gated; negotiated safeguards are not labelled as universal statutory terms.",
    "category": "VENDOR",
    "party_side": "buyer",
    "version": 2,
    "rules": [
        _r("sensitive_personal_data",
           "Identify the operative privacy regime and lawful basis for health and biometric data. The SPDI Rules may require written consent while applicable; the DPDP Act does not create a separate sensitive-data category or make consent the only lawful basis.",
           "red",
           [r"(?i)\b(sensitive\s+personal\s+data|health\s+record|patient\s+data)\b",
            r"(?i)\b(medical\s+record|clinical\s+data)\b", r"(?i)\b(biometric)\b"],
           deal_breaker=True, order=0,
           risk_description="Health or biometric processing lacks a valid, applicable legal basis, notice, purpose control, or required SPDI safeguard"),
        _r("data_breach_notification",
           "Set immediate internal escalation. Under DPDP Rule 7, affected-principal and initial Board notices are without delay and specified Board details follow within 72 hours unless extended; specified CERT-In incidents have a separate six-hour clock.",
           "red",
           [r"(?i)\b(data\s+breach|security\s+incident)\b", r"(?i)\b(breach\s+notif)\b",
            r"(?i)\b(CERT-?In)\b"],
           deal_breaker=True, order=1,
           risk_description="Incident clause cannot support applicable DPDP staged notices or the separate CERT-In clock for specified incidents"),
        _r("cdsco_compliance",
           "Medical device/pharma vendors must comply with CDSCO regulations, Medical Devices Rules 2017.",
           "yellow",
           [r"(?i)\b(CDSCO|Central\s+Drugs)\b", r"(?i)\b(medical\s+device)\b",
            r"(?i)\b(Drug.*Controller)\b", r"(?i)\b(pharmaceutical)\b"],
           order=2,
           risk_description="Vendor not acknowledging CDSCO regulatory requirements"),
        _r("clinical_trial_data",
           "Clinical trial data handling must comply with ICMR National Ethical Guidelines and New Drugs and Clinical Trials Rules 2019.",
           "yellow",
           [r"(?i)\b(clinical\s+trial)\b", r"(?i)\b(ICMR|Indian\s+Council\s+of\s+Medical)\b",
            r"(?i)\b(trial\s+data)\b"],
           order=3,
           risk_description="Clinical trial data handling without ICMR/ethics committee oversight"),
        _r("data_retention_healthcare",
           "Map each record category, establishment type, clinical use, and jurisdiction to its actual retention rule; do not apply one blanket 3-5 year period to all patient data.",
           "yellow",
           [r"(?i)\b(data\s+retention|record\s+retention)\b", r"(?i)\b(retention\s+period)\b",
            r"(?i)\b(destroy|delete|purge).*\b(record|data)\b"],
           order=4,
           risk_description="Retention is not mapped to the applicable record category and regulator, or conflicts with required erasure and legal-hold duties"),
        _r("hipaa_interop",
           "Require HIPAA Business Associate terms only when the parties and processing fall within HIPAA, not merely because data or a customer has a US connection.",
           "yellow",
           [r"(?i)\b(HIPAA)\b", r"(?i)\b(Business\s+Associate\s+Agreement|BAA)\b",
            r"(?i)\b(protected\s+health\s+information|PHI)\b"],
           order=5,
           risk_description="HIPAA-covered processing lacks required Business Associate terms, or HIPAA is asserted without a covered-entity/business-associate analysis"),
        _r("indemnification_healthcare",
           "Negotiate causation-based coverage for patient harm, privacy breaches, and lawfully recoverable regulatory exposure, coordinated with the liability cap and Indian Contract Act remedies.",
           "yellow",
           [r"(?i)\b(indemnif[ication]*)\b", r"(?i)\b(hold\s+harmless)\b"],
           order=6,
           risk_description="Healthcare-specific losses and third-party claims are not coherently allocated with the liability cap, causation standard, and applicable law"),
        _r("insurance_requirements",
           "Require professional, cyber, product, or medical-malpractice insurance only to the extent appropriate to the vendor's actual services and exposure.",
           "yellow",
           [r"(?i)\b(insurance|professional\s+liability)\b", r"(?i)\b(malpractice)\b",
            r"(?i)\b(errors?\s+and\s+omissions|E&O)\b"],
           order=7,
           risk_description="Missing professional liability insurance requirement"),
    ],
}
