"""IT Services Industry — MSA + IT Act/CERT-In/SOC2 compliance playbook."""
from scripts.playbooks._helpers import _r

IT_SERVICES = {
    "name": "IT Services Agreement (India)",
    "description": "Industry playbook for IT/ITES service agreements in India. Covers IT Act 2000, CERT-In Directions, SOC2/ISO27001 requirements, STPI/SEZ compliance, and data handling for outsourcing.",
    "category": "MSA",
    "party_side": "buyer",
    "rules": [
        _r("it_act_compliance",
           "Services involving electronic contracts/communications must comply with IT Act 2000 and IT (Reasonable Security Practices) Rules 2011.",
           "yellow",
           [r"(?i)\b(information\s+technology\s+act|IT\s+Act)\b",
            r"(?i)\b(electronic\s+contract|digital\s+signature)\b",
            r"(?i)\b(reasonable\s+security\s+practice)\b"],
           order=0,
           risk_description="Missing IT Act 2000 compliance for electronic contracts"),
        _r("certin_incident_reporting",
           "Cyber security incidents must be reported to CERT-In within 6 hours per CERT-In Directions 2022.",
           "red",
           [r"(?i)\b(CERT-?In)\b", r"(?i)\b(cyber\s+(?:security\s+)?incident)\b",
            r"(?i)\b(incident\s+report)\b", r"(?i)\b(6\s*hours?)\b"],
           deal_breaker=True, order=1,
           risk_description="Missing mandatory 6-hour CERT-In incident reporting obligation"),
        _r("soc2_iso27001",
           "Service provider should maintain SOC2 Type II or ISO 27001 certification. Annual re-certification required.",
           "yellow",
           [r"(?i)\b(SOC\s*2|SOC\s*II)\b", r"(?i)\b(ISO\s*27001)\b",
            r"(?i)\b(security\s+certification|compliance\s+certification)\b"],
           order=2,
           risk_description="Missing SOC2/ISO27001 security certification requirement"),
        _r("data_protection_it",
           "Personal data processing must comply with DPDP Act 2023. Include data processing agreement with roles (fiduciary vs processor).",
           "red",
           [r"(?i)\b(personal\s+data|data\s+process)\b", r"(?i)\b(DPDP|data\s+fiduciary)\b",
            r"(?i)\b(data\s+processor|data\s+processing\s+agreement)\b"],
           deal_breaker=True, order=3,
           risk_description="Missing data processing agreement or DPDP Act compliance"),
        _r("ip_ownership",
           "IP developed under the agreement should be clearly assigned. Pre-existing IP must be licensed. Work-for-hire provisions should be explicit.",
           "yellow",
           [r"(?i)\b(intellectual\s+property|IP\s+right)\b", r"(?i)\b(work.for.hire)\b",
            r"(?i)\b(IP\s+ownership|copyright\s+assign)\b"],
           order=4,
           risk_description="Ambiguous IP ownership or missing work-for-hire provisions"),
        _r("sla_penalties",
           "SLAs must have measurable metrics (uptime, response time) with service credits for breach. Minimum 99.5% uptime for critical services.",
           "yellow",
           [r"(?i)\b(SLA|service\s+level)\b", r"(?i)\b(uptime|availability)\b",
            r"(?i)\b(service\s+credit)\b", r"(?i)\b(response\s+time|resolution\s+time)\b"],
           order=5,
           risk_description="SLAs without measurable metrics or penalty mechanisms"),
        _r("business_continuity",
           "Service provider must have documented BCP/DR plan. RPO/RTO must be defined. Annual DR drill required.",
           "yellow",
           [r"(?i)\b(business\s+continuity|BCP)\b", r"(?i)\b(disaster\s+recovery|DR\s+plan)\b",
            r"(?i)\b(RPO|RTO)\b"],
           order=6,
           risk_description="Missing BCP/DR plan or RPO/RTO definitions"),
        _r("transition_assistance",
           "Contract must include transition assistance clause (minimum 90 days) for service handover at expiry or termination.",
           "yellow",
           [r"(?i)\b(transition\s+assist)\b", r"(?i)\b(hand.?over|migration\s+assist)\b",
            r"(?i)\b(exit\s+plan|exit\s+management)\b"],
           order=7,
           risk_description="Missing transition assistance clause for service handover"),
        _r("subcontracting",
           "Subcontracting must require prior written consent. Primary contractor remains liable. Subcontractor must meet same compliance standards.",
           "yellow",
           [r"(?i)\b(sub.?contract)\b", r"(?i)\b(sub.?process)\b",
            r"(?i)\b(third.party\s+service\s+provider)\b"],
           order=8,
           risk_description="Unrestricted subcontracting without client consent or compliance flow-down"),
    ],
}
