"""IT Services Industry — MSA + IT Act/CERT-In/SOC2 compliance playbook."""
from scripts.playbooks._helpers import _r

IT_SERVICES = {
    "name": "IT Services Agreement (India)",
    "description": "Industry playbook for IT/ITES service agreements in India. Covers IT Act 2000, CERT-In Directions, SOC2/ISO27001 requirements, STPI/SEZ compliance, and data handling for outsourcing.",
    "category": "MSA",
    "party_side": "buyer",
    "version": 2,
    "rules": [
        _r("it_act_compliance",
           "Services involving electronic contracts/communications must comply with IT Act 2000 and IT (Reasonable Security Practices) Rules 2011.",
           "yellow",
           [r"(?i)\b(information\s+technology\s+act|IT\s+Act)\b",
            r"(?i)\b(electronic\s+contract|digital\s+signature)\b",
            r"(?i)\b(reasonable\s+security\s+practice)\b"],
           order=0,
           risk_description="Missing IT Act 2000 compliance for electronic contracts"),
        _r("certin_incident_reporting",
           "For incidents within CERT-In's specified reportable categories, support the covered entity's six-hour reporting clock with a shorter internal processor-to-customer notice and rolling details.",
           "red",
           [r"(?i)\b(CERT-?In)\b", r"(?i)\b(cyber\s+(?:security\s+)?incident)\b",
            r"(?i)\b(incident\s+report)\b", r"(?i)\b(6\s*hours?)\b"],
           deal_breaker=True, order=1,
           risk_description="Incident terms cannot support six-hour CERT-In reporting when the incident and entity are covered, or incorrectly apply that clock to every event"),
        _r("soc2_iso27001",
           "Require current independent assurance appropriate to the service, such as SOC 2 Type II or ISO 27001, with renewal and material-exception reporting matched to the selected framework.",
           "yellow",
           [r"(?i)\b(SOC\s*2|SOC\s*II)\b", r"(?i)\b(ISO\s*27001)\b",
            r"(?i)\b(security\s+certification|compliance\s+certification)\b"],
           order=2,
           risk_description="Missing SOC2/ISO27001 security certification requirement"),
        _r("data_protection_it",
           "Where personal data is processed, identify fiduciary/processor roles and use clear processing terms to support applicable DPDP obligations; do not claim the Act prescribes a document titled DPA.",
           "red",
           [r"(?i)\b(personal\s+data|data\s+process)\b", r"(?i)\b(DPDP|data\s+fiduciary)\b",
            r"(?i)\b(data\s+processor|data\s+processing\s+agreement)\b"],
           deal_breaker=True, order=3,
           risk_description="Roles, instructions, safeguards, rights support, retention, or breach cooperation are missing for applicable personal-data processing"),
        _r("ip_ownership",
           "IP developed under the agreement should be clearly assigned. Pre-existing IP must be licensed. Work-for-hire provisions should be explicit.",
           "yellow",
           [r"(?i)\b(intellectual\s+property|IP\s+right)\b", r"(?i)\b(work.for.hire)\b",
            r"(?i)\b(IP\s+ownership|copyright\s+assign)\b"],
           order=4,
           risk_description="Ambiguous IP ownership or missing work-for-hire provisions"),
        _r("sla_penalties",
           "Use measurable, service-specific SLAs and meaningful remedies. A 99.5% target is a negotiation baseline, not a universal legal minimum.",
           "yellow",
           [r"(?i)\b(SLA|service\s+level)\b", r"(?i)\b(uptime|availability)\b",
            r"(?i)\b(service\s+credit)\b", r"(?i)\b(response\s+time|resolution\s+time)\b"],
           order=5,
           risk_description="SLAs without measurable metrics or penalty mechanisms"),
        _r("business_continuity",
           "Require a documented and tested BCP/DR plan with service-specific RPO/RTO and evidence appropriate to criticality; annual testing is a negotiated control unless a specific regime requires it.",
           "yellow",
           [r"(?i)\b(business\s+continuity|BCP)\b", r"(?i)\b(disaster\s+recovery|DR\s+plan)\b",
            r"(?i)\b(RPO|RTO)\b"],
           order=6,
           risk_description="Missing BCP/DR plan or RPO/RTO definitions"),
        _r("transition_assistance",
           "Negotiate transition assistance, data/knowledge return, access continuity, pricing, and duration based on switching complexity; ninety days is a commercial baseline, not a statutory minimum.",
           "yellow",
           [r"(?i)\b(transition\s+assist)\b", r"(?i)\b(hand.?over|migration\s+assist)\b",
            r"(?i)\b(exit\s+plan|exit\s+management)\b"],
           order=7,
           risk_description="Missing transition assistance clause for service handover"),
        _r("subcontracting",
           "Use notice or consent, responsibility, and obligation flow-down controls appropriate to the service and applicable regulatory regime; prior written consent is a client position, not universal law.",
           "yellow",
           [r"(?i)\b(sub.?contract)\b", r"(?i)\b(sub.?process)\b",
            r"(?i)\b(third.party\s+service\s+provider)\b"],
           order=8,
           risk_description="Unrestricted subcontracting without client consent or compliance flow-down"),
    ],
}
