"""Joint Venture / Partnership Agreement — Default playbook."""
from scripts.playbooks._helpers import _r  # noqa: F401

JOINT_VENTURE = {
    "name": "Joint Venture / Partnership Agreement",
    "description": "Default playbook for joint ventures and partnerships. Covers profit sharing, governance, capital contributions, IP, exit mechanisms, deadlock resolution, and dissolution under Indian law.",
    "category": "CUSTOM",
    "rules": [
        _r("profit_loss_sharing",
           "Profit/loss sharing must be proportionate to investment/effort. Flag disproportionate allocations.",
           "red",
           [r"(?i)\b(profit\s+(and\s+loss\s+)?(sharing|distribution|allocation))\b",
            r"(?i)\b(share\s+of\s+(profits?|losses?))\b",
            r"(?i)\b(distribution\s+of\s+(profits?|income|revenue))\b"],
           "Profits and losses of the Joint Venture shall be shared between the Parties in proportion to their respective capital contributions, unless otherwise agreed in writing. Distributions shall be made quarterly after provision for working capital and reserves.",
           deal_breaker=True,
           prompt="Check profit/loss sharing ratio. Flag if disproportionate to capital contribution or effort without justification.", order=0,
           detection_mode="ai_with_keywords",
           risk_description="Profit/loss distribution disproportionate to capital contribution or effort",
           unacceptable_signals=["losses borne solely by", "disproportionate distribution", "profits at managing partner's discretion"],
           acceptable_signals=["proportionate to capital contribution", "defined formula"],
           acceptable_position="Sharing proportionate to capital contribution, with defined formula"),
        _r("governance_decision_making",
           "Governance must be balanced. Flag if one party has unilateral control over key decisions.",
           "red",
           [r"(?i)\b(governance|management\s+committee|board\s+of\s+directors)\b",
            r"(?i)\b(decision[\s-]?making)\b", r"(?i)\b(voting\s+rights?)\b",
            r"(?i)\b(unilateral\s+(control|decision|authority))\b"],
           "The JV shall be managed by a Management Committee with equal representation from each Party. Key decisions (capital expenditure >INR [X], new contracts >INR [Y], changes to business plan, admission of new partners) shall require unanimous consent.",
           deal_breaker=True,
           prompt="Check governance structure. Flag if one party has unilateral decision-making power over key matters.", order=1,
           detection_mode="ai_with_keywords",
           risk_description="One party has unilateral control over JV decisions",
           unacceptable_signals=["sole discretion of managing partner", "unilateral decision-making", "no minority protection"],
           acceptable_signals=["unanimous consent for major decisions", "board representation proportionate to shareholding"],
           acceptable_position="Proportionate board representation; major decisions require unanimous consent"),
        _r("capital_contribution",
           "Capital contributions must be clearly defined with timelines and consequences for default.",
           "yellow",
           [r"(?i)\b(capital\s+contribution)\b", r"(?i)\b(investment\s+(amount|obligation))\b",
            r"(?i)\b(initial\s+(capital|investment))\b"],
           "Each Party shall contribute capital as set forth in Schedule [X]. Additional capital calls require unanimous consent. A Party failing to meet a capital call within thirty (30) days shall suffer dilution of its ownership interest proportionate to the shortfall.",
           prompt="Check if capital contributions are clearly defined. Flag if amounts or timelines are missing.", order=2),
        _r("ip_ownership",
           "JV-created IP ownership must be clearly allocated. Flag if one party takes all JV IP.",
           "red",
           [r"(?i)\b(intellectual\s+property\s+(of\s+the\s+)?(JV|joint\s+venture|partnership))\b",
            r"(?i)\b(JV[\s-]?(created|developed)\s+IP)\b",
            r"(?i)\b(ownership\s+of\s+(joint|shared)\s+IP)\b"],
           "IP created by the JV shall be jointly owned by the Parties in proportion to their equity shares. Each Party retains exclusive ownership of its pre-existing IP. Upon dissolution, JV IP shall be licensed non-exclusively to each Party for continued use.",
           deal_breaker=True,
           prompt="Check JV IP ownership. Flag if one party takes all JV-created IP without fair allocation.", order=3,
           detection_mode="ai_with_keywords",
           risk_description="One party takes all JV-created IP regardless of contribution",
           unacceptable_signals=["all JV IP belongs to Party A", "sole ownership regardless of contribution"],
           acceptable_signals=["jointly owned IP", "IP allocated based on contribution"],
           acceptable_position="JV-created IP jointly owned; allocation based on contribution for domain-specific work"),
        _r("non_compete_between_partners",
           "Non-compete between JV partners should be reasonable in scope and duration.",
           "yellow",
           [r"(?i)\b(non[\s-]?compete).{0,60}(partner|party|venture)\b",
            r"(?i)\b(shall\s+not\s+(directly\s+or\s+indirectly\s+)?compete)\b",
            r"(?i)\b(exclusivity\s+between\s+(the\s+)?parties)\b"],
           "During the term of this Agreement, neither Party shall directly or indirectly engage in any business that competes with the JV's business within the defined territory. This restriction shall not apply to pre-existing businesses of either Party.",
           prompt="Check scope of non-compete between partners. Flag if too broad or extends post-dissolution.", order=4),
        _r("exit_buyout_mechanism",
           "Exit/buy-out mechanism is essential. Missing exit clause is a deal-breaker.",
           "red",
           [r"(?i)\b(exit\s+(mechanism|clause|strategy))\b", r"(?i)\b(buy[\s-]?out)\b",
            r"(?i)\b(right\s+of\s+first\s+refusal|ROFR)\b", r"(?i)\b(tag[\s-]?along|drag[\s-]?along)\b"],
           "A Party wishing to exit shall first offer its interest to the other Party at fair market value (Right of First Refusal). If not exercised within sixty (60) days, the exiting Party may sell to a third party on terms no more favorable than offered to the continuing Party. Tag-along and drag-along rights shall apply to third-party sales.",
           deal_breaker=True,
           prompt="Check if exit/buy-out mechanism exists. Flag if missing — this is a deal-breaker.", order=5,
           detection_mode="ai_with_keywords",
           risk_description="No exit mechanism or buy-out formula defined",
           unacceptable_signals=["no exit provision", "lock-in with no buyout", "no valuation mechanism"],
           acceptable_signals=["buy-out at fair market value", "independent valuation", "shotgun clause"],
           acceptable_position="Exit after 2-year lock-in at fair market value by independent valuer"),
        _r("deadlock_resolution",
           "Must have a deadlock resolution mechanism. Prefer arbitration or expert determination.",
           "yellow",
           [r"(?i)\b(deadlock\s+(resolution|mechanism|provision))\b",
            r"(?i)\b(dispute\s+between\s+(the\s+)?partners)\b",
            r"(?i)\b(impasse|stalemate)\b"],
           "In the event of a deadlock on any key decision, the Parties shall first attempt resolution through negotiation over thirty (30) days, then mediation over thirty (30) days, and finally binding arbitration under the Arbitration and Conciliation Act, 1996.",
           prompt="Check if deadlock resolution mechanism exists. Flag if missing.", order=6,
           detection_mode="ai_with_keywords",
           risk_description="No deadlock resolution mechanism for equal partnerships",
           unacceptable_signals=["no deadlock provision", "status quo prevails indefinitely"],
           acceptable_signals=["escalation to CEOs", "mediation followed by arbitration", "external mediator"],
           acceptable_position="3-tier: CEO escalation → mediation → arbitration under Indian Arbitration Act"),
        _r("confidentiality",
           "Mutual confidentiality between JV partners.",
           "yellow",
           [r"(?i)\b(confidential(ity)?)\b", r"(?i)\b(proprietary\s+information)\b"],
           "Each Party shall maintain confidentiality of the other Party's proprietary information and JV trade secrets during the term and for five (5) years following dissolution.",
           prompt="Check if confidentiality is mutual between partners.", order=7),
        _r("dissolution",
           "Must define dissolution process and asset distribution.",
           "yellow",
           [r"(?i)\b(dissolut(ion|e))\b", r"(?i)\b(winding\s+up)\b",
            r"(?i)\b(termination\s+of\s+(the\s+)?(JV|joint\s+venture|partnership))\b"],
           "Upon dissolution: (a) JV debts and liabilities shall be settled first; (b) remaining assets distributed in proportion to equity shares; (c) JV IP licensed to each Party; (d) non-compete obligations cease. Dissolution requires unanimous consent unless triggered by material breach or deadlock.",
           prompt="Check if dissolution process and asset distribution are defined. Flag if missing.", order=8),
        _r("governing_law",
           "Indian law.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b"],
           "This Agreement shall be governed by the laws of India, including the Indian Partnership Act, 1932 (if applicable).",
           prompt="Flag foreign jurisdiction.", order=9),
    ],
}
