"""Lease / License Agreement (Commercial Property) — Default playbook."""
from scripts.playbooks._helpers import _r  # noqa: F401

LEASE = {
    "name": "Lease / License Agreement (Commercial Property)",
    "description": "Default playbook for commercial property leases in India. Covers rent escalation, lock-in, security deposit, maintenance charges, early exit, permitted use, renewal, fit-out, and sub-letting.",
    "category": "CUSTOM",
    "rules": [
        _r("rent_escalation",
           "Rent shall escalate by 5% per annum on each anniversary of the Lease Commencement Date. Annual rent escalation should be 5-8% (Indian market standard).",
           "yellow",
           [r"(?i)\b(rent\s+(escalation|increase|revision|hike))\b",
            r"(?i)\b(annual\s+(increase|escalation)\s+of\s+\d+%)\b",
            r"(?i)\b(rent\s+shall\s+(increase|be\s+revised))\b"],
           fallback="The monthly rent shall escalate by 8% (eight percent) per annum.",
           prompt="Check rent escalation percentage. Flag if >10% annual increase. Indian standard is 5-8%.", order=0,
           detection_mode="ai_with_keywords",
           risk_description="Annual rent escalation exceeds 10% or is uncapped",
           unacceptable_signals=["15% annual escalation", "escalation at landlord discretion", "uncapped rent increase"],
           acceptable_signals=["5% annual escalation", "CPI-linked", "escalation every 2-3 years"],
           clause_context="Standard commercial rent escalation in India is 5-8% per annum",
           acceptable_position="5% annual or CPI (whichever lower), applied every 12 months"),
        _r("lock_in_period",
           "Lock-in period should not exceed 3 years. Flag >3 years with no exit option.",
           "red",
           [r"(?i)\b(lock[\s-]?in\s+(period|term))\b", r"(?i)\b(minimum\s+(lease\s+)?(term|period|tenure))\b",
            r"(?i)\b(cannot\s+(be\s+)?terminat(e|ed)\s+during)\b"],
           "The initial lock-in period shall be twenty-four (24) months from the Lease Commencement Date. During the lock-in period, neither Party may terminate this Lease except for material breach.",
           deal_breaker=True,
           prompt="Check lock-in duration. Flag if >3 years. Acceptable: 1-2 years for startups, up to 3 years for established businesses.", order=1,
           detection_mode="ai_with_keywords",
           risk_description="Lock-in exceeds 3 years with no early exit option",
           unacceptable_signals=["5 year lock-in", "no early exit", "entire remaining rent payable on early termination"],
           acceptable_signals=["1-2 year lock-in", "early exit with 3 months notice", "exit penalty capped at 3 months rent"],
           acceptable_position="Lock-in 1-2 years with break clause; exit penalty capped at 3 months rent"),
        _r("security_deposit",
           "Security deposit should be 3-6 months rent (Indian standard). Flag if >6 months.",
           "yellow",
           [r"(?i)\b(security\s+deposit)\b", r"(?i)\b(interest[\s-]?free\s+deposit)\b",
            r"(?i)\b(refundable\s+deposit)\b"],
           "The Lessee shall pay a refundable, interest-free security deposit equivalent to three (3) months' rent. The deposit shall be refunded within thirty (30) days of lease termination, subject to deduction for damages beyond normal wear and tear.",
           prompt="Check security deposit amount. Flag if >6 months rent. Indian standard: 3-6 months.", order=2),
        _r("maintenance_charges",
           "Common area maintenance charges must be defined and not subject to unlimited escalation.",
           "yellow",
           [r"(?i)\b(maintenance\s+(charge|cost|fee|expense))\b",
            r"(?i)\b(common\s+area\s+maintenance|CAM)\b",
            r"(?i)\b(operating\s+(cost|expense))\b"],
           "Common Area Maintenance (CAM) charges shall be INR [X] per sq. ft. per month, subject to annual escalation not exceeding 5%. Lessor shall provide itemized accounting of CAM charges annually.",
           prompt="Check if maintenance charges are defined. Flag if undefined, unlimited escalation, or no transparency.", order=3),
        _r("early_exit_termination",
           "Must have early exit clause after lock-in period. No exit clause = deal-breaker.",
           "red",
           [r"(?i)\b(early\s+(exit|termination))\b", r"(?i)\b(terminat(e|ion)\s+(after|post)\s+lock[\s-]?in)\b",
            r"(?i)\b(break\s+clause)\b", r"(?i)\b(premature\s+termination)\b"],
           "After the lock-in period, either Party may terminate this Lease by providing ninety (90) days' prior written notice. The Lessee shall not be liable for rent beyond the notice period. Security deposit shall be refunded per the terms herein.",
           deal_breaker=True,
           prompt="Check if early exit clause exists after lock-in. Flag if missing — this is a deal-breaker.", order=4,
           detection_mode="ai_with_keywords",
           risk_description="No early termination clause or exit requires full remaining rent",
           unacceptable_signals=["no early termination", "full remaining rent payable", "termination only by mutual consent"],
           acceptable_signals=["3 months notice for early exit", "penalty limited to security deposit", "break clause"],
           acceptable_position="Early exit with 3 months notice after lock-in; penalty limited to 3 months rent"),
        _r("permitted_use",
           "Permitted use must allow business operations. Flag restrictive use clauses.",
           "yellow",
           [r"(?i)\b(permitted\s+use)\b", r"(?i)\b(use\s+of\s+(the\s+)?(premises|property))\b",
            r"(?i)\b(purpose\s+of\s+(the\s+)?lease)\b"],
           "The Premises shall be used by the Lessee solely for [commercial office / IT services / co-working] purposes and lawful business operations. The Lessee may operate 24x7 with server rooms and standard office equipment.",
           prompt="Check if permitted use allows the intended business. Flag overly restrictive use clauses.", order=5),
        _r("renewal_terms",
           "Renewal should have reasonable notice period (90 days). Flag auto-renewal without notice.",
           "yellow",
           [r"(?i)\b(renewal\s+(terms?|option|clause))\b", r"(?i)\b(right\s+to\s+renew)\b",
            r"(?i)\b(auto(matic(ally)?)?[\s-]?renew)\b", r"(?i)\b(option\s+to\s+renew)\b"],
           "The Lessee shall have the option to renew this Lease for an additional term of [X] years upon ninety (90) days' prior written notice before expiry, subject to mutually agreed revised rent.",
           prompt="Check renewal terms. Flag auto-renewal without adequate notice (prefer 90 days).", order=6),
        _r("fitout_restoration",
           "Fit-out and restoration obligations should be fair. Flag if lessee bears all restoration costs.",
           "yellow",
           [r"(?i)\b(fit[\s-]?out)\b", r"(?i)\b(restoration\s+(obligation|cost|charge))\b",
            r"(?i)\b(reinstate|reinstatement)\b", r"(?i)\b(original\s+condition)\b"],
           "The Lessee may carry out interior fit-out at its own expense with Lessor's written consent. Upon termination, the Lessee shall restore the Premises to the original condition, excluding normal wear and tear. Structural modifications require mutual agreement on restoration responsibility.",
           prompt="Check fit-out and restoration terms. Flag if lessee bears all costs including structural restoration.", order=7),
        _r("sub_letting",
           "Sub-letting should be permitted with lessor's consent. Flag if entirely prohibited.",
           "yellow",
           [r"(?i)\b(sub[\s-]?let(ting)?)\b", r"(?i)\b(sub[\s-]?lease)\b",
            r"(?i)\b(assign(ment)?\s+of\s+(the\s+)?lease)\b"],
           "The Lessee may sub-let a portion of the Premises (not exceeding 50% of the leased area) with the Lessor's prior written consent, which shall not be unreasonably withheld. The Lessee remains primarily liable under this Lease.",
           prompt="Check if sub-letting is permitted. Flag if entirely prohibited with no exceptions.", order=8),
        _r("governing_law",
           "Indian law with specific state jurisdiction.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b",
            r"(?i)\b(jurisdiction)\b"],
           "This Lease shall be governed by the laws of India and the applicable state Rent Control Act. Courts at [City], India shall have exclusive jurisdiction.",
           prompt="Must be Indian law with appropriate state jurisdiction.", order=9),
    ],
}
