"""Master Service Agreement — Default playbook."""
import uuid

def _r(clause_type, primary, risk, patterns, fallback=None, deal_breaker=False, ai_verify=True, prompt=None, order=0):
    sl = {"preferred": primary}
    if fallback:
        sl["fallback"] = fallback
    return {
        "id": str(uuid.uuid4()), "clause_type": clause_type, "primary_position": primary,
        "fallback_position": fallback, "risk_level": risk, "is_deal_breaker": deal_breaker,
        "detection_patterns": {"match_type": "regex", "patterns": patterns},
        "suggested_language": sl, "requires_ai_verification": ai_verify,
        "verification_prompt": prompt, "order_index": order,
    }

MSA = {
    "name": "Master Service Agreement (MSA)",
    "description": "Default playbook for master service agreements covering ongoing IT, consulting, or outsourcing relationships. Covers liability caps, indemnification, IP, termination, force majeure, and Indian law compliance.",
    "category": "MSA",
    "rules": [
        _r("scope_of_services",
           "Scope of services must be clearly defined with specific deliverables, timelines, and acceptance criteria.",
           "yellow",
           [r"(?i)\b(scope\s+of\s+(services|work))\b", r"(?i)\b(services?\s+(shall|will)\s+(include|comprise|consist))\b",
            r"(?i)\b(statement\s+of\s+work|SOW)\b"],
           "The scope of services shall be defined in individual Statements of Work (SOWs) attached hereto, each specifying deliverables, timelines, acceptance criteria, and fees.",
           prompt="Check if scope of services is clearly defined or vague/open-ended. Flag if no SOW mechanism exists.", order=0),
        _r("payment_terms",
           "Payment terms should be Net 30. Flag if exceeding 45 days.",
           "yellow",
           [r"(?i)\b(payment\s+terms?)\b", r"(?i)\b(net\s+\d+)\b", r"(?i)\b(payable\s+within\s+\d+\s+days)\b",
            r"(?i)\b(invoice|billing)\s+(cycle|period|terms)\b"],
           "All invoices shall be payable within thirty (30) days of receipt of a valid invoice (Net 30). Late payments shall accrue interest at 1.5% per month or the maximum rate permitted by law.",
           prompt="Check payment terms. Flag if >45 days. Acceptable: Net 30.", order=1),
        _r("limitation_of_liability",
           "Liability must be capped at 12 months of fees paid under the relevant SOW. Unlimited liability is a deal-breaker.",
           "red",
           [r"(?i)\b(unlimited\s+liability)\b", r"(?i)\b(no\s+(cap|limit|limitation)\s+(on|to)\s+liability)\b",
            r"(?i)\b(limitation\s+of\s+liability)\b", r"(?i)\b(aggregate\s+liability)\b",
            r"(?i)\b(liability\s+shall\s+not\s+(exceed|be\s+limited))\b"],
           "Neither Party's aggregate liability under this Agreement shall exceed the total fees paid or payable in the twelve (12) months preceding the claim. Neither Party shall be liable for indirect, incidental, consequential, or punitive damages.",
           deal_breaker=True,
           prompt="Check if liability is capped. Flag unlimited liability as deal-breaker. Acceptable cap: 12 months fees.", order=2),
        _r("indemnification",
           "Indemnification should be mutual and capped. One-sided uncapped indemnification is a deal-breaker.",
           "red",
           [r"(?i)\b(indemnif(y|ication|ies))\b", r"(?i)\b(defend,?\s+indemnify,?\s+(and\s+)?hold\s+harmless)\b",
            r"(?i)\b(indemnif(y|ication)\s+against\s+any\s+and\s+all)\b"],
           "Each Party shall indemnify the other against third-party claims arising from: (a) breach of this Agreement; (b) negligence or wilful misconduct; (c) infringement of intellectual property rights. Indemnification obligations shall be subject to the limitation of liability cap.",
           deal_breaker=True,
           prompt="Check if indemnification is mutual or one-sided. Check if it's capped or uncapped. Flag one-sided uncapped indemnification.", order=3),
        _r("ip_ownership",
           "Pre-existing IP stays with original owner. Work product IP should be clearly allocated.",
           "red",
           [r"(?i)\b(intellectual\s+property\s+(ownership|rights))\b", r"(?i)\b(work(s)?\s+for\s+hire)\b",
            r"(?i)\b(all\s+(IP|intellectual\s+property)\s+shall\s+(belong|vest))\b",
            r"(?i)\b(pre[\s-]?existing\s+(IP|intellectual\s+property))\b"],
           "Each Party retains all rights in its pre-existing intellectual property. Work product created specifically for Client under an SOW shall be assigned to Client upon full payment. Service Provider retains rights to its tools, methodologies, and general know-how.",
           deal_breaker=True,
           prompt="Check IP ownership allocation. Flag if all IP (including pre-existing) is assigned to one party.", order=4),
        _r("confidentiality",
           "Confidentiality term should be 3-5 years, not perpetual.",
           "yellow",
           [r"(?i)\b(confidential(ity)?\s+(obligation|clause|provision))\b",
            r"(?i)\b(perpetual\s+confidentiality)\b", r"(?i)\b(confidential(ity)?\s+(in\s+)?perpetuity)\b"],
           "Each Party shall maintain the confidentiality of the other's Confidential Information for three (3) years following termination of this Agreement.",
           prompt="Check if confidentiality term is perpetual. Acceptable: 3-5 years.", order=5),
        _r("termination_for_convenience",
           "Termination for convenience should require 30-day written notice and payment for work completed.",
           "red",
           [r"(?i)\b(terminat(e|ion)\s+(for\s+)?convenience)\b",
            r"(?i)\b(terminat(e|ion)\s+without\s+(cause|reason))\b",
            r"(?i)\b(may\s+terminate\s+(at\s+)?any\s+time)\b"],
           "Either Party may terminate this Agreement for convenience upon thirty (30) days' prior written notice. Upon termination, Client shall pay for all services rendered and expenses incurred through the effective date of termination.",
           deal_breaker=True,
           prompt="Check if termination for convenience exists and whether it requires notice. Flag if no notice period or payment for completed work.", order=6),
        _r("termination_for_cause",
           "Termination for cause must include a cure period (minimum 30 days).",
           "yellow",
           [r"(?i)\b(terminat(e|ion)\s+for\s+cause)\b", r"(?i)\b(material\s+breach)\b",
            r"(?i)\b(cure\s+period)\b", r"(?i)\b(right\s+to\s+cure)\b"],
           "Either Party may terminate for material breach if the breaching Party fails to cure such breach within thirty (30) days of receiving written notice specifying the breach.",
           prompt="Check if cure period exists for termination for cause. Flag if no cure period. Acceptable: 30 days.", order=7),
        _r("force_majeure",
           "Force majeure should cover both parties equally with specific triggering events and termination right if event persists.",
           "yellow",
           [r"(?i)\b(force\s+majeure)\b", r"(?i)\b(act(s)?\s+of\s+god)\b",
            r"(?i)\b(beyond\s+(the\s+)?(reasonable\s+)?control)\b"],
           "Neither Party shall be liable for delays caused by force majeure events including natural disasters, epidemics, war, government actions, or other events beyond reasonable control. If a force majeure event continues for sixty (60) days, either Party may terminate upon written notice.",
           prompt="Check if force majeure covers both parties. Flag if only one party is protected.", order=8),
        _r("assignment",
           "Assignment should be permitted to affiliates without consent.",
           "yellow",
           [r"(?i)\b(may\s+not\s+assign)\b", r"(?i)\b(assignment\s+(is\s+)?(prohibited|restricted))\b",
            r"(?i)\b(no\s+assignment\s+without\s+(prior\s+)?(written\s+)?consent)\b"],
           "Neither Party may assign this Agreement without the prior written consent of the other Party, except that either Party may assign to an affiliate or in connection with a merger, acquisition, or sale of substantially all its assets.",
           prompt="Check if assignment is completely prohibited or allows affiliate assignments.", order=9),
        _r("warranties",
           "Warranties should be mutual. Service provider warrants professional standards; client warrants accurate information.",
           "yellow",
           [r"(?i)\b(warrant(y|ies|s)?\s+(and\s+)?representation)\b", r"(?i)\b(as[\s-]?is)\b",
            r"(?i)\b(no\s+warrant(y|ies))\b", r"(?i)\b(disclaim(s|ing)?\s+all\s+warrant(y|ies))\b"],
           "Service Provider warrants that services shall be performed in a professional and workmanlike manner in accordance with generally accepted industry standards. Client warrants that all information provided shall be accurate and complete.",
           prompt="Check if warranties are mutual or one-sided. Flag 'as-is' disclaimers on services.", order=10),
        _r("dispute_resolution",
           "Prefer arbitration under the Indian Arbitration and Conciliation Act, 1996 over litigation.",
           "green",
           [r"(?i)\b(dispute\s+resolution)\b", r"(?i)\b(arbitrat(ion|or|e))\b",
            r"(?i)\b(mediat(ion|or|e))\b", r"(?i)\b(Indian\s+Arbitration)\b"],
           "Any dispute arising out of this Agreement shall first be attempted to be resolved through good faith negotiation. If unresolved within thirty (30) days, the dispute shall be referred to arbitration under the Arbitration and Conciliation Act, 1996, with a sole arbitrator seated in [City], India.",
           prompt="Check dispute resolution mechanism. Prefer arbitration over litigation.", order=11),
        _r("governing_law",
           "Governing law must be Indian law.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b",
            r"(?i)\b(applicable\s+law)\b"],
           "This Agreement shall be governed by and construed in accordance with the laws of India.",
           prompt="Check if governing law is Indian law. Flag foreign jurisdiction.", order=12),
        _r("auto_renewal",
           "Auto-renewal must include 30-day opt-out notice window.",
           "yellow",
           [r"(?i)\b(auto(matic(ally)?)?[\s-]?renew(al|s|ed)?)\b",
            r"(?i)\b(renew(s|ed)?\s+automatically)\b"],
           "This Agreement shall automatically renew for successive one (1) year terms unless either Party provides written notice of non-renewal at least thirty (30) days prior to the expiration of the then-current term.",
           prompt="Check if auto-renewal has an opt-out notice period. Flag if no opt-out window.", order=13),
        _r("data_protection",
           "Must reference IT Act 2000 and DPDP Act 2023 for data handling obligations.",
           "yellow",
           [r"(?i)\b(data\s+protection)\b", r"(?i)\b(personal\s+data)\b", r"(?i)\b(DPDP|IT\s+Act)\b",
            r"(?i)\b(data\s+privacy)\b", r"(?i)\b(information\s+technology\s+act)\b"],
           "Both Parties shall comply with applicable data protection laws including the Information Technology Act, 2000 and the Digital Personal Data Protection Act, 2023. Any processing of personal data shall be governed by a separate Data Processing Agreement.",
           prompt="Check if data protection obligations are addressed. Flag if missing in a services agreement.", order=14),
    ],
}
