"""Master Service Agreement — Default playbook."""
from scripts.playbooks._helpers import _r  # noqa: F401

MSA = {
    "name": "Master Service Agreement (MSA)",
    "description": "Default playbook for master service agreements covering ongoing IT, consulting, or outsourcing relationships. Covers liability caps, indemnification, IP, termination, force majeure, and Indian law compliance.",
    "category": "msa",
    "party_side": "buyer",
    "rules": [
        _r("scope_of_services",
           "Scope of services must be clearly defined with specific deliverables, timelines, and acceptance criteria.",
           "yellow",
           [r"(?i)\b(scope\s+of\s+(services|work))\b", r"(?i)\b(services?\s+(shall|will)\s+(include|comprise|consist))\b",
            r"(?i)\b(statement\s+of\s+work|SOW)\b"],
           "The scope of services shall be defined in individual Statements of Work (SOWs) attached hereto, each specifying deliverables, timelines, acceptance criteria, and fees.",
           prompt="Check if scope of services is clearly defined or vague/open-ended. Flag if no SOW mechanism exists.", order=0,
           detection_mode="ai_with_keywords",
           risk_description="Scope of services is vague or open-ended without SOW mechanism",
           unacceptable_signals=["as directed by client", "all services reasonably requested", "scope to be determined"],
           acceptable_signals=["specific deliverables", "statement of work", "defined acceptance criteria"],
           acceptable_position="Clearly defined scope with SOW mechanism for each engagement"),
        _r("payment_terms",
           "Payment terms should be Net 30. Flag if exceeding 45 days.",
           "yellow",
           [r"(?i)\b(payment\s+terms?)\b", r"(?i)\b(net\s+\d+)\b", r"(?i)\b(payable\s+within\s+\d+\s+days)\b",
            r"(?i)\b(invoice|billing)\s+(cycle|period|terms)\b"],
           "All invoices shall be payable within thirty (30) days of receipt of a valid invoice (Net 30). Late payments shall accrue interest at 1.5% per month or the maximum rate permitted by law.",
           prompt="Check payment terms. Flag if >45 days. Acceptable: Net 30.", order=1,
           detection_mode="ai_with_keywords",
           risk_description="Payment terms exceed 45 days or lack late payment penalties",
           unacceptable_signals=["net 90", "net 60", "payment at sole discretion", "no late payment interest"],
           acceptable_signals=["net 30", "within 30 days of invoice", "late payment interest at"],
           acceptable_position="Net 30 payment terms with 1.5% monthly interest on late payments"),
        _r("limitation_of_liability",
           "Liability must be capped at 12 months of fees paid under the relevant SOW. Unlimited liability is a deal-breaker.",
           "red",
           [r"(?i)\b(unlimited\s+liability)\b", r"(?i)\b(no\s+(cap|limit|limitation)\s+(on|to)\s+liability)\b",
            r"(?i)\b(limitation\s+of\s+liability)\b", r"(?i)\b(aggregate\s+liability)\b",
            r"(?i)\b(liability\s+shall\s+not\s+(exceed|be\s+limited))\b"],
           "Neither Party's aggregate liability under this Agreement shall exceed the total fees paid or payable in the twelve (12) months preceding the claim. Neither Party shall be liable for indirect, incidental, consequential, or punitive damages.",
           deal_breaker=True,
           prompt="Check if liability is capped. Flag unlimited liability as deal-breaker. Acceptable cap: 12 months fees.", order=2,
           detection_mode="ai_with_keywords",
           risk_description="Liability cap is missing, unlimited, or disproportionately high relative to contract value",
           unacceptable_signals=["unlimited liability", "no cap on damages", "aggregate liability shall not apply", "liability without limitation"],
           acceptable_signals=["liability capped at", "aggregate liability shall not exceed", "limited to fees paid in the preceding 12 months"],
           acceptable_position="Mutual liability capped at 12 months of fees paid, with standard carve-outs for IP infringement and confidentiality breach"),
        _r("indemnification",
           "Indemnification should be mutual and capped. One-sided uncapped indemnification is a deal-breaker.",
           "red",
           [r"(?i)\b(indemnif(y|ication|ies))\b", r"(?i)\b(defend,?\s+indemnify,?\s+(and\s+)?hold\s+harmless)\b",
            r"(?i)\b(indemnif(y|ication)\s+against\s+any\s+and\s+all)\b"],
           "Each Party shall indemnify the other against third-party claims arising from: (a) breach of this Agreement; (b) negligence or wilful misconduct; (c) infringement of intellectual property rights. Indemnification obligations shall be subject to the limitation of liability cap.",
           deal_breaker=True,
           prompt="Check if indemnification is mutual or one-sided. Check if it's capped or uncapped. Flag one-sided uncapped indemnification.", order=3,
           detection_mode="ai_with_keywords",
           risk_description="Indemnification is one-sided, uncapped, or covers consequential/indirect damages",
           unacceptable_signals=["shall indemnify without limitation", "indemnify against all losses including consequential", "sole indemnification obligation"],
           acceptable_signals=["mutual indemnification", "indemnification capped at", "limited to direct damages", "subject to the limitation of liability"],
           acceptable_position="Mutual indemnification capped at contract value, limited to direct damages"),
        _r("ip_ownership",
           "Pre-existing IP stays with original owner. Work product IP should be clearly allocated.",
           "red",
           [r"(?i)\b(intellectual\s+property\s+(ownership|rights))\b", r"(?i)\b(work(s)?\s+for\s+hire)\b",
            r"(?i)\b(all\s+(IP|intellectual\s+property)\s+shall\s+(belong|vest))\b",
            r"(?i)\b(pre[\s-]?existing\s+(IP|intellectual\s+property))\b"],
           "Each Party retains all rights in its pre-existing intellectual property. Work product created specifically for Client under an SOW shall be assigned to Client upon full payment. Service Provider retains rights to its tools, methodologies, and general know-how.",
           deal_breaker=True,
           prompt="Check IP ownership allocation. Flag if all IP (including pre-existing) is assigned to one party.", order=4,
           detection_mode="ai_with_keywords",
           risk_description="IP ownership assigns all intellectual property including pre-existing IP to one party",
           unacceptable_signals=["all intellectual property shall vest in", "assigns all right title and interest", "work product including pre-existing IP"],
           acceptable_signals=["pre-existing IP remains with", "background IP excluded", "license to pre-existing IP"],
           acceptable_position="Pre-existing IP stays with originator; newly created IP assigned to client"),
        _r("confidentiality",
           "Confidentiality term should be 3-5 years, not perpetual.",
           "yellow",
           [r"(?i)\b(confidential(ity)?\s+(obligation|clause|provision))\b",
            r"(?i)\b(perpetual\s+confidentiality)\b", r"(?i)\b(confidential(ity)?\s+(in\s+)?perpetuity)\b"],
           "Each Party shall maintain the confidentiality of the other's Confidential Information for three (3) years following termination of this Agreement.",
           prompt="Check if confidentiality term is perpetual. Acceptable: 3-5 years.", order=5,
           detection_mode="ai_with_keywords",
           risk_description="Confidentiality obligation is perpetual or unreasonably long (>5 years)",
           unacceptable_signals=["obligations shall survive in perpetuity", "indefinite confidentiality", "shall remain confidential forever"],
           acceptable_signals=["confidentiality period of", "obligations expire after", "3 years from disclosure"],
           acceptable_position="Confidentiality survives 3-5 years post-termination; trade secrets indefinitely"),
        _r("termination_for_convenience",
           "Termination for convenience should require 30-day written notice and payment for work completed.",
           "red",
           [r"(?i)\b(terminat(e|ion)\s+(for\s+)?convenience)\b",
            r"(?i)\b(terminat(e|ion)\s+without\s+(cause|reason))\b",
            r"(?i)\b(may\s+terminate\s+(at\s+)?any\s+time)\b"],
           "Either Party may terminate this Agreement for convenience upon thirty (30) days' prior written notice. Upon termination, Client shall pay for all services rendered and expenses incurred through the effective date of termination.",
           deal_breaker=True,
           prompt="Check if termination for convenience exists and whether it requires notice. Flag if no notice period or payment for completed work.", order=6,
           detection_mode="ai_with_keywords",
           risk_description="Termination for convenience lacks adequate notice period or is one-sided",
           unacceptable_signals=["may terminate at any time without notice", "immediate termination without cause", "unilateral right to terminate"],
           acceptable_signals=["30 days written notice", "either party may terminate", "payment for services rendered"],
           acceptable_position="Either party may terminate with 30 days written notice; payment due for work completed"),
        _r("termination_for_cause",
           "Termination for cause must include a cure period (minimum 30 days).",
           "yellow",
           [r"(?i)\b(terminat(e|ion)\s+for\s+cause)\b", r"(?i)\b(material\s+breach)\b",
            r"(?i)\b(cure\s+period)\b", r"(?i)\b(right\s+to\s+cure)\b"],
           "Either Party may terminate for material breach if the breaching Party fails to cure such breach within thirty (30) days of receiving written notice specifying the breach.",
           prompt="Check if cure period exists for termination for cause. Flag if no cure period. Acceptable: 30 days.", order=7,
           detection_mode="ai_with_keywords",
           risk_description="Termination for cause has no cure period or grounds are unreasonably broad",
           unacceptable_signals=["immediate termination upon breach", "any breach shall entitle", "no cure period"],
           acceptable_signals=["30 days to cure", "written notice specifying the breach", "material breach that remains uncured"],
           acceptable_position="Termination for material breach only, with 30-day written notice and cure period"),
        _r("force_majeure",
           "Force majeure should cover both parties equally with specific triggering events and termination right if event persists.",
           "yellow",
           [r"(?i)\b(force\s+majeure)\b", r"(?i)\b(act(s)?\s+of\s+god)\b",
            r"(?i)\b(beyond\s+(the\s+)?(reasonable\s+)?control)\b"],
           "Neither Party shall be liable for delays caused by force majeure events including natural disasters, epidemics, war, government actions, or other events beyond reasonable control. If a force majeure event continues for sixty (60) days, either Party may terminate upon written notice.",
           prompt="Check if force majeure covers both parties. Flag if only one party is protected.", order=8,
           detection_mode="ai_with_keywords",
           risk_description="Force majeure is one-sided, has exhaustive list, or allows indefinite suspension",
           unacceptable_signals=["force majeure shall only apply to", "limited to acts of God", "indefinite suspension"],
           acceptable_signals=["either party may invoke", "including but not limited to", "right to terminate if persists beyond 90 days"],
           acceptable_position="Mutual force majeure with broad list; right to terminate if event persists beyond 90 days"),
        _r("assignment",
           "Assignment should be permitted to affiliates without consent.",
           "yellow",
           [r"(?i)\b(may\s+not\s+assign)\b", r"(?i)\b(assignment\s+(is\s+)?(prohibited|restricted))\b",
            r"(?i)\b(no\s+assignment\s+without\s+(prior\s+)?(written\s+)?consent)\b"],
           "Neither Party may assign this Agreement without the prior written consent of the other Party, except that either Party may assign to an affiliate or in connection with a merger, acquisition, or sale of substantially all its assets.",
           prompt="Check if assignment is completely prohibited or allows affiliate assignments.", order=9,
           detection_mode="ai_with_keywords",
           risk_description="Assignment completely prohibited without affiliate or M&A exceptions",
           unacceptable_signals=["may not assign under any circumstances", "no assignment without consent"],
           acceptable_signals=["may assign to affiliates", "in connection with a merger or acquisition"],
           acceptable_position="Assignment permitted to affiliates and in M&A transactions without consent"),
        _r("warranties",
           "Warranties should be mutual. Service provider warrants professional standards; client warrants accurate information.",
           "yellow",
           [r"(?i)\b(warrant(y|ies|s)?\s+(and\s+)?representation)\b", r"(?i)\b(as[\s-]?is)\b",
            r"(?i)\b(no\s+warrant(y|ies))\b", r"(?i)\b(disclaim(s|ing)?\s+all\s+warrant(y|ies))\b"],
           "Service Provider warrants that services shall be performed in a professional and workmanlike manner in accordance with generally accepted industry standards. Client warrants that all information provided shall be accurate and complete.",
           prompt="Check if warranties are mutual or one-sided. Flag 'as-is' disclaimers on services.", order=10,
           detection_mode="ai_with_keywords",
           risk_description="Warranties are one-sided or services sold as-is with no quality assurance",
           unacceptable_signals=["as-is", "no warranties", "all warranties disclaimed"],
           acceptable_signals=["professional and workmanlike manner", "industry standards", "mutual warranties"],
           acceptable_position="Mutual warranties: services performed professionally; client provides accurate info"),
        _r("dispute_resolution",
           "Prefer arbitration under the Indian Arbitration and Conciliation Act, 1996 over litigation.",
           "green",
           [r"(?i)\b(dispute\s+resolution)\b", r"(?i)\b(arbitrat(ion|or|e))\b",
            r"(?i)\b(mediat(ion|or|e))\b", r"(?i)\b(Indian\s+Arbitration)\b"],
           "Any dispute arising out of this Agreement shall first be attempted to be resolved through good faith negotiation. If unresolved within thirty (30) days, the dispute shall be referred to arbitration under the Arbitration and Conciliation Act, 1996, with a sole arbitrator seated in [City], India.",
           prompt="Check dispute resolution mechanism. Prefer arbitration over litigation.", order=11,
           detection_mode="ai_with_keywords",
           risk_description="No arbitration clause or dispute resolution relies solely on litigation",
           unacceptable_signals=["exclusive jurisdiction of foreign courts", "no alternative dispute resolution"],
           acceptable_signals=["arbitration", "mediation followed by arbitration", "Arbitration and Conciliation Act 1996"],
           acceptable_position="Tiered: negotiation → mediation → arbitration under Indian Arbitration Act 1996"),
        _r("governing_law",
           "Governing law must be Indian law.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b",
            r"(?i)\b(applicable\s+law)\b"],
           "This Agreement shall be governed by and construed in accordance with the laws of India.",
           prompt="Check if governing law is Indian law. Flag foreign jurisdiction.", order=12,
           detection_mode="ai_with_keywords",
           risk_description="Governing law is not Indian law or jurisdiction outside India",
           unacceptable_signals=["laws of England", "Delaware", "Singapore"],
           acceptable_signals=["laws of India", "Indian courts"],
           acceptable_position="Indian law with jurisdiction in a convenient Indian city"),
        _r("auto_renewal",
           "Auto-renewal must include 30-day opt-out notice window.",
           "yellow",
           [r"(?i)\b(auto(matic(ally)?)?[\s-]?renew(al|s|ed)?)\b",
            r"(?i)\b(renew(s|ed)?\s+automatically)\b"],
           "This Agreement shall automatically renew for successive one (1) year terms unless either Party provides written notice of non-renewal at least thirty (30) days prior to the expiration of the then-current term.",
           prompt="Check if auto-renewal has an opt-out notice period. Flag if no opt-out window.", order=13,
           detection_mode="ai_with_keywords",
           risk_description="Auto-renewal with no opt-out window or unreasonably short notice period",
           unacceptable_signals=["automatically renews without notice", "no opt-out", "7 days notice to cancel"],
           acceptable_signals=["30 days notice before renewal", "either party may elect not to renew"],
           acceptable_position="Auto-renewal with 30-day opt-out notice before each renewal date"),
        _r("data_protection",
           "Must reference IT Act 2000 and DPDP Act 2023 for data handling obligations.",
           "yellow",
           [r"(?i)\b(data\s+protection)\b", r"(?i)\b(personal\s+data)\b", r"(?i)\b(DPDP|IT\s+Act)\b",
            r"(?i)\b(data\s+privacy)\b", r"(?i)\b(information\s+technology\s+act)\b"],
           "Both Parties shall comply with applicable data protection laws including the Information Technology Act, 2000 and the Digital Personal Data Protection Act, 2023. Any processing of personal data shall be governed by a separate Data Processing Agreement.",
           prompt="Check if data protection obligations are addressed. Flag if missing in a services agreement.", order=14,
           detection_mode="ai_with_keywords",
           risk_description="Data protection clause is missing or doesn't reference applicable law (DPDP Act 2023, IT Act 2000)",
           unacceptable_signals=["no mention of data protection", "data handled at discretion"],
           acceptable_signals=["DPDP Act", "IT Act 2000", "data protection obligations", "data fiduciary"],
           clause_context="Under India's DPDP Act 2023, contracts involving personal data must include data protection provisions"),
    ],
}
