"""SaaS Subscription Agreement — Default playbook."""
import uuid

def _r(clause_type, primary, risk, patterns, fallback=None, deal_breaker=False, ai_verify=True, prompt=None, order=0):
    sl = {"preferred": primary}
    if fallback:
        sl["fallback"] = fallback
    return {
        "id": str(uuid.uuid4()), "clause_type": clause_type, "primary_position": primary,
        "fallback_position": fallback, "risk_level": risk, "is_deal_breaker": deal_breaker,
        "detection_patterns": {"match_type": "regex", "patterns": patterns},
        "suggested_language": sl, "requires_ai_verification": ai_verify,
        "verification_prompt": prompt, "order_index": order,
    }

SAAS = {
    "name": "SaaS Subscription Agreement",
    "description": "Default playbook for cloud software subscriptions. Covers SLA/uptime, data ownership, security, liability, termination with data portability, pricing, and DPDP Act compliance.",
    "category": "SAAS",
    "rules": [
        _r("sla_uptime",
           "SaaS agreement must include a Service Level Agreement with minimum 99.9% uptime guarantee and remedies for breach.",
           "yellow",
           [r"(?i)\b(service\s+level\s+agreement|SLA)\b", r"(?i)\b(uptime\s+(guarantee|commitment))\b",
            r"(?i)\b(\d{2,3}(\.\d+)?%\s+uptime)\b", r"(?i)\b(availability\s+(guarantee|commitment))\b"],
           "Provider shall maintain Service availability of at least 99.9% per calendar month, excluding scheduled maintenance. If uptime falls below the SLA, Customer shall receive service credits as specified in the SLA schedule.",
           prompt="Check if an SLA/uptime guarantee exists. Flag if no SLA or if uptime is below 99.9%.", order=0),
        _r("data_ownership",
           "Customer data must remain customer's property at all times. Vendor claiming ownership of customer data is a deal-breaker.",
           "red",
           [r"(?i)\b(data\s+ownership)\b", r"(?i)\b(customer\s+data)\b",
            r"(?i)\b(all\s+data\s+(shall\s+)?(belong|vest)\s+(to|in|with)\s+(provider|vendor|company))\b",
            r"(?i)\b(we\s+own\s+(all\s+)?data)\b"],
           "All Customer Data uploaded to or generated within the Service remains the exclusive property of Customer. Provider acquires no rights to Customer Data except the limited license to process it for providing the Service.",
           deal_breaker=True,
           prompt="Check who owns customer data. Flag if vendor/provider claims ownership. Customer must own their data.", order=1),
        _r("data_security",
           "Must specify security standards (SOC 2, ISO 27001) and encryption requirements.",
           "yellow",
           [r"(?i)\b(data\s+security)\b", r"(?i)\b(SOC\s*2|ISO\s*27001|ISO\s*27018)\b",
            r"(?i)\b(encrypt(ion|ed))\b", r"(?i)\b(security\s+(measures|standards|controls))\b"],
           "Provider shall maintain industry-standard security measures including SOC 2 Type II compliance, encryption of data at rest (AES-256) and in transit (TLS 1.2+), regular penetration testing, and annual security audits.",
           prompt="Check if specific security standards are mentioned. Flag vague security promises without named standards.", order=2),
        _r("limitation_of_liability",
           "Liability capped at 12 months of subscription fees. Unlimited liability is a deal-breaker.",
           "red",
           [r"(?i)\b(limitation\s+of\s+liability)\b", r"(?i)\b(aggregate\s+liability)\b",
            r"(?i)\b(unlimited\s+liability)\b", r"(?i)\b(liability\s+shall\s+not\s+exceed)\b"],
           "Provider's aggregate liability shall not exceed the total subscription fees paid by Customer in the twelve (12) months preceding the claim. Neither Party shall be liable for indirect, consequential, or punitive damages.",
           deal_breaker=True,
           prompt="Check liability cap. Flag unlimited liability. Acceptable: 12 months fees.", order=3),
        _r("indemnification",
           "Vendor must indemnify for IP infringement. Should be mutual and capped.",
           "red",
           [r"(?i)\b(indemnif(y|ication|ies))\b", r"(?i)\b(hold\s+harmless)\b"],
           "Provider shall indemnify Customer against third-party claims alleging that the Service infringes any intellectual property right. Customer shall indemnify Provider against claims arising from Customer's use of the Service in violation of this Agreement.",
           prompt="Check if vendor indemnifies for IP infringement. Check if mutual and capped.", order=4),
        _r("termination_data_portability",
           "Upon termination, customer must be able to export all their data. No data export = deal-breaker.",
           "red",
           [r"(?i)\b(data\s+(portability|export|extraction|migration))\b",
            r"(?i)\b(upon\s+termination.{0,80}data)\b",
            r"(?i)\b(return\s+of\s+(customer\s+)?data)\b"],
           "Upon termination for any reason, Provider shall make Customer Data available for export in a standard machine-readable format (CSV, JSON, or XML) for at least thirty (30) days. After the export period, Provider shall permanently delete all Customer Data and certify deletion.",
           deal_breaker=True,
           prompt="Check if data export/portability provision exists for termination. Flag if missing — customer must get their data back.", order=5),
        _r("auto_renewal",
           "Auto-renewal must have 30-day opt-out window. Flag if no cancellation notice period.",
           "yellow",
           [r"(?i)\b(auto(matic(ally)?)?[\s-]?renew(al|s|ed)?)\b",
            r"(?i)\b(renew(s|ed)?\s+automatically)\b"],
           "This subscription shall renew automatically unless Customer provides written notice of non-renewal at least thirty (30) days before the end of the current term.",
           prompt="Check auto-renewal opt-out period. Flag if no opt-out window.", order=6),
        _r("price_escalation",
           "Price increases should be capped (CPI or max 10% annually). Unlimited price escalation is concerning.",
           "yellow",
           [r"(?i)\b(price\s+(increase|escalation|adjustment|hike))\b",
            r"(?i)\b(fee\s+(increase|adjustment))\b",
            r"(?i)\b(reserve(s)?\s+the\s+right\s+to\s+(change|increase|adjust)\s+(price|fee))\b"],
           "Provider may increase subscription fees upon renewal by written notice at least sixty (60) days prior, not to exceed the greater of 5% or the Consumer Price Index (CPI) increase for the preceding year.",
           prompt="Check if price increases are capped. Flag unlimited or >10% annual increases.", order=7),
        _r("reverse_engineering",
           "Standard prohibition — negotiate for interoperability exceptions.",
           "yellow",
           [r"(?i)\b(reverse\s+engineer(ing)?)\b", r"(?i)\b(decompil(e|ation)|disassembl(e|y))\b"],
           "Customer shall not reverse engineer or decompile the Service, except as permitted by applicable law for interoperability purposes under the Information Technology Act, 2000.",
           prompt="Check if reverse engineering prohibition includes interoperability exception.", order=8),
        _r("ip_ownership",
           "Customer data stays customer's. Vendor IP (platform, code) stays vendor's. Clearly separate.",
           "red",
           [r"(?i)\b(intellectual\s+property\s+(ownership|rights))\b",
            r"(?i)\b(all\s+(IP|intellectual\s+property)\s+shall\s+(belong|vest))\b"],
           "Provider retains all intellectual property rights in the Service, including all improvements and modifications. Customer retains all rights in Customer Data. Neither Party acquires any rights in the other's intellectual property except as expressly granted herein.",
           prompt="Check IP separation between vendor platform IP and customer data.", order=9),
        _r("force_majeure",
           "Force majeure should cover both parties with termination right after 60 days.",
           "yellow",
           [r"(?i)\b(force\s+majeure)\b", r"(?i)\b(act(s)?\s+of\s+god)\b",
            r"(?i)\b(beyond\s+(the\s+)?(reasonable\s+)?control)\b"],
           "Neither Party shall be liable for failure to perform due to events beyond reasonable control. If a force majeure event persists for sixty (60) days, either Party may terminate upon written notice.",
           prompt="Check if force majeure is mutual.", order=10),
        _r("data_processing_dpdp",
           "Must have a Data Processing Agreement if processing personal data under DPDP Act 2023.",
           "yellow",
           [r"(?i)\b(data\s+process(ing|or))\b", r"(?i)\b(DPDP|Digital\s+Personal\s+Data\s+Protection)\b",
            r"(?i)\b(data\s+fiduciary)\b", r"(?i)\b(personal\s+data)\b"],
           "Where Provider processes personal data on behalf of Customer, the Parties shall execute a Data Processing Agreement in compliance with the Digital Personal Data Protection Act, 2023. Provider shall act only on Customer's documented instructions.",
           prompt="Check if data processing obligations reference DPDP Act 2023. Flag if missing in a SaaS agreement that handles personal data.", order=11),
        _r("governing_law",
           "Governing law should be Indian law.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b"],
           "This Agreement shall be governed by the laws of India.",
           prompt="Flag foreign jurisdiction.", order=12),
    ],
}
