"""Vendor / Procurement Agreement — Default playbook."""
import uuid

def _r(clause_type, primary, risk, patterns, fallback=None, deal_breaker=False,
       ai_verify=True, prompt=None, order=0,
       detection_mode="keywords_only", risk_description=None,
       acceptable_position=None, unacceptable_signals=None,
       acceptable_signals=None, clause_context=None):
    sl = {"preferred": primary}
    if fallback:
        sl["fallback"] = fallback
    d = {
        "id": str(uuid.uuid4()), "clause_type": clause_type, "primary_position": primary,
        "fallback_position": fallback, "risk_level": risk, "is_deal_breaker": deal_breaker,
        "detection_patterns": {"match_type": "regex", "patterns": patterns},
        "suggested_language": sl, "requires_ai_verification": ai_verify,
        "verification_prompt": prompt, "order_index": order,
    }
    d["detection_mode"] = detection_mode
    d["risk_description"] = risk_description
    d["acceptable_position"] = acceptable_position
    d["unacceptable_signals"] = unacceptable_signals or []
    d["acceptable_signals"] = acceptable_signals or []
    d["clause_context"] = clause_context
    return d

VENDOR = {
    "name": "Vendor / Procurement Agreement",
    "description": "Default playbook for buying goods or services from suppliers. Covers delivery, acceptance, payment, warranties, liability, indemnification, and termination for non-performance.",
    "category": "CUSTOM",
    "rules": [
        _r("delivery_terms",
           "Delivery timelines must be specific with SLAs and consequences for delay.",
           "yellow",
           [r"(?i)\b(delivery\s+(terms?|schedule|timeline))\b", r"(?i)\b(deliver(y|ed)\s+within\s+\d+)\b",
            r"(?i)\b(shipping\s+(terms?|conditions))\b"],
           "Vendor shall deliver goods/services within the timelines specified in each Purchase Order. Delay beyond [X] days shall entitle the Buyer to liquidated damages at 1% of the order value per week of delay, capped at 10%.",
           prompt="Check if delivery timelines are specific. Flag if no dates/SLAs or no consequences for delay.", order=0),
        _r("acceptance_criteria",
           "Must define acceptance/rejection process with inspection period.",
           "yellow",
           [r"(?i)\b(acceptance\s+(criteria|testing|process))\b", r"(?i)\b(inspection\s+period)\b",
            r"(?i)\b(reject(ion)?\s+(process|right|notice))\b"],
           "Buyer shall have fifteen (15) business days from delivery to inspect and accept or reject the goods/services. Rejection must be communicated in writing with reasons. Vendor shall remedy defects within ten (10) business days of rejection notice at no additional cost.",
           prompt="Check if acceptance/rejection process is defined. Flag if missing.", order=1,
           detection_mode="ai_with_keywords",
           risk_description="No defined acceptance/rejection process or timeline",
           unacceptable_signals=["deemed accepted upon delivery", "no rejection right", "no inspection period"],
           acceptable_signals=["inspection period", "acceptance criteria defined", "right to reject non-conforming goods"],
           acceptable_position="30-day inspection with defined criteria; right to reject non-conforming goods"),
        _r("payment_terms",
           "Payment terms should be milestone-based. Advance payment should not exceed 30%.",
           "yellow",
           [r"(?i)\b(payment\s+terms?)\b", r"(?i)\b(advance\s+payment)\b",
            r"(?i)\b(payable\s+within\s+\d+)\b", r"(?i)\b(net\s+\d+)\b"],
           "Payment shall be made within thirty (30) days of acceptance of goods/services and receipt of valid invoice. Advance payment, if any, shall not exceed 20% of the Purchase Order value.",
           prompt="Check payment terms. Flag if advance payment >30% or payment period >45 days.", order=2),
        _r("warranties",
           "Vendor must provide express warranties on goods/services. Flag 'as-is' disclaimers.",
           "yellow",
           [r"(?i)\b(warrant(y|ies))\b", r"(?i)\b(as[\s-]?is)\b",
            r"(?i)\b(no\s+warrant(y|ies))\b", r"(?i)\b(disclaim(s|ing)?\s+all\s+warrant(y|ies))\b"],
           "Vendor warrants that: (a) goods shall be free from defects in material and workmanship for twelve (12) months from acceptance; (b) goods shall conform to specifications in the Purchase Order; (c) services shall be performed in a professional manner. Vendor shall repair or replace defective goods at its expense.",
           prompt="Check if express warranties exist. Flag 'as-is' or warranty disclaimers.", order=3,
           detection_mode="ai_with_keywords",
           risk_description="Goods/services sold as-is with no express warranties",
           unacceptable_signals=["as-is", "no warranties express or implied", "all warranties disclaimed"],
           acceptable_signals=["warranty of merchantability", "fit for intended purpose", "12 months warranty period"],
           acceptable_position="Express warranty: conforms to specs, free from defects, fit for purpose, 12-month warranty"),
        _r("limitation_of_liability",
           "Liability capped at contract value. Unlimited liability is a deal-breaker.",
           "red",
           [r"(?i)\b(limitation\s+of\s+liability)\b", r"(?i)\b(aggregate\s+liability)\b",
            r"(?i)\b(unlimited\s+liability)\b"],
           "Vendor's aggregate liability shall not exceed the total value of the relevant Purchase Order. Neither Party shall be liable for indirect or consequential damages, except for Vendor's indemnification obligations.",
           deal_breaker=True,
           prompt="Check liability cap. Flag unlimited liability.", order=4,
           detection_mode="ai_with_keywords",
           risk_description="Liability cap missing or set too low for potential damages from defects",
           unacceptable_signals=["vendor liability limited to price of individual order", "as-is basis"],
           acceptable_signals=["capped at total contract value", "capped at 12 months of fees"],
           acceptable_position="Vendor liability capped at total contract value or 12 months fees"),
        _r("indemnification",
           "Vendor must indemnify for defective goods and IP infringement.",
           "red",
           [r"(?i)\b(indemnif(y|ication|ies))\b", r"(?i)\b(hold\s+harmless)\b"],
           "Vendor shall indemnify Buyer against: (a) third-party claims arising from defective goods/services; (b) claims of intellectual property infringement; (c) death or personal injury caused by Vendor's negligence.",
           prompt="Check if vendor indemnifies for defects and IP infringement.", order=5,
           detection_mode="ai_with_keywords",
           risk_description="Vendor does not indemnify for defective goods or IP infringement",
           unacceptable_signals=["buyer assumes all risk", "no vendor indemnification", "vendor not liable for defects"],
           acceptable_signals=["vendor indemnifies for defective goods", "IP infringement indemnification"],
           acceptable_position="Vendor indemnifies for defective goods and third-party IP infringement"),
        _r("termination_non_performance",
           "Must have termination right for vendor non-performance with cure period.",
           "yellow",
           [r"(?i)\b(terminat(e|ion)\s+(for\s+)?(non[\s-]?performance|default|breach))\b",
            r"(?i)\b(material\s+breach)\b", r"(?i)\b(cure\s+period)\b"],
           "Buyer may terminate for Vendor's material breach or non-performance if Vendor fails to cure within thirty (30) days of written notice. Upon termination, Vendor shall refund payments for undelivered goods/services.",
           prompt="Check if termination for non-performance exists with cure period.", order=6),
        _r("force_majeure",
           "Force majeure should be mutual with defined events and termination right.",
           "yellow",
           [r"(?i)\b(force\s+majeure)\b", r"(?i)\b(act(s)?\s+of\s+god)\b"],
           "Neither Party shall be liable for delays due to force majeure events. If force majeure continues for sixty (60) days, either Party may terminate the affected Purchase Order.",
           prompt="Check if force majeure is mutual.", order=7),
        _r("insurance_requirements",
           "Vendor should maintain adequate insurance coverage.",
           "yellow",
           [r"(?i)\b(insurance\s+(requirement|coverage|policy))\b",
            r"(?i)\b(maintain\s+(adequate\s+)?insurance)\b"],
           "Vendor shall maintain: (a) commercial general liability insurance of at least INR 1 Crore; (b) professional indemnity insurance; (c) worker's compensation as required by law. Vendor shall provide certificates of insurance upon request.",
           prompt="Check if insurance requirements are specified. Flag if no minimum insurance.", order=8),
        _r("governing_law",
           "Indian law.",
           "green",
           [r"(?i)\b(govern(ed|ing)\s+(by|law))\b", r"(?i)\b(laws\s+of\s+(the\s+)?india)\b"],
           "This Agreement shall be governed by the laws of India.",
           prompt="Flag foreign jurisdiction.", order=9),
    ],
}
