"""
Risk Report Generator - Creates professional DOCX reports from analysis data.

ZDR-safe: Only receives analysis metadata (risk snippets + AI explanations),
NOT the full contract text.
"""

import io
import logging
from datetime import datetime, timezone
from typing import List, Dict

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

logger = logging.getLogger(__name__)


def generate_risk_report(
    filename: str,
    executive_summary: List[str],
    redlines: List[Dict],
    risk_summary: Dict[str, int],
    generated_by: str = "ContraRed AI",
) -> io.BytesIO:
    """
    Generate a professional risk assessment DOCX report.

    Args:
        filename: Original contract filename
        executive_summary: List of executive summary bullet points
        redlines: List of dicts with keys: risk_level, rule_name,
                  original_text, explanation, suggested_fix
        risk_summary: Dict with keys: red, yellow
        generated_by: Author name

    Returns:
        BytesIO buffer containing the DOCX file
    """
    doc = Document()

    # -- Title --
    title = doc.add_heading("Contract Risk Assessment Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Contract: {filename}")
    doc.add_paragraph(f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %H:%M UTC')}")
    doc.add_paragraph(f"Analyzed by: {generated_by}")
    doc.add_paragraph("")

    # -- Risk Summary Table --
    doc.add_heading("Risk Summary", level=1)

    red_count = risk_summary.get("red", 0)
    yellow_count = risk_summary.get("yellow", 0)
    total = red_count + yellow_count

    table = doc.add_table(rows=2, cols=3)
    table.style = "Light Grid Accent 1"
    headers = ["Critical (RED)", "Warning (YELLOW)", "Total"]
    values = [str(red_count), str(yellow_count), str(total)]
    for i, (header, value) in enumerate(zip(headers, values)):
        table.cell(0, i).text = header
        table.cell(1, i).text = value

    doc.add_paragraph("")

    # -- Executive Summary --
    doc.add_heading("Executive Summary", level=1)

    if executive_summary:
        for point in executive_summary:
            doc.add_paragraph(point, style="List Bullet")
    else:
        doc.add_paragraph("No executive summary available.")

    doc.add_paragraph("")

    # -- Detailed Findings --
    doc.add_heading("Detailed Findings", level=1)

    if not redlines:
        doc.add_paragraph("No risks detected. This document appears compliant.")
    else:
        for i, redline in enumerate(redlines, 1):
            level = redline.get("risk_level", "YELLOW")
            level_label = "CRITICAL" if level == "RED" else "WARNING"
            rule_name = redline.get("rule_name", "Unknown Rule")

            doc.add_heading(f"{i}. [{level_label}] {rule_name}", level=2)

            # Original clause
            p = doc.add_paragraph()
            run = p.add_run("Original Clause: ")
            run.bold = True
            p.add_run(redline.get("original_text", "N/A"))

            # Explanation
            p = doc.add_paragraph()
            run = p.add_run("Risk Explanation: ")
            run.bold = True
            p.add_run(redline.get("explanation", "N/A"))

            # Suggested Fix
            fix = redline.get("suggested_fix")
            if fix:
                p = doc.add_paragraph()
                run = p.add_run("Recommended Fix: ")
                run.bold = True
                p.add_run(fix)

            doc.add_paragraph("")

    # -- Footer --
    doc.add_paragraph("")
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_p.add_run("Generated by ContraRed | AI-Powered Contract Redlining")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    # Write to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
