"""
DPDP Act 2023 Compliance Layer — 12 rules for Digital Personal Data Protection Act compliance.
This layer can be toggled ON alongside any playbook (MSA, SaaS, Employment, etc.).
"""

DPDP_LAYER = {
    "code": "dpdp",
    "name": "DPDP Act 2023 Compliance",
    "description": "Digital Personal Data Protection Act 2023 — reviews contracts for DPDP compliance gaps. Covers consent, data principal rights, breach notification, cross-border transfers, and penalty allocation.",
    "jurisdiction": "IN",
    "rules": [
        {
            "clause_type": "dpdp_consent_mechanism",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Contract must specify lawful basis for processing personal data under DPDP Act 2023. Consent must be free, specific, informed, unconditional, and unambiguous (Section 6).",
            "fallback_position": "At minimum, contract must identify the lawful basis for processing and require consent to be freely given.",
            "detection_patterns": ["consent", "personal data", "data principal", "lawful basis", "processing"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing or inadequate consent mechanism under DPDP Act 2023 Section 6",
            "acceptable_position": "Consent mechanism compliant with DPDP Act Section 6 — free, specific, informed, unconditional, unambiguous",
            "unacceptable_signals": ["blanket consent", "deemed consent for unrelated purposes", "no consent mechanism", "consent bundled with other terms"],
            "acceptable_signals": ["free and informed consent", "specific purpose", "unconditional consent", "DPDP Section 6"],
            "sort_order": 0,
        },
        {
            "clause_type": "dpdp_data_principal_rights",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Must enable Data Principal rights: right to access (Section 11), right to correction/erasure (Section 12), right to grievance redressal (Section 13), right to nominate (Section 14).",
            "fallback_position": "At minimum, contract must acknowledge data principal rights to access and correction.",
            "detection_patterns": ["data principal", "access", "correction", "erasure", "grievance", "nominate"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Contract does not preserve Data Principal rights under DPDP Act Sections 11-14",
            "acceptable_position": "All four Data Principal rights explicitly preserved and operationalized",
            "unacceptable_signals": ["no mention of data principal rights", "waiver of rights", "rights at discretion of fiduciary"],
            "acceptable_signals": ["right to access", "right to correction", "right to erasure", "grievance redressal", "right to nominate"],
            "sort_order": 1,
        },
        {
            "clause_type": "dpdp_fiduciary_obligations",
            "risk_level": "RED",
            "is_deal_breaker": False,
            "primary_position": "Data Fiduciary must implement reasonable security safeguards (Section 8(4)), ensure data accuracy, and delete data when purpose is fulfilled or consent withdrawn (Section 8(7)).",
            "fallback_position": "Data Fiduciary acknowledges obligation to maintain security safeguards and data accuracy.",
            "detection_patterns": ["data fiduciary", "security safeguard", "data accuracy", "data deletion", "purpose limitation"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing Data Fiduciary obligations under DPDP Act Section 8",
            "acceptable_position": "Fiduciary obligations clearly stated with security safeguards, accuracy requirements, and deletion timelines",
            "unacceptable_signals": ["no security obligations", "fiduciary has no duty", "as-is data handling"],
            "acceptable_signals": ["reasonable security safeguards", "ensure accuracy", "delete when purpose fulfilled"],
            "sort_order": 2,
        },
        {
            "clause_type": "dpdp_breach_notification",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Data Fiduciary must notify the Data Protection Board of India AND affected Data Principals of any personal data breach without undue delay, in the prescribed form (Section 8(6)).",
            "fallback_position": "Breach notification to the Data Protection Board within 72 hours at minimum.",
            "detection_patterns": ["breach notification", "data breach", "security incident", "data protection board", "notify"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing or inadequate breach notification under DPDP Act Section 8(6)",
            "acceptable_position": "Breach notification to DPB and affected data principals without undue delay in prescribed form",
            "unacceptable_signals": ["no breach notification", "notification only to board", "notification delayed beyond 72 hours", "breach notification at discretion"],
            "acceptable_signals": ["notify data protection board", "notify affected data principals", "without undue delay", "72 hours"],
            "sort_order": 3,
        },
        {
            "clause_type": "dpdp_cross_border_transfer",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Personal data may only be transferred outside India to countries/territories notified by the Central Government (Section 16). Transfer to restricted/blacklisted countries is prohibited.",
            "fallback_position": "Cross-border transfers restricted to government-notified countries with adequate safeguards.",
            "detection_patterns": ["cross-border", "data transfer", "outside India", "international transfer", "data localization", "transfer outside"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Non-compliant cross-border data transfer provisions under DPDP Act Section 16",
            "acceptable_position": "Transfers only to notified countries with adequate data protection standards",
            "unacceptable_signals": ["unrestricted transfer", "no mention of transfer restrictions", "transfer to any country", "data may be stored anywhere"],
            "acceptable_signals": ["notified countries only", "government-approved jurisdictions", "data localization", "transfer restrictions"],
            "sort_order": 4,
        },
        {
            "clause_type": "dpdp_consent_manager",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "If using a Consent Manager, it must be registered with the Data Protection Board. Contract should specify Consent Manager obligations (Section 9).",
            "fallback_position": "Acknowledge Consent Manager framework and registration requirements.",
            "detection_patterns": ["consent manager", "consent management", "consent platform", "consent framework"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Consent Manager framework (effective Nov 2026) not addressed",
            "acceptable_position": "Consent Manager registered with DPB and obligations clearly defined",
            "unacceptable_signals": ["unregistered consent manager", "consent manager not mentioned"],
            "acceptable_signals": ["registered consent manager", "DPB registration", "consent management platform"],
            "sort_order": 5,
        },
        {
            "clause_type": "dpdp_processor_agreement",
            "risk_level": "RED",
            "is_deal_breaker": False,
            "primary_position": "If processing is outsourced, a valid Data Processing Agreement must exist. Processor must process only on behalf of and per instructions of the Data Fiduciary (Section 8(2)).",
            "fallback_position": "Processor acknowledges it acts only on instructions of the Data Fiduciary.",
            "detection_patterns": ["data processor", "processing agreement", "sub-processor", "outsource", "on behalf of"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing or inadequate Data Processor agreement under DPDP Act Section 8(2)",
            "acceptable_position": "Valid DPA with processor acting strictly per fiduciary instructions",
            "unacceptable_signals": ["no processing agreement", "processor acts independently", "processor may use data for own purposes"],
            "acceptable_signals": ["processing agreement", "per instructions of fiduciary", "on behalf of data fiduciary"],
            "sort_order": 6,
        },
        {
            "clause_type": "dpdp_childrens_data",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "If processing children's data (under 18), verifiable parental consent is required. No behavioral monitoring or targeted advertising directed at children (Section 9).",
            "fallback_position": "Acknowledge restrictions on children's data processing if applicable.",
            "detection_patterns": ["children", "minor", "parental consent", "age verification", "under 18", "child"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Children's data protections not addressed (DPDP Act Section 9)",
            "acceptable_position": "Verifiable parental consent required; no behavioral monitoring of children",
            "unacceptable_signals": ["no age verification", "children's data treated same as adults", "behavioral tracking of minors"],
            "acceptable_signals": ["parental consent", "age verification", "no behavioral monitoring of children"],
            "sort_order": 7,
        },
        {
            "clause_type": "dpdp_purpose_limitation",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "Personal data must be processed only for the specific purpose for which consent was given. Any secondary use requires fresh consent (Section 6(1)).",
            "fallback_position": "Processing limited to stated purposes; secondary use requires additional consent.",
            "detection_patterns": ["purpose limitation", "specified purpose", "secondary use", "additional processing", "purpose of processing"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Vague or overly broad purpose specification under DPDP Act Section 6(1)",
            "acceptable_position": "Purpose clearly specified; secondary use requires fresh consent",
            "unacceptable_signals": ["broad purpose", "any lawful purpose", "future purposes", "any purpose deemed necessary"],
            "acceptable_signals": ["specific purpose", "limited to stated purpose", "fresh consent for secondary use"],
            "sort_order": 8,
        },
        {
            "clause_type": "dpdp_data_retention",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "Data must be erased when no longer necessary for the purpose or when consent is withdrawn, unless retention required by law (Section 8(7)).",
            "fallback_position": "Data retention period defined; erasure upon purpose completion or consent withdrawal.",
            "detection_patterns": ["data retention", "retention period", "data erasure", "data deletion", "storage limitation", "retain"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing data retention/erasure provisions under DPDP Act Section 8(7)",
            "acceptable_position": "Defined retention period with erasure upon purpose completion or consent withdrawal",
            "unacceptable_signals": ["indefinite retention", "no retention period", "perpetual storage", "data kept forever"],
            "acceptable_signals": ["retention period defined", "erase when purpose fulfilled", "delete upon consent withdrawal"],
            "sort_order": 9,
        },
        {
            "clause_type": "dpdp_significant_fiduciary",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "If classified as Significant Data Fiduciary (Section 10), must appoint a Data Protection Officer (resident in India), conduct periodic Data Protection Impact Assessments, and submit audit reports.",
            "fallback_position": "Acknowledge Significant Data Fiduciary obligations if applicable.",
            "detection_patterns": ["significant data fiduciary", "data protection officer", "DPO", "impact assessment", "DPIA", "audit report"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Significant Data Fiduciary obligations not addressed (DPDP Act Section 10)",
            "acceptable_position": "DPO appointed (India-resident), periodic DPIAs conducted, audit reports submitted",
            "unacceptable_signals": ["no DPO", "no impact assessment", "significant fiduciary not addressed"],
            "acceptable_signals": ["data protection officer", "DPIA", "audit reports", "impact assessment"],
            "sort_order": 10,
        },
        {
            "clause_type": "dpdp_penalty_indemnification",
            "risk_level": "RED",
            "is_deal_breaker": False,
            "primary_position": "Contract must allocate liability for DPDP penalties (up to Rs 250 crore per violation). Indemnification should cover regulatory fines, breach costs, and data principal compensation.",
            "fallback_position": "At minimum, parties acknowledge DPDP penalty exposure and allocate liability for regulatory fines.",
            "detection_patterns": ["penalty", "fine", "indemnif", "regulatory", "250 crore", "data protection board", "DPDP penalty"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "DPDP penalty exposure (up to Rs 250 crore) not allocated in contract",
            "acceptable_position": "Liability for DPDP penalties allocated; indemnification covers fines, breach costs, and compensation",
            "unacceptable_signals": ["no penalty allocation", "one-sided indemnification favoring processor", "no mention of regulatory fines"],
            "acceptable_signals": ["indemnification for DPDP penalties", "liability allocation", "regulatory fine coverage", "250 crore"],
            "sort_order": 11,
        },
    ],
}
