"""
DPDP Act 2023 Compliance Layer — 18 rules for Digital Personal Data Protection Act compliance.
This layer can be toggled ON alongside any playbook (MSA, SaaS, Employment, etc.).
Covers all DPDP sections 4-17 for comprehensive compliance scanning.
"""

DPDP_LAYER = {
    "code": "dpdp",
    "name": "DPDP Act 2023 Compliance",
    "description": "Digital Personal Data Protection Act 2023 — reviews contracts for DPDP compliance gaps. Covers consent, data principal rights, breach notification, cross-border transfers, and penalty allocation.",
    "jurisdiction": "IN",
    "rules": [
        {
            "clause_type": "dpdp_consent_mechanism",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Contract must specify lawful basis for processing personal data under DPDP Act 2023. Consent must be free, specific, informed, unconditional, and unambiguous (Section 6).",
            "fallback_position": "At minimum, contract must identify the lawful basis for processing and require consent to be freely given.",
            "detection_patterns": ["consent", "personal data", "data principal", "lawful basis", "processing"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing or inadequate consent mechanism under DPDP Act 2023 Section 6",
            "acceptable_position": "Consent mechanism compliant with DPDP Act Section 6 — free, specific, informed, unconditional, unambiguous",
            "unacceptable_signals": ["blanket consent", "deemed consent for unrelated purposes", "no consent mechanism", "consent bundled with other terms"],
            "acceptable_signals": ["free and informed consent", "specific purpose", "unconditional consent", "DPDP Section 6"],
            "sort_order": 0,
        },
        {
            "clause_type": "dpdp_data_principal_rights",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Must enable Data Principal rights: right to access (Section 11), right to correction/erasure (Section 12), right to grievance redressal (Section 13), right to nominate (Section 14).",
            "fallback_position": "At minimum, contract must acknowledge data principal rights to access and correction.",
            "detection_patterns": ["data principal", "access", "correction", "erasure", "grievance", "nominate"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Contract does not preserve Data Principal rights under DPDP Act Sections 11-14",
            "acceptable_position": "All four Data Principal rights explicitly preserved and operationalized",
            "unacceptable_signals": ["no mention of data principal rights", "waiver of rights", "rights at discretion of fiduciary"],
            "acceptable_signals": ["right to access", "right to correction", "right to erasure", "grievance redressal", "right to nominate"],
            "sort_order": 1,
        },
        {
            "clause_type": "dpdp_fiduciary_obligations",
            "risk_level": "RED",
            "is_deal_breaker": False,
            "primary_position": "Data Fiduciary must implement reasonable security safeguards (Section 8(4)), ensure data accuracy, and delete data when purpose is fulfilled or consent withdrawn (Section 8(7)).",
            "fallback_position": "Data Fiduciary acknowledges obligation to maintain security safeguards and data accuracy.",
            "detection_patterns": ["data fiduciary", "security safeguard", "data accuracy", "data deletion", "purpose limitation"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing Data Fiduciary obligations under DPDP Act Section 8",
            "acceptable_position": "Fiduciary obligations clearly stated with security safeguards, accuracy requirements, and deletion timelines",
            "unacceptable_signals": ["no security obligations", "fiduciary has no duty", "as-is data handling"],
            "acceptable_signals": ["reasonable security safeguards", "ensure accuracy", "delete when purpose fulfilled"],
            "sort_order": 2,
        },
        {
            "clause_type": "dpdp_breach_notification",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Data Fiduciary must notify the Data Protection Board of India AND affected Data Principals of any personal data breach without undue delay, in the prescribed form (Section 8(6)).",
            "fallback_position": "Breach notification to the Data Protection Board within 72 hours at minimum.",
            "detection_patterns": ["breach notification", "data breach", "security incident", "data protection board", "notify"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing or inadequate breach notification under DPDP Act Section 8(6)",
            "acceptable_position": "Breach notification to DPB and affected data principals without undue delay in prescribed form",
            "unacceptable_signals": ["no breach notification", "notification only to board", "notification delayed beyond 72 hours", "breach notification at discretion"],
            "acceptable_signals": ["notify data protection board", "notify affected data principals", "without undue delay", "72 hours"],
            "sort_order": 3,
        },
        {
            "clause_type": "dpdp_cross_border_transfer",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Personal data may only be transferred outside India to countries/territories notified by the Central Government (Section 16). Transfer to restricted/blacklisted countries is prohibited.",
            "fallback_position": "Cross-border transfers restricted to government-notified countries with adequate safeguards.",
            "detection_patterns": ["cross-border", "data transfer", "outside India", "international transfer", "data localization", "transfer outside"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Non-compliant cross-border data transfer provisions under DPDP Act Section 16",
            "acceptable_position": "Transfers only to notified countries with adequate data protection standards",
            "unacceptable_signals": ["unrestricted transfer", "no mention of transfer restrictions", "transfer to any country", "data may be stored anywhere"],
            "acceptable_signals": ["notified countries only", "government-approved jurisdictions", "data localization", "transfer restrictions"],
            "sort_order": 4,
        },
        {
            "clause_type": "dpdp_consent_manager",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "If using a Consent Manager, it must be registered with the Data Protection Board. Contract should specify Consent Manager obligations (Section 9).",
            "fallback_position": "Acknowledge Consent Manager framework and registration requirements.",
            "detection_patterns": ["consent manager", "consent management", "consent platform", "consent framework"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Consent Manager framework (effective Nov 2026) not addressed",
            "acceptable_position": "Consent Manager registered with DPB and obligations clearly defined",
            "unacceptable_signals": ["unregistered consent manager", "consent manager not mentioned"],
            "acceptable_signals": ["registered consent manager", "DPB registration", "consent management platform"],
            "sort_order": 5,
        },
        {
            "clause_type": "dpdp_processor_agreement",
            "risk_level": "RED",
            "is_deal_breaker": False,
            "primary_position": "If processing is outsourced, a valid Data Processing Agreement must exist. Processor must process only on behalf of and per instructions of the Data Fiduciary (Section 8(2)).",
            "fallback_position": "Processor acknowledges it acts only on instructions of the Data Fiduciary.",
            "detection_patterns": ["data processor", "processing agreement", "sub-processor", "outsource", "on behalf of"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing or inadequate Data Processor agreement under DPDP Act Section 8(2)",
            "acceptable_position": "Valid DPA with processor acting strictly per fiduciary instructions",
            "unacceptable_signals": ["no processing agreement", "processor acts independently", "processor may use data for own purposes"],
            "acceptable_signals": ["processing agreement", "per instructions of fiduciary", "on behalf of data fiduciary"],
            "sort_order": 6,
        },
        {
            "clause_type": "dpdp_childrens_data",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "If processing children's data (under 18), verifiable parental consent is required. No behavioral monitoring or targeted advertising directed at children (Section 9).",
            "fallback_position": "Acknowledge restrictions on children's data processing if applicable.",
            "detection_patterns": ["children", "minor", "parental consent", "age verification", "under 18", "child"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Children's data protections not addressed (DPDP Act Section 9)",
            "acceptable_position": "Verifiable parental consent required; no behavioral monitoring of children",
            "unacceptable_signals": ["no age verification", "children's data treated same as adults", "behavioral tracking of minors"],
            "acceptable_signals": ["parental consent", "age verification", "no behavioral monitoring of children"],
            "sort_order": 7,
        },
        {
            "clause_type": "dpdp_purpose_limitation",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "Personal data must be processed only for the specific purpose for which consent was given. Any secondary use requires fresh consent (Section 6(1)).",
            "fallback_position": "Processing limited to stated purposes; secondary use requires additional consent.",
            "detection_patterns": ["purpose limitation", "specified purpose", "secondary use", "additional processing", "purpose of processing"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Vague or overly broad purpose specification under DPDP Act Section 6(1)",
            "acceptable_position": "Purpose clearly specified; secondary use requires fresh consent",
            "unacceptable_signals": ["broad purpose", "any lawful purpose", "future purposes", "any purpose deemed necessary"],
            "acceptable_signals": ["specific purpose", "limited to stated purpose", "fresh consent for secondary use"],
            "sort_order": 8,
        },
        {
            "clause_type": "dpdp_data_retention",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "Data must be erased when no longer necessary for the purpose or when consent is withdrawn, unless retention required by law (Section 8(7)).",
            "fallback_position": "Data retention period defined; erasure upon purpose completion or consent withdrawal.",
            "detection_patterns": ["data retention", "retention period", "data erasure", "data deletion", "storage limitation", "retain"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing data retention/erasure provisions under DPDP Act Section 8(7)",
            "acceptable_position": "Defined retention period with erasure upon purpose completion or consent withdrawal",
            "unacceptable_signals": ["indefinite retention", "no retention period", "perpetual storage", "data kept forever"],
            "acceptable_signals": ["retention period defined", "erase when purpose fulfilled", "delete upon consent withdrawal"],
            "sort_order": 9,
        },
        {
            "clause_type": "dpdp_significant_fiduciary",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "If classified as Significant Data Fiduciary (Section 10), must appoint a Data Protection Officer (resident in India), conduct periodic Data Protection Impact Assessments, and submit audit reports.",
            "fallback_position": "Acknowledge Significant Data Fiduciary obligations if applicable.",
            "detection_patterns": ["significant data fiduciary", "data protection officer", "DPO", "impact assessment", "DPIA", "audit report"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Significant Data Fiduciary obligations not addressed (DPDP Act Section 10)",
            "acceptable_position": "DPO appointed (India-resident), periodic DPIAs conducted, audit reports submitted",
            "unacceptable_signals": ["no DPO", "no impact assessment", "significant fiduciary not addressed"],
            "acceptable_signals": ["data protection officer", "DPIA", "audit reports", "impact assessment"],
            "sort_order": 10,
        },
        {
            "clause_type": "dpdp_penalty_indemnification",
            "risk_level": "RED",
            "is_deal_breaker": False,
            "primary_position": "Contract must allocate liability for DPDP penalties (up to Rs 250 crore per violation). Indemnification should cover regulatory fines, breach costs, and data principal compensation.",
            "fallback_position": "At minimum, parties acknowledge DPDP penalty exposure and allocate liability for regulatory fines.",
            "detection_patterns": ["penalty", "fine", "indemnif", "regulatory", "250 crore", "data protection board", "DPDP penalty"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "DPDP penalty exposure (up to Rs 250 crore) not allocated in contract",
            "acceptable_position": "Liability for DPDP penalties allocated; indemnification covers fines, breach costs, and compensation",
            "unacceptable_signals": ["no penalty allocation", "one-sided indemnification favoring processor", "no mention of regulatory fines"],
            "acceptable_signals": ["indemnification for DPDP penalties", "liability allocation", "regulatory fine coverage", "250 crore"],
            "sort_order": 11,
        },
        # ---- New rules (12-17) for comprehensive coverage ----
        {
            "clause_type": "dpdp_notice_requirements",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Data Fiduciary must provide clear notice to Data Principals before or at the time of collecting personal data, describing the data collected, purposes, rights, and how to exercise them (Section 5).",
            "fallback_position": "At minimum, a privacy notice must be provided describing the purpose of data collection.",
            "detection_patterns": ["notice", "privacy notice", "inform", "transparency", "privacy policy"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Missing or inadequate privacy notice under DPDP Act Section 5",
            "acceptable_position": "Clear, comprehensive privacy notice provided before or at time of data collection",
            "unacceptable_signals": ["no notice provided", "notice not given", "no privacy policy", "data collected without informing"],
            "acceptable_signals": ["privacy notice", "informed before collection", "notice provided", "transparency notice"],
            "sort_order": 12,
        },
        {
            "clause_type": "dpdp_lawful_purpose",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "Processing must be for a lawful purpose — one not expressly forbidden by law (Section 4). Contract must clearly state the lawful basis for processing.",
            "fallback_position": "Processing purpose stated and not contrary to any applicable law.",
            "detection_patterns": ["lawful purpose", "legal basis", "legitimate purpose", "processing grounds", "lawful basis"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Lawful basis for processing not clearly established (DPDP Act Section 4)",
            "acceptable_position": "Lawful basis clearly stated — either consent (Section 6) or legitimate use (Section 7)",
            "unacceptable_signals": ["no lawful basis", "purpose not stated", "processing without justification"],
            "acceptable_signals": ["lawful purpose", "legal basis established", "consent-based processing", "legitimate use"],
            "sort_order": 13,
        },
        {
            "clause_type": "dpdp_data_accuracy",
            "risk_level": "YELLOW",
            "is_deal_breaker": False,
            "primary_position": "Data Fiduciary must ensure completeness, accuracy, and consistency of personal data, especially when used for decisions affecting the Data Principal or shared with others (Section 8(3)).",
            "fallback_position": "Data accuracy obligations acknowledged for decision-making scenarios.",
            "detection_patterns": ["data accuracy", "accurate data", "data quality", "completeness", "consistency"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Data accuracy obligations not addressed (DPDP Act Section 8(3))",
            "acceptable_position": "Data accuracy, completeness, and consistency obligations clearly stated",
            "unacceptable_signals": ["no accuracy obligation", "as-is data", "no quality guarantees"],
            "acceptable_signals": ["ensure accuracy", "data quality", "complete and accurate", "consistent data"],
            "sort_order": 14,
        },
        {
            "clause_type": "dpdp_grievance_officer",
            "risk_level": "RED",
            "is_deal_breaker": True,
            "primary_position": "Data Fiduciary must appoint a Grievance Officer to address Data Principal complaints. Officer contact details must be published. Response required within prescribed time (Section 13).",
            "fallback_position": "At minimum, a point of contact for data-related complaints must be designated.",
            "detection_patterns": ["grievance officer", "grievance redressal", "complaint officer", "data protection officer", "complaint mechanism"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "No Grievance Officer or complaint mechanism designated (DPDP Act Section 13)",
            "acceptable_position": "Grievance Officer appointed with published contact details and response SLA",
            "unacceptable_signals": ["no grievance mechanism", "no complaint process", "no designated officer"],
            "acceptable_signals": ["grievance officer", "complaint mechanism", "redressal officer", "respond within"],
            "sort_order": 15,
        },
        {
            "clause_type": "dpdp_consent_withdrawal",
            "risk_level": "RED",
            "is_deal_breaker": False,
            "primary_position": "Data Principal must be able to withdraw consent at any time with the same ease as granting it. Withdrawal must not result in penalties or disadvantage (Section 6(6)).",
            "fallback_position": "Consent withdrawal mechanism available; no penalties for withdrawal.",
            "detection_patterns": ["withdraw consent", "revoke consent", "opt out", "consent withdrawal", "right to withdraw"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Consent withdrawal mechanism missing or made difficult (DPDP Act Section 6(6))",
            "acceptable_position": "Easy consent withdrawal with no penalties; same ease as granting consent",
            "unacceptable_signals": ["cannot withdraw", "penalty for withdrawal", "withdrawal fee", "consent irrevocable", "difficult to withdraw"],
            "acceptable_signals": ["withdraw at any time", "easy withdrawal", "no penalty for withdrawal", "right to revoke"],
            "sort_order": 16,
        },
        {
            "clause_type": "dpdp_data_principal_duties",
            "risk_level": "GREEN",
            "is_deal_breaker": False,
            "primary_position": "Data Principals have duties under Section 15: not to file false complaints, provide accurate information, and comply with applicable laws when exercising rights.",
            "fallback_position": "Contract may reference Data Principal obligations under applicable law.",
            "detection_patterns": ["data principal duties", "principal obligations", "accurate information", "false complaint"],
            "detection_mode": "ai_with_keywords",
            "risk_description": "Data Principal duties under Section 15 not referenced (informational)",
            "acceptable_position": "Data Principal duties referenced — accurate information, no false complaints",
            "unacceptable_signals": [],
            "acceptable_signals": ["data principal duties", "accurate information obligation", "no false complaints"],
            "sort_order": 17,
        },
    ],
}
